#!/usr/bin/env python3
"""Generate InternalSlashCommands.xml for client patch 012-gm-slash-commands.

Reads the project-maintained table
    data/client-patches/012-gm-slash-commands/commands.toml
and writes the XML the 2009 client loads at startup from
    <install>/Common/xml/slash_commands/InternalSlashCommands.xml

The file is authored by this project from identifiers and types only. It carries
no CME-authored text: every Description and ParamDescription is empty, every Usage
is built here from the command word and its parameter names, and the only comment
is the generated-file note below. Schema and parser findings (SGW.exe, Ghidra,
2026-10-05) are in data/client-patches/README.md, patch 012.

Usage:
    python tools/client-patches/gm_slash_commands.py            # rewrite the XML
    python tools/client-patches/gm_slash_commands.py --check    # fail if it is stale
    python tools/client-patches/gm_slash_commands.py --summary  # counts and masks

The output is ASCII with CRLF line endings, like the client's own XML, and is
deterministic: the same table always gives the same bytes (the zip hash depends on it).
"""
import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATCH_DIR = ROOT / "data" / "client-patches" / "012-gm-slash-commands"
TABLE = PATCH_DIR / "commands.toml"
XML = PATCH_DIR / "InternalSlashCommands.xml"

# The namespace the client's generated parser matches elements and attributes
# against. It is an identifier, not a link: nothing is fetched from it.
NAMESPACE = "http://www.cheyenneme.com/common/slash_commands"

# The client's Access parser (SGW.exe 0x00a4c530) tests these ten letters in this
# order and ORs 1 << index into the command's mask: guide, CSR, lead CSR, QA, lead
# QA, artist, designer, lead designer, programmer, management.
ROLE_LETTERS = "gcCqQadDpm"

PARAM_TYPES = {"Boolean", "Integer", "Float", "String"}
COMMAND_RE = re.compile(r"^/[a-z][a-z0-9]*$")
EVENT_RE = re.compile(r"^Event_SlashCmd_[A-Za-z0-9]+$")
NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9/-]*$")  # e.g. DesignId, on/off, X-Coordinate

HEADER = (
    "  <!-- Generated by tools/client-patches/gm_slash_commands.py from "
    "data/client-patches/012-gm-slash-commands/commands.toml. Do not edit by hand. -->"
)


def access_mask(access: str) -> int:
    """The mask SGW.exe computes from an Access attribute.

    The shipped code asks a std::wstring for the position of each role letter and
    sets the bit when the answer is non-zero. A letter found at position 0 answers
    0, and a letter not found answers npos (non-zero), so both the first letter's
    role is left out and every absent role is put in.
    """
    mask = 0
    for bit, letter in enumerate(ROLE_LETTERS):
        if access.find(letter) != 0:
            mask |= 1 << bit
    return mask


class TableError(ValueError):
    pass


def parse_param(text: str, where: str) -> tuple[str, str]:
    parts = text.split(" ")
    if len(parts) != 2:
        raise TableError(f"{where}: parameter {text!r} must be '<Type> <Name>'")
    ptype, name = parts
    if ptype not in PARAM_TYPES:
        raise TableError(f"{where}: parameter type {ptype!r} is not one of {sorted(PARAM_TYPES)}")
    if not NAME_RE.match(name):
        raise TableError(f"{where}: parameter name {name!r} is not a single word (letters, digits, - or /)")
    return ptype, name


def load_table(path: Path = TABLE) -> list[dict]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    default_access = data.get("access", "")
    if not default_access or any(c not in ROLE_LETTERS for c in default_access):
        raise TableError(f"access {default_access!r}: letters must come from {ROLE_LETTERS}")
    commands = []
    seen = set()
    for i, entry in enumerate(data.get("command", [])):
        name = entry.get("name", "")
        where = f"command #{i + 1} {name!r}"
        unknown = set(entry) - {"name", "event", "params", "optional", "access"}
        if unknown:
            raise TableError(f"{where}: unknown keys {sorted(unknown)}")
        if not COMMAND_RE.match(name):
            raise TableError(f"{where}: command word must match {COMMAND_RE.pattern}")
        if name in seen:
            # The client's map keeps one entry per word; a duplicate here would
            # silently replace the first.
            raise TableError(f"{where}: duplicate command word")
        seen.add(name)
        event = entry.get("event", "")
        if not EVENT_RE.match(event):
            raise TableError(f"{where}: event {event!r} must match {EVENT_RE.pattern}")
        access = entry.get("access", default_access)
        if not access or any(c not in ROLE_LETTERS for c in access):
            raise TableError(f"{where}: access {access!r}: letters must come from {ROLE_LETTERS}")
        mandatory = [parse_param(p, where) for p in entry.get("params", [])]
        optional = [parse_param(p, where) for p in entry.get("optional", [])]
        commands.append(
            {
                "name": name,
                "event": event,
                "access": access,
                "mandatory": mandatory,
                "optional": optional,
            }
        )
    if not commands:
        raise TableError("the table has no commands")
    return commands


def usage(cmd: dict) -> str:
    words = [cmd["name"]]
    # Square brackets for a required parameter, round for an optional one: the
    # client prints Usage into chat, and a literal "<" is the riskier character
    # there (CME's own file mostly uses [name] for required ones too).
    words += [f"[{n}]" for _, n in cmd["mandatory"]]
    words += [f"({n})" for _, n in cmd["optional"]]
    return " ".join(words)


def attr_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def render(commands: list[dict]) -> bytes:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<CommandList xmlns="{NAMESPACE}" xmlns:scmd="{NAMESPACE}">',
        HEADER,
    ]
    for cmd in commands:
        lines.append(
            f'  <scmd:Command scmd:CommandName="{attr_escape(cmd["name"])}"'
            f' scmd:Access="{cmd["access"]}" scmd:Description=""'
            f' scmd:EventName="{cmd["event"]}"'
            f' scmd:Usage="{attr_escape(usage(cmd))}">'
        )
        for tag, params in (("MandatoryParam", cmd["mandatory"]), ("OptionalParam", cmd["optional"])):
            for ptype, name in params:
                lines.append(
                    f'    <scmd:{tag} scmd:PType="{ptype}" scmd:ParamName="{name}"'
                    ' scmd:ParamDescription=""/>'
                )
        lines.append("  </scmd:Command>")
    lines.append("</CommandList>")
    text = "\r\n".join(lines) + "\r\n"
    return text.encode("ascii")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed XML is stale")
    ap.add_argument("--summary", action="store_true", help="print counts and masks")
    ap.add_argument("--table", type=Path, default=TABLE, help="read this table instead (experiments)")
    ap.add_argument("--out", type=Path, default=XML, help="write this file instead (experiments)")
    args = ap.parse_args()
    try:
        commands = load_table(args.table)
    except TableError as err:
        print(f"error: {err}", file=sys.stderr)
        return 2
    xml = render(commands)
    if args.summary:
        masks = {}
        for c in commands:
            masks.setdefault(access_mask(c["access"]), []).append(c["name"])
        print(f"{len(commands)} commands, {len(xml)} bytes")
        for mask, names in sorted(masks.items()):
            print(f"  mask 0x{mask:03X}: {len(names)} commands")
        return 0
    if args.check:
        if not args.out.exists() or args.out.read_bytes() != xml:
            print(f"error: {args.out} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"ok: {len(commands)} commands, {args.out} is current")
        return 0
    args.out.write_bytes(xml)
    print(f"wrote {args.out}: {len(commands)} commands, {len(xml)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
