--
-- Cover sets: one row per UE3 cover-prefab "chunk" extracted from the SGW
-- client cache (covernodes_*.pak archives). Each cover set is a named
-- group of cover nodes that ships together as a placeable prefab
-- (fences, half-walls, doorways, etc.). Per the V5 reverse-engineering
-- in docs/reverse-engineering/findings/cover-system.md, this is the
-- server-only `SGWCoverSet` entity's source data — clients never see
-- it directly; they observe the consequences via
-- `onEnterCoverSet`/`onLeaveCoverSet` on the SGWCombatant interface.
--
-- Seed data is auto-generated by `tools/ue3_extract_cover_nodes.py`
-- from the canonical `covernodes_nikols.pak` + unioned alt
-- `covernodes_sdeiter.pak`. Issue: #209.
--
-- Name: cover_sets; Type: TABLE; Schema: resources; Owner: -
--

CREATE TABLE cover_sets (
    chunk_id integer NOT NULL,
    chunk_name character varying(128) NOT NULL,
    primary_author character varying(64) NOT NULL,
    has_variant boolean DEFAULT false NOT NULL,
    src_pak character varying(64) NOT NULL
);
