--
-- Cover sets: one row per group of world-space cover nodes. A set is the
-- unit the NPC cover scorer reserves against and the content engine keys
-- `player_entered_cover` / `player_left_cover` on (the `cover_set_id`
-- trigger param is this `chunk_id`). Per the V5 reverse-engineering in
-- docs/reverse-engineering/findings/cover-system.md, this is the
-- server-only `SGWCoverSet` entity's source data -- clients never see it
-- directly; they observe the consequences via
-- `onEnterCoverSet`/`onLeaveCoverSet` on the SGWCombatant interface.
--
-- Every row is scoped to one world (`world_id`): node positions are world
-- coordinates, and the cell service keeps one spatial index per world so a
-- query in one world never returns another's cover.
--
-- Seed data is generated by the `cover_extract` binary
-- (crates/navmesh-extractor) from the `SGWSpecCoverNode` actors and
-- `StaticMeshActor.CoverNodeArray` components baked into each map's .umap
-- chunks -- docs/engine/cover-extraction.md. `chunk_id` is
-- `world_id * 100000 + n`; `chunk_name` names the source chunk, pattern
-- and first component export; `src_pak` is the source .umap chunk. The
-- column names predate the extractor (they described the retired
-- covernodes_*.pak prefab corpus) and are kept so the loader and the
-- content-engine payloads do not change shape.
--
-- Name: cover_sets; Type: TABLE; Schema: resources; Owner: -
--

CREATE TABLE cover_sets (
    chunk_id integer NOT NULL,
    world_id integer NOT NULL,
    chunk_name character varying(128) NOT NULL,
    primary_author character varying(64) NOT NULL,
    has_variant boolean DEFAULT false NOT NULL,
    src_pak character varying(64) NOT NULL
);
