# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants
from cell.Minigame import Minigame
from common.Config import Config
import Atrea

class SecurityOffice(Script):
	n71_var_Player = None
	n110_var_Player = None
	def n111_trigger_In(self):
		if self.n111_var_Player is None or not 5168:
			return
		if not 2:
			added = self.n111_var_Player.inventory.pickedUpItem(5168, 1 or 1)
		else:
			added = self.n111_var_Player.inventory.addItem(2, 5168, 1 or 1)
		self.n111_var_Player.inventory.flushUpdates()
		if added:
			status = self.n142_var_Player.missions.getStepStatus(1561, 4621)
		else:
			pass

	n111_var_Player = None
	n112_var_Player = None
	def n112_propagator_Player(self):
		self.n111_var_Player = self.n112_var_Player
		self.n142_var_Player = self.n112_var_Player
		self.n148_var_Player = self.n112_var_Player
		self.n113_var_Player = self.n112_var_Player
		self.n156_var_Player = self.n112_var_Player

	def n113_trigger_In(self):
		status = self.n113_var_Player.missions.getStepStatus(1561, 4620)
		if status == Constants.MISSION_Active:
			self.n156_var_Player.displayDialog(None, 5362)
			self.n148_var_Player.missions.advance(1561, 4621)
			self.n111_trigger_In()

	n113_var_Player = None
	n122_var_Player = None
	n139_var_Player = None
	n142_var_Player = None
	n148_var_Player = None
	n149_var_Player = None
	n150_var_Player = None
	n151_var_Player = None
	n152_var_Player = None
	def n153_trigger_In(self):
		def mgHandler(self, result):
			if result == Constants.MINIGAME_RESULT_Victory:
				self.n155_var_Player.missions.advance(1561, 4623)
			elif result == Constants.MINIGAME_RESULT_Defeat:
				pass
			else:
				pass
		gameIds = [k for k, v in Config.MINIGAME_NAMES.items() if v == 'Livewire']
		assert(len(gameIds) == 1)
		minigame = Minigame('', 1, gameIds[0], 1, 0xffff, lambda mg, rc: mgHandler(self, rc))
		if not self.n153_var_Player.requestStartMinigame(minigame):
			pass

	n153_var_Player = None
	n154_var_Player = None
	n155_var_Player = None
	n156_var_Player = None
	n157_var_Player = None
	n158_var_Player = None
	n159_var_Player = None
	n160_var_Player = None
	n161_var_Player = None
	n162_var_Player = None
	n163_var_Player = None
	n164_var_Player = None
	n165_var_Entity = None
	def n166_trigger_In(self):
		self.n166_var_Entity = None
		if None is not None:
			self.n166_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGC_W1_ElevatorButton2'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n166_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n166_var_Entity = entity
						break
			else:
				self.n166_var_Entity = None
		self.n165_var_Entity = self.n166_var_Entity
		if self.n166_var_Entity is not None:
			entity = self.n165_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 256)

	n166_var_Entity = None
	n167_var_Player = None
	def n167_propagator_Player(self):
		self.n168_var_Player = self.n167_var_Player
		self.n170_var_Target = self.n167_var_Player
		self.n175_var_Player = self.n167_var_Player
		self.n176_var_Player = self.n167_var_Player
		self.n177_var_Source = self.n167_var_Player
		self.n177_var_Target = self.n167_var_Player

	n168_var_Player = None
	n170_var_Target = None
	n170_var_Destination = None
	n171_var_Set = None
	n171_var_Value = None
	def n175_trigger_Step(self):
		self.n175_var_Player.missions.advance(1562, 4625)
		pos = self.n170_var_Destination
		self.n170_var_Target.moveTo(pos.x, pos.y, pos.z, worldName = '' or None)
		self.n176_var_Player.displayDialog(None, 5366)
		self.n177_trigger_In()

	n175_var_Player = None
	n176_var_Player = None
	def n177_trigger_In(self):
		if self.n177_var_Source is not None and 10009 is not None:
			target = self.n177_var_Target
			targetId = target.entityId if target else None
			self.n177_var_Source.playSequence(10009, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n177_var_Source = None
	n177_var_Target = None
	n178_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n171_var_Value = self.str2vec('-53.86,1.311,62.136')
		self.n170_var_Destination = self.n171_var_Value
		self.n178_var_Player = self.owner
		self.n110_var_Player = self.n178_var_Player
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n71_var_Player = self.owner
			self.n110_var_Player = self.n71_var_Player
			return True
		self.n71_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGC_W1_FirearmBody', interactCb, once = False)
		def deadCb(args):
			self.n110_var_Player.displayDialog(None, 5359)
			return True
		self.n109_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'SGC_W1_JaffaBomb', deadCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n112_var_Player = self.owner
			self.n112_propagator_Player()
			self.n113_trigger_In()
			return True
		self.n112_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGCW1_AirmanBody', interactCb, once = False)
		def itemCb(params):
			self.n122_var_Player = params['player']
			self.n150_var_Player = self.n122_var_Player
			self.n151_var_Player = self.n122_var_Player
			self.n149_var_Player = self.n122_var_Player
			status = self.n150_var_Player.missions.getStepStatus(1561, 4621)
			if status == Constants.MISSION_Active:
				self.n149_var_Player.displayDialog(None, 5363)
				self.n151_var_Player.missions.advance(1561, 4622)
			return True
		self.n122_lvar_HandlerId = self.owner.subscribe('item.use::' + str(5168), itemCb, once = True)
		def dialogChoiceCb(args):
			self.n139_var_Player = args['player']
			self.n163_var_Player = self.n139_var_Player
			self.n164_var_Player = self.n139_var_Player
			status = self.n163_var_Player.missions.getMissionStatus(1561)
			if status == Constants.MISSION_Not_Active:
				self.n164_var_Player.missions.accept(1561)
			return True
		self.n139_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5359), dialogChoiceCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n152_var_Player = self.owner
			self.n155_var_Player = self.n152_var_Player
			self.n154_var_Player = self.n152_var_Player
			self.n153_var_Player = self.n152_var_Player
			status = self.n154_var_Player.missions.getStepStatus(1561, 4622)
			if status == Constants.MISSION_Active:
				self.n153_trigger_In()
			return True
		self.n152_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGC_W1_NaqBomb', interactCb, once = False)
		def itemCb(params):
			self.n157_var_Player = params['player']
			self.n159_var_Player = self.n157_var_Player
			self.n158_var_Player = self.n157_var_Player
			self.n162_var_Player = self.n157_var_Player
			status = self.n158_var_Player.missions.getStepStatus(1561, 4623)
			if status == Constants.MISSION_Active:
				self.n162_var_Player.missions.complete(1561)
				self.n159_var_Player.displayDialog(None, 5365)
			return True
		self.n157_lvar_HandlerId = self.owner.subscribe('item.use::' + str(5168), itemCb, once = True)
		def dialogChoiceCb(args):
			self.n160_var_Player = args['player']
			self.n161_var_Player = self.n160_var_Player
			self.n161_var_Player.missions.accept(1562)
			self.n166_trigger_In()
			return True
		self.n160_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5365), dialogChoiceCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n167_var_Player = self.owner
			self.n167_propagator_Player()
			status = self.n168_var_Player.missions.getStepStatus(1562, 4624)
			if status == Constants.MISSION_Active:
				self.n175_trigger_Step()
			return True
		self.n167_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGC_W1_ElevatorButton2', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n71_lvar_TagSubscriptionId)
		self.owner.space.unsubscribe(self.n109_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n112_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n122_lvar_HandlerId)
		self.owner.unsubscribe(self.n139_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n152_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n157_lvar_HandlerId)
		self.owner.unsubscribe(self.n160_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n167_lvar_TagSubscriptionId)

