function Update-CimmeriaClient {
    <#
    .SYNOPSIS
        Configures the Stargate Worlds game client to connect to the Cimmeria server.

    .DESCRIPTION
        Finds the Stargate Worlds client installation and drops a LoginInternal.lua
        file that overrides the login server list. This is the mechanism the client
        was designed for -- LoginInternal.lua defines LoginMod.loadServerSystems()
        which populates the server dropdown on the login screen.

        If LoginInternal.lua is not present, the client falls back to Login.lua's
        built-in server list (the original CME live servers, which no longer exist).

        The file is placed at:
          {ClientPath}/Working/SGWGame/Content/UI/Startup/Login/LoginInternal.lua

    .PARAMETER ClientPath
        Path to the SGW client root directory (e.g. "Stargate Worlds-QA").
        If not specified, searches common install locations automatically.

    .PARAMETER ServerAddress
        Full URL of the login server. Default: 127.0.0.1:8081

    .PARAMETER ServerName
        Display name for the server in the login dropdown. Default: Cimmeria

    .PARAMETER Launch
        Launch SGW.exe after patching.

    .PARAMETER NoLaunch
        Skip launching SGW.exe after patching.

    .PARAMETER Atrea
        Launch via AtreaLoader instead of SGW.exe directly. Enables Mercury
        protocol logging, PCAP capture, and AES session key dumping to
        {ClientBinaries}/sessions/.

    .EXAMPLE
        Update-CimmeriaClient

    .EXAMPLE
        Update-CimmeriaClient -ClientPath "F:\Stargate Worlds-QA"

    .EXAMPLE
        Update-CimmeriaClient -ServerAddress "http://play.cimmeria.gg:8081" -NoLaunch

    .EXAMPLE
        Update-CimmeriaClient -Atrea
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [string]$ClientPath,
        [string]$ServerAddress = "127.0.0.1:8081",
        [string]$ServerName = "Cimmeria",
        [switch]$Launch,
        [switch]$NoLaunch,
        [switch]$Atrea
    )

    Write-Step "PATCHING GAME CLIENT"

    # Find client installation
    if (-not $ClientPath) {
        # Search common install locations and sibling directories
        $scriptDrive = (Split-Path $PSScriptRoot -Qualifier)
        $searchPaths = @(
            "${scriptDrive}\Stargate Worlds-QA",
            "${env:ProgramFiles(x86)}\FireSky\Stargate Worlds-QA",
            "${env:ProgramFiles}\FireSky\Stargate Worlds-QA",
            "${env:ProgramFiles(x86)}\Cheyenne Mountain Entertainment\Stargate Worlds",
            "${env:ProgramFiles}\Cheyenne Mountain Entertainment\Stargate Worlds"
        )

        foreach ($search in $searchPaths) {
            if (Find-SgwExe $search) {
                $ClientPath = $search
                Write-Status "Found client: $ClientPath" "Green"
                break
            }
        }

        if (-not $ClientPath) {
            Write-Host ""
            Write-Host "Stargate Worlds client not found in common locations." -ForegroundColor Yellow
            Write-Host ""
            Write-Host "Please specify the path manually:" -ForegroundColor White
            Write-Host "  pwsh patch-client.ps1 -ClientPath 'F:\Stargate Worlds-QA'" -ForegroundColor Gray
            Write-Host ""
            Write-Host "The directory should contain Working\binaries\SGW.exe or SGW.exe." -ForegroundColor Gray
            return
        }
    }

    $sgwExe = Find-SgwExe $ClientPath

    if (-not $sgwExe) {
        throw "SGW.exe not found in: $ClientPath"
    }

    # Write LoginInternal.lua
    $luaDir = Join-Path $ClientPath "Working\SGWGame\Content\UI\Startup\Login"
    $luaFile = Join-Path $luaDir "LoginInternal.lua"

    $luaContent = @"
-- LoginInternal.lua - Generated by Cimmeria bootstrap
-- This overrides Login.lua's loadServerSystems() to point at the local server.
-- If this file is removed, the client falls back to the original (dead) CME servers.

LoginMod = {}

function LoginMod.loadServerSystems()
    LoginMod.servers = {}
    LoginMod.servers["$ServerName"] = "$ServerAddress"
end
"@

    if ($PSCmdlet.ShouldProcess($luaFile, "Write LoginInternal.lua")) {
        New-Item -ItemType Directory -Path $luaDir -Force | Out-Null
        Set-Content -Path $luaFile -Value $luaContent -Encoding UTF8 -NoNewline
        Write-Status "LoginInternal.lua written: $ServerName -> $ServerAddress" "Green"
    }

    # Binary patch: disable remote desktop check
    Patch-SgwRemoteDesktopCheck -SgwExe $sgwExe

    Write-Status "Client configured successfully." "Green"

    if ($Launch -or (-not $NoLaunch)) {
        if ($Atrea) {
            Start-SgwClientAtrea -SgwExe $sgwExe
        } else {
            Start-SgwClient -SgwExe $sgwExe
        }
    } else {
        Write-Host ""
        Write-Host "Client configured. To connect:" -ForegroundColor Green
        Write-Host "  1. Start the server: pwsh setup.ps1" -ForegroundColor White
        if ($Atrea) {
            Write-Host "  2. Launch via: pwsh patch-client.ps1 -Atrea" -ForegroundColor White
        } else {
            Write-Host "  2. Launch SGW.exe" -ForegroundColor White
        }
        Write-Host "  3. Login with: test / test" -ForegroundColor White
    }
}

function Find-SgwExe {
    param([string]$BasePath)

    # QA/development layout: Working\binaries\SGW.exe
    $candidate = Join-Path $BasePath "Working\binaries\SGW.exe"
    if (Test-Path $candidate) { return $candidate }

    # Standard install layout: SGW.exe at root
    $candidate = Join-Path $BasePath "SGW.exe"
    if (Test-Path $candidate) { return $candidate }

    return $null
}

function Patch-SgwRemoteDesktopCheck {
    <#
    .SYNOPSIS
        NOPs out the remote desktop check in SGW.exe.

    .DESCRIPTION
        SGW.exe calls GetSystemMetrics(SM_REMOTESESSION) during FEngineLoop::Init
        and refuses to launch if it detects a Remote Desktop session, showing
        "Error_RemoteDesktop". This patch changes the conditional JZ to an
        unconditional JMP so the error path is always skipped.

        Patch site (VA 0x00418a77 in the QA build):
          PUSH 0x1000              ; SM_REMOTESESSION
          CALL [GetSystemMetrics]
          TEST EAX,EAX
          JZ   +0x6C              ; <-- patch: change JZ (0x74) to JMP (0xEB)

        The patch is idempotent -- re-running on an already-patched binary is a no-op.
    #>
    param(
        [Parameter(Mandatory)]
        [string]$SgwExe
    )

    $bytes = [System.IO.File]::ReadAllBytes($SgwExe)

    # Search for: PUSH 0x1000 / CALL [IAT] / TEST EAX,EAX / JZ
    # Pattern:    68 00 10 00 00 / FF 15 xx xx xx xx / 85 C0 / 74
    # We match the fixed bytes and skip the 4-byte IAT address.
    $patternPrefix = [byte[]]@(0x68, 0x00, 0x10, 0x00, 0x00, 0xFF, 0x15)
    $patternSuffix = [byte[]]@(0x85, 0xC0)
    # Total: 7 (prefix) + 4 (IAT addr) + 2 (suffix) = 13 bytes, then byte 13 is JZ/JMP

    $patchOffset = -1
    for ($i = 0; $i -lt $bytes.Length - 14; $i++) {
        # Match prefix (push 0x1000 + call [indirect])
        $match = $true
        for ($j = 0; $j -lt $patternPrefix.Length; $j++) {
            if ($bytes[$i + $j] -ne $patternPrefix[$j]) {
                $match = $false
                break
            }
        }
        if (-not $match) { continue }

        # Skip 4 bytes of IAT address (indices 7-10), then match TEST EAX,EAX
        $suffixStart = $i + 7 + 4  # index 11
        if ($bytes[$suffixStart] -ne 0x85 -or $bytes[$suffixStart + 1] -ne 0xC0) {
            continue
        }

        # Byte at index 13 should be JZ (0x74) or already-patched JMP (0xEB)
        $jmpByte = $bytes[$suffixStart + 2]
        if ($jmpByte -eq 0x74 -or $jmpByte -eq 0xEB) {
            $patchOffset = $suffixStart + 2
            break
        }
    }

    if ($patchOffset -lt 0) {
        Write-Status "WARNING: Remote desktop check pattern not found in SGW.exe -- skipping patch." "Yellow"
        return
    }

    if ($bytes[$patchOffset] -eq 0xEB) {
        Write-Status "Remote desktop check already patched." "DarkGray"
        return
    }

    # Patch JZ -> JMP
    $bytes[$patchOffset] = 0xEB
    [System.IO.File]::WriteAllBytes($SgwExe, $bytes)
    Write-Status "Patched: remote desktop check disabled (JZ -> JMP at file offset 0x$($patchOffset.ToString('X')))." "Green"
}

function Start-SgwClient {
    param(
        [string]$SgwExe
    )

    $binDir = Split-Path $SgwExe -Parent

    Write-Host ""
    Write-Step "LAUNCHING GAME CLIENT"
    Write-Status "Starting SGW.exe..." "White"
    $proc = Start-Process -FilePath $SgwExe -WorkingDirectory $binDir -PassThru
    if ($proc) {
        Write-Status "SGW.exe launched (PID $($proc.Id))." "Green"
        Write-Host ""
        Write-Host "  Login with: test / test" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Status "WARNING: Failed to launch SGW.exe." "Yellow"
    }
}

function Start-SgwClientAtrea {
    <#
    .SYNOPSIS
        Launches SGW.exe via AtreaLoader with Mercury logging and PCAP capture.

    .DESCRIPTION
        AtreaLoader.exe injects AtreaRL.dll into the SGW process, enabling:
        - Mercury protocol message logging
        - Full network PCAP capture (sessions\*.pcap)
        - AES session key extraction (sessions\*-keys.txt)

        Output files are written to {binDir}\sessions\.
    #>
    param(
        [Parameter(Mandatory)]
        [string]$SgwExe
    )

    $binDir = Split-Path $SgwExe -Parent
    $atreaExe = Join-Path $binDir "AtreaLoader.exe"

    if (-not (Test-Path $atreaExe)) {
        Write-Host ""
        Write-Status "ERROR: AtreaLoader.exe not found in: $binDir" "Red"
        Write-Host ""
        Write-Host "  The Atrea Remote Loader must be placed alongside SGW.exe." -ForegroundColor Gray
        Write-Host "  Required files: AtreaLoader.exe, AtreaRL.dll, AtreaLoader.config" -ForegroundColor Gray
        return
    }

    # Strip ASLR from SGW.exe if needed (idempotent -- modifies PE header once).
    # Without this, AtreaLoader can't apply its patches and the sniffer won't work.
    Write-Status "Ensuring ASLR is disabled on SGW.exe..." "DarkGray"
    $fixProc = Start-Process -FilePath $atreaExe -ArgumentList "--fix-aslr" -WorkingDirectory $binDir -Wait -NoNewWindow -PassThru
    if ($fixProc.ExitCode -ne 0) {
        Write-Status "WARNING: --fix-aslr returned exit code $($fixProc.ExitCode)" "Yellow"
    }

    # Ensure sessions output directory exists
    $sessionsDir = Join-Path $binDir "sessions"
    New-Item -ItemType Directory -Path $sessionsDir -Force | Out-Null

    Write-Host ""
    Write-Step "LAUNCHING GAME CLIENT (ATREA)"
    Write-Status "Starting via AtreaLoader with Mercury logging + PCAP capture..." "White"

    $atreaArgs = "--enable-group=Mercury -SHOWLOG -LOG"
    $proc = Start-Process -FilePath $atreaExe -ArgumentList $atreaArgs -WorkingDirectory $binDir -PassThru
    if ($proc) {
        Write-Status "AtreaLoader launched (PID $($proc.Id))." "Green"
        Write-Host ""
        Write-Host "  Login with: test / test" -ForegroundColor White
        Write-Host "  PCAP + keys: $sessionsDir" -ForegroundColor Cyan
        Write-Host ""
    } else {
        Write-Status "WARNING: Failed to launch AtreaLoader.exe." "Yellow"
    }
}
