#!/usr/bin/env python3
"""Generate and validate the ability-tree seed from the owner's canonical workbook.

Reads sheet ``12_Trainer_Server_Export`` of the EMULATOR FINAL v2 workbook
(SHA-256 pinned below), validates it against the import-safety rules of the
FINAL v1 handoff (section 5) plus the campaign's own guards, and writes:

* ``docs/analysis/ability-trees/source/trainer_server_export.json``
  (committed review copy of sheet 12),
* ``db/resources/Archetypes/Seed/archetype_ability_tree.sql``,
* ``db/resources/Abilities/Seed/trainer_abilities.sql``
  (debug list 1 offers every node; rows of any other list are kept).

The generated SQL is committed, so CI never needs this script or openpyxl.

Usage (from the repo root):

    python tools/ability_trees/generate_seed.py            # regenerate
    python tools/ability_trees/generate_seed.py --check    # exit 1 on drift
    python tools/ability_trees/generate_seed.py --from-json [--check]
        # use the committed JSON instead of the workbook (stock Python only)

Exit codes: 0 ok, 1 drift (``--check``), 2 validation or input failure.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

WORKBOOK = Path(
    "docs/analysis/ability-trees/source/"
    "SGW_All_Classes_Progression_EMULATOR_FINAL_v2_LEVEL50.xlsx"
)
WORKBOOK_SHA256 = "ad9af21448794ca1eea2bae609016b5b55ad12f2bedec542c5f3b84cf1b21dba"
SHEET = "12_Trainer_Server_Export"

JSON_OUT = Path("docs/analysis/ability-trees/source/trainer_server_export.json")
TREE_SQL = Path("db/resources/Archetypes/Seed/archetype_ability_tree.sql")
TRAINER_SQL = Path("db/resources/Abilities/Seed/trainer_abilities.sql")

ABILITIES_SQL = Path("db/resources/Abilities/Seed/abilities.sql")
CHAR_CREATION_SQL = Path("db/resources/Archetypes/Seed/char_creation.sql")
STARTER_SQL = Path("db/resources/Archetypes/Seed/char_creation_abilities.sql")

COLUMNS = (
    "archetype",
    "branch",
    "node_order",
    "unlock_level",
    "required_branch_points",
    "skill_point_cost",
    "ability_id",
    "primary_prereq_ability_id",
    "additional_prereq_ability_ids",
    "is_branch_root",
    "is_capstone",
    "raw_training_cost",
    "project_status",
)
INT_COLUMNS = (
    "node_order",
    "unlock_level",
    "required_branch_points",
    "skill_point_cost",
    "ability_id",
    "primary_prereq_ability_id",
    "raw_training_cost",
)
BOOL_COLUMNS = ("is_branch_root", "is_capstone")

# Workbook archetype -> (EArchetype, branches in tree_index order).
# Free Jaffa / Shol'va maps to ARCHETYPE_Sholva only; ARCHETYPE_Jaffa gets
# no rows (decision D-AT04).
ARCHETYPES = (
    ("Soldier", "ARCHETYPE_Soldier", ("Automatic Weapons", "Heavy Weapons", "Command")),
    (
        "Commando",
        "ARCHETYPE_Commando",
        ("Demolitions", "Stealth / Infiltration", "Precision / Marksmanship"),
    ),
    ("Scientist", "ARCHETYPE_Scientist", ("Medical", "Support", "Robotics")),
    (
        "Archaeologist",
        "ARCHETYPE_Archeologist",
        ("Anthropology", "Sociology", "Archaeology"),
    ),
    (
        "Asgard",
        "ARCHETYPE_Asgard",
        ("Attack Programs", "Defensive Programs", "Scientific Programs"),
    ),
    ("Free Jaffa / Shol'va", "ARCHETYPE_Sholva", ("Heritage", "Tau'ri", "Tactics")),
    ("Goa'uld", "ARCHETYPE_Goauld", ("Ashrak", "Battle Lord", "Servant Lord")),
)
ARCHETYPE_ENUM = {label: enum for label, enum, _ in ARCHETYPES}
ARCHETYPE_ORDER = {label: i for i, (label, _, _) in enumerate(ARCHETYPES)}
TREE_INDEX = {
    (label, branch): i for label, _, branches in ARCHETYPES for i, branch in enumerate(branches)
}

ALLOWED_LEVELS = frozenset({1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50})
CAPSTONE_LEVEL = 50
MAX_NODES_PER_BRANCH = 30  # AbilityMod.MAX_BUTTONS (audit A-22)
TRAINER_DEBUG_LIST_ID = 1  # referenced by entity template 25 (D-AT06)

# Purchasable nodes that are also granted at character creation for the same
# archetype. Each entry is an accepted, documented exception.
ALLOWED_STARTER_COLLISIONS = {
    # D-AT09: universal starter Health Heal is also a Goa'uld Servant Lord
    # node. Left as-is until Goa'uld UAT is scheduled.
    ("ARCHETYPE_Goauld", 1646): "D-AT09",
}

# The pinned workbook's expected shape (handoff sections 1 and 11, audit A-10).
EXPECTED = {
    "nodes": 439,
    "unique_ids": 419,
    "branches": 21,
    "shared_ids": 19,
    "raw_cost_zero": 59,
    "above_level_20": 243,
    "per_archetype": {
        "Soldier": 72,
        "Commando": 64,
        "Scientist": 59,
        "Archaeologist": 65,
        "Asgard": 66,
        "Free Jaffa / Shol'va": 51,
        "Goa'uld": 62,
    },
}

GENERATED_NOTE = (
    "-- GENERATED by tools/ability_trees/generate_seed.py from sheet {sheet} of\n"
    "-- {workbook}\n"
    "-- (SHA-256 {sha}).\n"
    "-- Do not edit by hand: change the workbook and regenerate.\n"
)


class InputError(Exception):
    """Unreadable or mis-shaped input; reported and exit 2."""


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def normalize_row(raw: dict, where: str) -> dict:
    row = {}
    for col in COLUMNS:
        value = raw.get(col)
        if col in INT_COLUMNS:
            if value is None or value == "":
                value = 0
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise InputError(f"{where}: {col} is not an integer: {value!r}")
            if isinstance(value, float):
                if not value.is_integer():
                    raise InputError(f"{where}: {col} is not an integer: {value!r}")
                value = int(value)
        elif col in BOOL_COLUMNS:
            if not isinstance(value, bool):
                raise InputError(f"{where}: {col} is not a boolean: {value!r}")
        elif col == "additional_prereq_ability_ids":
            # A single id may arrive as a number rather than text.
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                value = str(int(value))
            value = "" if value is None else str(value).strip()
        else:
            if not isinstance(value, str) or not value.strip():
                raise InputError(f"{where}: {col} is empty or not text: {value!r}")
            value = value.strip()
        row[col] = value
    return row


def load_from_workbook() -> list[dict]:
    path = REPO_ROOT / WORKBOOK
    if not path.is_file():
        raise InputError(f"workbook not found: {WORKBOOK.as_posix()}")
    actual = sha256_of(path)
    if actual != WORKBOOK_SHA256:
        raise InputError(
            f"workbook SHA-256 mismatch: expected {WORKBOOK_SHA256}, got {actual}. "
            "The canonical workbook changed; re-pin it deliberately."
        )
    try:
        import openpyxl  # noqa: PLC0415 - optional dependency, workbook mode only
    except ImportError as exc:
        raise InputError(
            "openpyxl is required to read the workbook (pip install openpyxl), "
            "or use --from-json to regenerate from the committed export"
        ) from exc
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    if SHEET not in wb.sheetnames:
        raise InputError(f"sheet {SHEET} missing from the workbook")
    rows = list(wb[SHEET].iter_rows(values_only=True))
    wb.close()
    if not rows:
        raise InputError(f"sheet {SHEET} is empty")
    header = tuple(str(c).strip() if c is not None else "" for c in rows[0])
    extra = header[len(COLUMNS):]
    if header[: len(COLUMNS)] != COLUMNS or any(extra):
        raise InputError(f"sheet {SHEET} header is {header}, expected {COLUMNS}")
    out = []
    for n, values in enumerate(rows[1:], start=2):
        if all(v is None or v == "" for v in values):
            continue
        out.append(normalize_row(dict(zip(COLUMNS, values)), f"{SHEET} row {n}"))
    return out


def load_from_json() -> list[dict]:
    path = REPO_ROOT / JSON_OUT
    if not path.is_file():
        raise InputError(f"committed export not found: {JSON_OUT.as_posix()}")
    data = json.loads(path.read_text(encoding="utf-8"))
    src = data.get("source", {})
    if src.get("sha256") != WORKBOOK_SHA256 or src.get("sheet") != SHEET:
        raise InputError(
            f"{JSON_OUT.as_posix()} was exported from {src}, not the pinned workbook"
        )
    return [
        normalize_row(raw, f"{JSON_OUT.as_posix()} rows[{i}]")
        for i, raw in enumerate(data.get("rows", []))
    ]


# --------------------------------------------------------------------------
# Minimal parser for the repo's one-row-per-statement INSERT seeds
# --------------------------------------------------------------------------

INSERT_RE = re.compile(
    r"^INSERT INTO (?:\w+\.)?(\w+) \(([^)]*)\) VALUES \((.*)\);$", re.DOTALL
)


def split_values(text: str, where: str) -> list[str]:
    values, buf, i, in_str = [], [], 0, False
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == "'":
                if i + 1 < len(text) and text[i + 1] == "'":
                    buf.append("'")
                    i += 2
                    continue
                in_str = False
            else:
                buf.append(ch)
        elif ch == "'":
            in_str = True
        elif ch == ",":
            values.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
        i += 1
    if in_str:
        raise InputError(f"{where}: unterminated string literal")
    values.append("".join(buf).strip())
    return values


def split_statements(text: str) -> list[tuple[int, str]]:
    """Split SQL text on top-level ';', dropping '--' comments outside strings.

    Returns (starting line number, statement text) pairs. String literals may
    span lines (abilities.sql has multi-line descriptions).
    """
    out, buf, i, line, start, in_str = [], [], 0, 1, None, False
    while i < len(text):
        ch = text[i]
        if in_str:
            buf.append(ch)
            if ch == "'":
                if i + 1 < len(text) and text[i + 1] == "'":
                    buf.append("'")
                    i += 1
                else:
                    in_str = False
        elif ch == "-" and text.startswith("--", i):
            end = text.find("\n", i)
            i = len(text) if end < 0 else end
            continue
        elif ch == ";":
            stmt = "".join(buf).strip()
            if stmt:
                out.append((start or line, stmt))
            buf, start = [], None
        else:
            if ch == "'":
                in_str = True
            if start is None and not ch.isspace():
                start = line
            buf.append(ch)
        if ch == "\n":
            line += 1
        i += 1
    if in_str:
        raise InputError("unterminated string literal")
    if "".join(buf).strip():
        out.append((start or line, "".join(buf).strip()))
    return out


def parse_inserts(rel: Path, table: str) -> list[dict]:
    """Parse the INSERT rows for ``table``; any other INSERT is an error."""
    path = REPO_ROOT / rel
    if not path.is_file():
        raise InputError(f"seed not found: {rel.as_posix()}")
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    rows = []
    try:
        statements = split_statements(text)
    except InputError as exc:
        raise InputError(f"{rel.as_posix()}: {exc}") from exc
    for n, stmt in statements:
        if not stmt.startswith("INSERT INTO"):
            continue
        m = INSERT_RE.match(stmt + ";")
        if not m or m.group(1) != table:
            raise InputError(f"{rel.as_posix()}:{n}: unexpected statement: {stmt[:120]}")
        cols = [c.strip() for c in m.group(2).split(",")]
        vals = split_values(m.group(3), f"{rel.as_posix()}:{n}")
        if len(cols) != len(vals):
            raise InputError(f"{rel.as_posix()}:{n}: {len(cols)} columns, {len(vals)} values")
        rows.append(dict(zip(cols, vals)))
    return rows


def load_repo_context() -> tuple[set[int], dict[str, dict[int, list[int]]], list[dict]]:
    ability_ids = {int(r["ability_id"]) for r in parse_inserts(ABILITIES_SQL, "abilities")}

    def_archetype = {
        int(r["char_def_id"]): r["archetype"]
        for r in parse_inserts(CHAR_CREATION_SQL, "char_creation")
    }
    starters: dict[str, dict[int, list[int]]] = collections.defaultdict(
        lambda: collections.defaultdict(list)
    )
    for r in parse_inserts(STARTER_SQL, "char_creation_abilities"):
        char_def = int(r["char_def_id"])
        if char_def not in def_archetype:
            raise InputError(
                f"{STARTER_SQL.as_posix()}: char_def_id {char_def} has no char_creation row"
            )
        starters[def_archetype[char_def]][int(r["ability_id"])].append(char_def)

    trainer_rows = parse_inserts(TRAINER_SQL, "trainer_abilities")
    return ability_ids, starters, trainer_rows


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------


def prerequisites(row: dict) -> list[int]:
    ids = set()
    if row["primary_prereq_ability_id"]:
        ids.add(row["primary_prereq_ability_id"])
    for token in row["additional_prereq_ability_ids"].split(","):
        token = token.strip()
        if not token:
            continue
        if not token.isdigit():
            raise InputError(
                f"{row['archetype']} / {row['branch']} #{row['node_order']}: "
                f"bad additional prerequisite {token!r}"
            )
        ids.add(int(token))
    ids.discard(0)
    return sorted(ids)


def node_label(row: dict) -> str:
    return f"{row['archetype']} / {row['branch']} #{row['node_order']} (ability {row['ability_id']})"


def validate(
    rows: list[dict],
    ability_ids: set[int],
    starters: dict[str, dict[int, list[int]]],
) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    notes: list[str] = []

    # Archetype and branch mapping (handoff 5.3, D-AT04).
    for r in rows:
        if r["archetype"] not in ARCHETYPE_ENUM:
            errors.append(f"{node_label(r)}: unknown archetype {r['archetype']!r}")
        elif (r["archetype"], r["branch"]) not in TREE_INDEX:
            errors.append(f"{node_label(r)}: branch {r['branch']!r} is not in the tree_index map")
    if errors:
        return errors, notes

    branches: dict[tuple[str, str], list[dict]] = collections.defaultdict(list)
    for r in rows:
        branches[(r["archetype"], r["branch"])].append(r)

    # Workbook order must agree with the pinned tree_index map.
    seen_order: dict[str, list[str]] = collections.defaultdict(list)
    for r in rows:
        if r["branch"] not in seen_order[r["archetype"]]:
            seen_order[r["archetype"]].append(r["branch"])
    for label, _, expected in ARCHETYPES:
        got = tuple(seen_order.get(label, ()))
        if got != expected:
            errors.append(
                f"{label}: workbook branch order {got} differs from the tree_index map {expected}"
            )

    # Every id and prerequisite exists in resources.abilities (5.1, 4).
    for r in rows:
        if r["ability_id"] <= 0 or r["ability_id"] not in ability_ids:
            errors.append(f"{node_label(r)}: ability id missing from {ABILITIES_SQL.as_posix()}")
        for p in prerequisites(r):
            if p not in ability_ids:
                errors.append(
                    f"{node_label(r)}: prerequisite {p} missing from {ABILITIES_SQL.as_posix()}"
                )

    # (archetype, ability_id) is unique; shared ids span archetypes only.
    per_arch_ids = collections.Counter((r["archetype"], r["ability_id"]) for r in rows)
    for (arch, aid), n in sorted(per_arch_ids.items()):
        if n > 1:
            errors.append(f"{arch}: ability {aid} appears {n} times in one archetype")

    for (arch, branch), nodes in branches.items():
        where = f"{arch} / {branch}"
        nodes.sort(key=lambda r: r["node_order"])
        orders = [r["node_order"] for r in nodes]
        if orders != list(range(1, len(nodes) + 1)):
            errors.append(f"{where}: node orders are not unique and contiguous from 1: {orders}")
        if len(nodes) > MAX_NODES_PER_BRANCH:
            errors.append(
                f"{where}: {len(nodes)} nodes, the client draws at most {MAX_NODES_PER_BRANCH}"
            )
        roots = [r for r in nodes if r["is_branch_root"]]
        caps = [r for r in nodes if r["is_capstone"]]
        if len(roots) != 1:
            errors.append(f"{where}: {len(roots)} branch roots, expected exactly 1")
        else:
            root = roots[0]
            if root["node_order"] != 1 or prerequisites(root):
                errors.append(f"{node_label(root)}: root must be node 1 with no prerequisites")
        if len(caps) != 1:
            errors.append(f"{where}: {len(caps)} capstones, expected exactly 1")
        for c in caps:
            if c["unlock_level"] != CAPSTONE_LEVEL:
                errors.append(f"{node_label(c)}: capstone unlocks at {c['unlock_level']}, not 50")
            if c["is_branch_root"]:
                errors.append(f"{node_label(c)}: node is both root and capstone")

        in_branch = {r["ability_id"]: r for r in nodes}
        prev = None
        for r in nodes:
            if r["unlock_level"] not in ALLOWED_LEVELS:
                errors.append(f"{node_label(r)}: unlock level {r['unlock_level']} not allowed")
            if r["skill_point_cost"] < 0:
                errors.append(f"{node_label(r)}: negative skill_point_cost")
            if r["required_branch_points"] < 0:
                errors.append(f"{node_label(r)}: negative required_branch_points")
            if r["raw_training_cost"] < 0:
                errors.append(f"{node_label(r)}: negative raw_training_cost")
            # Tiers advance with node order; spend gates never fall (5.12).
            if prev is not None:
                if r["unlock_level"] < prev["unlock_level"]:
                    errors.append(f"{node_label(r)}: unlock level falls behind node {prev['node_order']}")
                if r["required_branch_points"] < prev["required_branch_points"]:
                    errors.append(
                        f"{node_label(r)}: required_branch_points falls behind node {prev['node_order']}"
                    )
                if (
                    r["unlock_level"] == prev["unlock_level"]
                    and r["required_branch_points"] != prev["required_branch_points"]
                ):
                    errors.append(f"{node_label(r)}: two spend gates inside one unlock tier")
            prev = r
            prereqs = prerequisites(r)
            if not r["is_branch_root"] and not prereqs:
                errors.append(f"{node_label(r)}: non-root node has no prerequisite")
            for p in prereqs:
                if p == r["ability_id"]:
                    errors.append(f"{node_label(r)}: requires itself (5.10)")
                    continue
                dep = in_branch.get(p)
                if dep is None:
                    errors.append(f"{node_label(r)}: prerequisite {p} is not a node of this branch")
                    continue
                # 5.9: a prerequisite must be reachable no later than its dependant.
                if dep["unlock_level"] > r["unlock_level"]:
                    errors.append(
                        f"{node_label(r)}: prerequisite {p} unlocks later ({dep['unlock_level']})"
                    )
                if dep["required_branch_points"] > r["required_branch_points"]:
                    errors.append(f"{node_label(r)}: prerequisite {p} has a higher spend gate")

        # 5.11: no cycle in the branch prerequisite graph.
        state: dict[int, int] = {}

        def visit(aid: int, stack: list[int], _in_branch=in_branch, _where=where) -> None:
            state[aid] = 1
            for p in prerequisites(_in_branch[aid]):
                if p not in _in_branch or p == aid:
                    continue
                if state.get(p) == 1:
                    cycle = stack[stack.index(p):] + [p] if p in stack else [aid, p]
                    errors.append(f"{_where}: prerequisite cycle {' -> '.join(map(str, cycle))}")
                elif state.get(p) is None:
                    visit(p, stack + [p])
            state[aid] = 2

        for aid in sorted(in_branch):
            if aid not in state:
                visit(aid, [aid])

    # Starter collisions (audit A-26, D-AT09).
    used_exceptions = set()
    for r in rows:
        enum = ARCHETYPE_ENUM[r["archetype"]]
        defs = starters.get(enum, {}).get(r["ability_id"])
        if not defs:
            continue
        key = (enum, r["ability_id"])
        if key in ALLOWED_STARTER_COLLISIONS:
            used_exceptions.add(key)
            notes.append(
                f"allowed starter collision ({ALLOWED_STARTER_COLLISIONS[key]}): {node_label(r)} "
                f"is granted at creation to char_def {sorted(set(defs))}"
            )
        else:
            errors.append(
                f"{node_label(r)}: purchasable node is granted at creation to {enum} "
                f"char_def {sorted(set(defs))}; a player could never buy it"
            )
    for key in sorted(set(ALLOWED_STARTER_COLLISIONS) - used_exceptions):
        notes.append(f"allowed starter collision {key} no longer occurs; drop it from the script")

    # Pinned shape of the canonical workbook.
    stats = summarize(rows)
    for key in ("nodes", "unique_ids", "branches", "shared_ids", "raw_cost_zero", "above_level_20"):
        if stats[key] != EXPECTED[key]:
            errors.append(f"{key} = {stats[key]}, expected {EXPECTED[key]}")
    if stats["per_archetype"] != EXPECTED["per_archetype"]:
        errors.append(
            f"per-archetype counts {stats['per_archetype']} != {EXPECTED['per_archetype']}"
        )
    for label, _, _ in ARCHETYPES:
        n = stats["branches_per_archetype"].get(label, 0)
        if n != 3:
            errors.append(f"{label}: {n} branches, expected exactly 3 (5.3)")

    return errors, notes


def summarize(rows: list[dict]) -> dict:
    per_arch = collections.Counter(r["archetype"] for r in rows)
    archs_per_id: dict[int, set[str]] = collections.defaultdict(set)
    for r in rows:
        archs_per_id[r["ability_id"]].add(r["archetype"])
    branch_keys = {(r["archetype"], r["branch"]) for r in rows}
    return {
        "nodes": len(rows),
        "unique_ids": len(archs_per_id),
        "branches": len(branch_keys),
        "shared_ids": sum(1 for s in archs_per_id.values() if len(s) > 1),
        "raw_cost_zero": sum(1 for r in rows if r["raw_training_cost"] == 0),
        "above_level_20": sum(1 for r in rows if r["unlock_level"] > 20),
        "per_archetype": {label: per_arch.get(label, 0) for label, _, _ in ARCHETYPES},
        "branches_per_archetype": collections.Counter(a for a, _ in branch_keys),
        "per_branch": {
            (label, b): sum(1 for r in rows if r["archetype"] == label and r["branch"] == b)
            for label, _, bs in ARCHETYPES
            for b in bs
        },
    }


# --------------------------------------------------------------------------
# Rendering (all text uses "\n"; line endings are applied on write)
# --------------------------------------------------------------------------


def sort_key(row: dict) -> tuple:
    return (
        ARCHETYPE_ORDER[row["archetype"]],
        TREE_INDEX[(row["archetype"], row["branch"])],
        row["node_order"],
    )


def sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def generated_note() -> str:
    return GENERATED_NOTE.format(sheet=SHEET, workbook=WORKBOOK.as_posix(), sha=WORKBOOK_SHA256)


def render_json(rows: list[dict]) -> str:
    doc = {
        "source": {
            "workbook": WORKBOOK.name,
            "sha256": WORKBOOK_SHA256,
            "sheet": SHEET,
            "generator": "tools/ability_trees/generate_seed.py",
        },
        "rows": [{col: r[col] for col in COLUMNS} for r in sorted(rows, key=sort_key)],
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def render_tree_sql(rows: list[dict]) -> str:
    out = [
        "--\n"
        "-- TOC entry 3170 (class 0 OID 62802)\n"
        "-- Dependencies: 187\n"
        "-- Data for Name: archetype_ability_tree; Type: TABLE DATA; Schema: resources; Owner: -\n"
        "--\n"
        + generated_note()
        + "-- ability_index = node_order; tree_index follows the workbook branch order.\n"
        "-- Free Jaffa / Shol'va maps to ARCHETYPE_Sholva only (D-AT04).\n"
        "--\n\n"
    ]
    for r in sorted(rows, key=sort_key):
        prereqs = "{" + ",".join(str(p) for p in prerequisites(r)) + "}"
        out.append(
            "INSERT INTO archetype_ability_tree (archetype, ability_index, ability_id, tree_index, "
            "level, prerequisite_abilities, required_branch_points, skill_point_cost, "
            "is_branch_root, is_capstone, branch_name, project_status) VALUES ("
            f"'{ARCHETYPE_ENUM[r['archetype']]}', {r['node_order']}, {r['ability_id']}, "
            f"{TREE_INDEX[(r['archetype'], r['branch'])]}, {r['unlock_level']}, '{prereqs}', "
            f"{r['required_branch_points']}, {r['skill_point_cost']}, "
            f"{'true' if r['is_branch_root'] else 'false'}, "
            f"{'true' if r['is_capstone'] else 'false'}, "
            f"{sql_text(r['branch'])}, {sql_text(r['project_status'])});\n\n"
        )
    return "".join(out)


def render_trainer_sql(rows: list[dict], existing: list[dict]) -> str:
    out = [
        "--\n"
        "-- TOC entry 3246 (class 0 OID 63139)\n"
        "-- Dependencies: 263\n"
        "-- Data for Name: trainer_abilities; Type: TABLE DATA; Schema: resources; Owner: -\n"
        "--\n"
        + generated_note()
        + f"-- List {TRAINER_DEBUG_LIST_ID} (debug list, entity template 25) offers every tree node of\n"
        "-- every seeded archetype. Rows of other lists are carried over unchanged.\n"
        "--\n\n"
    ]
    for r in sorted(rows, key=sort_key):
        out.append(
            "INSERT INTO trainer_abilities (list_id, archetype, ability_id) VALUES "
            f"({TRAINER_DEBUG_LIST_ID}, '{ARCHETYPE_ENUM[r['archetype']]}', {r['ability_id']});\n\n"
        )
    for e in existing:
        if int(e["list_id"]) == TRAINER_DEBUG_LIST_ID:
            continue
        out.append(
            "INSERT INTO trainer_abilities (list_id, archetype, ability_id) VALUES "
            f"({int(e['list_id'])}, {sql_text(e['archetype'])}, {int(e['ability_id'])});\n\n"
        )
    return "".join(out)


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------


def pick_eol(path: Path, mode: str) -> str:
    if mode == "lf":
        return "\n"
    if mode == "crlf":
        return "\r\n"
    if path.is_file():
        head = path.read_bytes()[:4096]
        if b"\n" in head:
            return "\r\n" if b"\r\n" in head else "\n"
    return "\r\n" if os.name == "nt" else "\n"


def print_summary(rows: list[dict], notes: list[str], preserved: int) -> None:
    s = summarize(rows)
    print("Ability-tree seed validation: OK")
    print(f"  workbook      {WORKBOOK.name}")
    print(f"  sha256        {WORKBOOK_SHA256}")
    print(f"  nodes         {s['nodes']}")
    print(f"  unique ids    {s['unique_ids']}")
    print(f"  branches      {s['branches']}")
    print(f"  shared ids    {s['shared_ids']}")
    print(f"  raw cost 0    {s['raw_cost_zero']}")
    print(f"  above lvl 20  {s['above_level_20']}")
    print("  per archetype:")
    for label, enum, branches in ARCHETYPES:
        sizes = ", ".join(f"{b} {s['per_branch'][(label, b)]}" for b in branches)
        print(f"    {label:<22} {enum:<24} {s['per_archetype'][label]:>3}  ({sizes})")
    print("    (ARCHETYPE_Jaffa             no rows, D-AT04)")
    print(f"  trainer list {TRAINER_DEBUG_LIST_ID} rows: {s['nodes']}; other-list rows kept: {preserved}")
    for note in notes:
        print(f"  note: {note}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="regenerate in memory and exit 1 on drift")
    ap.add_argument(
        "--from-json",
        action="store_true",
        help="read the committed JSON export instead of the workbook (no openpyxl needed)",
    )
    ap.add_argument(
        "--eol",
        choices=("auto", "lf", "crlf"),
        default="auto",
        help="line endings for written files (auto: keep each file's current style)",
    )
    args = ap.parse_args(argv)

    try:
        rows = load_from_json() if args.from_json else load_from_workbook()
        ability_ids, starters, trainer_rows = load_repo_context()
        errors, notes = validate(rows, ability_ids, starters)
    except InputError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if errors:
        print(f"Ability-tree seed validation FAILED ({len(errors)} problem(s)):", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 2

    outputs = {
        TREE_SQL: render_tree_sql(rows),
        TRAINER_SQL: render_trainer_sql(rows, trainer_rows),
    }
    if not args.from_json:
        outputs[JSON_OUT] = render_json(rows)
    preserved = sum(1 for e in trainer_rows if int(e["list_id"]) != TRAINER_DEBUG_LIST_ID)

    print_summary(rows, notes, preserved)

    if args.check:
        drift = []
        for rel, text in outputs.items():
            path = REPO_ROOT / rel
            current = path.read_bytes().decode("utf-8").replace("\r\n", "\n") if path.is_file() else None
            if current != text:
                drift.append(rel.as_posix())
        if drift:
            print("DRIFT: regenerate with tools/ability_trees/generate_seed.py:", file=sys.stderr)
            for d in drift:
                print(f"  - {d}", file=sys.stderr)
            return 1
        print("check: committed files match the generator")
        return 0

    for rel, text in outputs.items():
        path = REPO_ROOT / rel
        eol = pick_eol(path, args.eol)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.replace("\n", eol).encode("utf-8"))
        print(f"wrote {rel.as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
