//! Routes `OrgSquad*` `CellToBaseMsg` variants to `base::organization::handlers`.

use crate::base::organization::handlers::{
    handle_squad_accepted, handle_squad_loot_mode, handle_squad_member_left,
    handle_squad_minimap_ping,
};
use crate::cell::messages::CellToBaseMsg;

use super::DispatchCtx;

pub(super) async fn route(msg: CellToBaseMsg, ctx: &DispatchCtx<'_>) {
    match msg {
        CellToBaseMsg::OrgSquadSendInvite { .. } => {
            // OrgSquadSendInvite is currently generated by the base-method handler
            // (organizationInviteByType).  That handler is Phase 3 (base method
            // dispatch).  For Phase 2 the invite originates from the invite_response
            // accept path which produces OrgSquadAccepted directly.  No fanout needed
            // here beyond what the accept path already does.
            tracing::debug!(
                "OrgSquadSendInvite: no-op in Phase 2 (base method not yet implemented)"
            );
        }

        CellToBaseMsg::OrgSquadAccepted {
            org_id,
            new_member_entity_id,
            new_member_player_id,
            new_member_name,
            new_member_rank,
            existing_member_entity_ids,
            roster,
        } => {
            handle_squad_accepted(
                org_id,
                new_member_entity_id,
                new_member_player_id,
                new_member_name,
                new_member_rank,
                existing_member_entity_ids,
                roster,
                ctx.transport,
                ctx.connected,
                ctx.entity_to_addr,
            )
            .await;
        }

        CellToBaseMsg::OrgSquadMemberLeft {
            org_id,
            leaving_entity_id,
            leaving_player_id,
            leaving_name,
            reason,
            remaining_member_entity_ids,
        } => {
            handle_squad_member_left(
                org_id,
                leaving_entity_id,
                leaving_player_id,
                leaving_name,
                reason,
                remaining_member_entity_ids,
                ctx.transport,
                ctx.connected,
                ctx.entity_to_addr,
            )
            .await;
        }

        CellToBaseMsg::OrgSquadLootMode {
            org_id,
            loot_mode,
            member_entity_ids,
        } => {
            handle_squad_loot_mode(
                org_id,
                loot_mode,
                member_entity_ids,
                ctx.transport,
                ctx.connected,
                ctx.entity_to_addr,
            )
            .await;
        }

        CellToBaseMsg::OrgSquadMinimapPing {
            org_id,
            sender_entity_id,
            location,
            member_entity_ids,
        } => {
            handle_squad_minimap_ping(org_id, sender_entity_id, location, member_entity_ids).await;
        }

        // Exhaustiveness guard — all other variants handled by sibling dispatchers.
        _ => {
            tracing::warn!("organization_dispatch: unexpected variant — routing bug");
        }
    }
}
