"""Tests for ship.py (ship.sh), each in a throwaway repository with a bare origin and a fake
`gh`; nothing here touches a real PR or a real worktree.

    python -m unittest discover -s tools/build-lane -p "test_*.py"
"""

from __future__ import annotations

import contextlib
import io
import json
import re
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import ship  # noqa: E402
from test_lane_stats import find_bash  # noqa: E402
from test_rebase_pr import Repo, sh  # noqa: E402

TRAILERS = "Co-Authored-By: Bot <bot@example.invalid>\nClaude-Session: https://example.invalid/s/1"
FOOTER = "Generated by a test."

# A stand-in for `gh`: state lives in a JSON file, and every call is recorded in it.
FAKE_GH = r'''
import json, os, sys
path = os.environ["FAKE_GH_STATE"]
st = json.load(open(path))
sys.stdout.reconfigure(newline="\n")   # gh prints LF; a CR breaks `read` in bash
args = sys.argv[1:]
st["calls"].append(args)
def save(): json.dump(st, open(path, "w"))
def opt(name, default=None):
    return args[args.index(name) + 1] if name in args else default
prs = st["prs"]
out, code = "", 0
if args[:2] == ["pr", "list"]:
    head, state = opt("--head"), opt("--state", "open").upper()
    found = [p for p in prs.values() if p["headRefName"] == head and (state == "ALL" or p["state"] == state)]
    if "-q" in args:
        out = f'{found[0]["state"]} {found[0].get("headRefOid", "")}' if found else ""
    else:
        out = json.dumps([{"number": p["number"], "url": p["url"]} for p in found])
elif args[:2] == ["pr", "create"]:
    n = str(100 + len(prs))
    prs[n] = {"number": int(n), "url": f"https://example.invalid/pull/{n}", "state": "OPEN",
              "headRefName": opt("--head"), "title": opt("--title"), "body": open(opt("--body-file")).read(),
              "isDraft": "--draft" in args, "files": [], "mergeStateStatus": "CLEAN"}
    out = prs[n]["url"]
elif args[:2] == ["pr", "view"]:
    p = prs[args[2]]
    seq = p.get("mergeStateSeq")
    if seq and "mergeStateStatus" in opt("--json", ""):
        p["mergeStateStatus"] = seq.pop(0) if len(seq) > 1 else seq[0]
    out = json.dumps(p)
elif args[:2] == ["pr", "checks"]:
    seq = st["checks"]
    frame = seq.pop(0) if len(seq) > 1 else seq[0]
    if frame is None:
        out, code = "no checks reported", 1
    else:
        out = json.dumps([{"name": k, "bucket": v} for k, v in frame.items()])
elif args[:2] == ["pr", "merge"]:
    prs[args[2]].update(state="MERGED", mergedAt="2026-10-03T12:00:00Z")
else:
    out, code = "unexpected gh call", 2
save()
print(out)
sys.exit(code)
'''

GREEN = {g: "pass" for g in ship.GATING}
FIELD = re.compile(r'(\w+)=("[^"]*"|\S+)')


class ShipCase(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="test-ship-"))
        self.repo = Repo(self.tmp)
        (self.repo.main / "external").mkdir()
        (self.repo.main / "external" / "keep.txt").write_text("real external\n")
        self.repo.commit(self.repo.main, {".gitignore": ".claude/worktrees/\nexternal\n", "README.md": "# Demo\n", "src.rs": "fn a() {}\n"})
        self.repo.push_main()
        self.wt = self.repo.main / ".claude" / "worktrees" / "feat"
        sh("git", "worktree", "add", "-q", "-b", "feat", str(self.wt), "origin/main", cwd=self.repo.main)

        bindir = self.tmp / "bin"
        bindir.mkdir()
        (bindir / "fake_gh.py").write_text(FAKE_GH)
        gh = bindir / "gh"   # for rm-worktree.sh, which finds gh on PATH
        gh.write_text(f'#!/bin/sh\nexec "{Path(sys.executable).as_posix()}" "{(bindir / "fake_gh.py").as_posix()}" "$@"\n')
        psql = bindir / "psql"
        psql.write_text('#!/bin/sh\necho "$*" >> "$FAKE_PSQL_LOG"\n'
                        'case "$*" in *"SELECT datname"*) echo sgw_feat ;; esac\n')
        for f in (gh, psql):
            f.chmod(0o755)
        self.state = self.tmp / "gh.json"
        self.save_state({"calls": [], "prs": {}, "checks": [None]})
        self.troot = self.tmp / "targets"
        (self.troot / "feat").mkdir(parents=True)
        self.env = mock.patch.dict(os.environ, {
            "FAKE_GH_STATE": str(self.state), "FAKE_PSQL_LOG": str(self.tmp / "psql.log"),
            "SHIP_TRAILERS": TRAILERS, "SHIP_PR_FOOTER": FOOTER, "SHIP_POLL_SECONDS": "0",
            "PATH": str(bindir) + os.pathsep + os.environ["PATH"], "PSQL": psql.as_posix(),
            "CIMMERIA_TARGET_ROOT": self.troot.as_posix(), "LANE_ROOT": (self.tmp / "lane").as_posix(),
            "RM_WORKTREE_MIN_IDLE": "0"})
        self.env.start()
        self.patches = [mock.patch.object(ship, "GH", [sys.executable, str(bindir / "fake_gh.py")])]
        for p in self.patches:
            p.start()

    def tearDown(self):
        for p in self.patches:
            p.stop()
        self.env.stop()
        ext = self.wt / "external"
        if ext.is_symlink() or ext.exists():   # never let rmtree follow the link
            subprocess.run(["cmd", "/c", "rmdir", str(ext)] if os.name == "nt" else ["rm", "-f", str(ext)], capture_output=True)
        shutil.rmtree(self.tmp, ignore_errors=True)

    def save_state(self, st):
        self.state.write_text(json.dumps(st))

    def gh_state(self):
        return json.loads(self.state.read_text())

    def ship(self, *argv) -> tuple[int, dict, str]:
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            code = ship.main(list(argv))
        line = buf.getvalue().strip()
        self.assertNotIn("\n", line, "one line of output")
        fields = {k: v.strip('"') for k, v in FIELD.findall(line)}
        return code, fields, line

    def edit(self, name="new.rs", text="fn n() {}\n"):
        p = self.wt / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)

    def remote_head(self, branch="feat"):
        out = sh("git", "ls-remote", str(self.repo.origin), f"refs/heads/{branch}", cwd=self.tmp)
        return out.split()[0] if out else ""


class RefusalTests(ShipCase):
    def test_missing_worktree_is_refused(self):
        code, f, _ = self.ship("pr", "-C", str(self.tmp / "gone"), "-m", "x")
        self.assertEqual((code, f["status"]), (2, "refused"))
        self.assertIn("missing-worktree", f["reason"])

    def test_main_checkout_is_refused_even_on_a_feature_branch(self):
        sh("git", "checkout", "-q", "-b", "side", cwd=self.repo.main)
        (self.repo.main / "x.rs").write_text("x\n")
        code, f, _ = self.ship("pr", "-C", str(self.repo.main), "-m", "x")
        self.assertEqual(code, 2)
        self.assertIn("main-checkout", f["reason"])
        self.assertEqual(self.remote_head("side"), "")

    def test_main_branch_is_refused(self):
        other = self.repo.main / ".claude" / "worktrees" / "onmain"
        sh("git", "worktree", "add", "-q", "--detach", str(other), "origin/main", cwd=self.repo.main)
        code, f, _ = self.ship("pr", "-C", str(other), "-m", "x")
        self.assertEqual(code, 2)
        self.assertIn("detached-head", f["reason"])
        sh("git", "-C", str(other), "checkout", "-q", "-B", "master", cwd=self.tmp)
        code, f, _ = self.ship("pr", "-C", str(other), "-m", "x")
        self.assertEqual(code, 2)
        self.assertIn("protected-branch", f["reason"])

    def test_vanished_worktree_entry_is_refused_not_pushed_from_main(self):
        """The 2026-10-03 incident: the directory stays, git's entry for it is gone."""
        self.edit()
        shutil.rmtree(self.repo.main / ".git" / "worktrees" / "feat")
        code, f, _ = self.ship("pr", "-C", str(self.wt), "-m", "x")
        self.assertEqual(code, 2, f)
        self.assertEqual(self.remote_head(), "")

    def test_directory_inside_main_without_its_own_git_is_a_toplevel_mismatch(self):
        stray = self.repo.main / ".claude" / "worktrees" / "stray"
        stray.mkdir(parents=True)
        code, f, _ = self.ship("pr", "-C", str(stray), "-m", "x")
        self.assertEqual(code, 2)
        self.assertIn("toplevel-mismatch", f["reason"])


class PrTests(ShipCase):
    def test_commit_push_and_create_a_pr(self):
        self.edit()
        code, f, line = self.ship("pr", "-C", str(self.wt), "-m", "feat: add n\n\nWhy it matters.")
        self.assertEqual(code, 0, line)
        self.assertEqual((f["status"], f["branch"], f["pr"], f["kind"]), ("ok", "feat", "100", "code"))
        self.assertEqual(self.remote_head(), sh("git", "rev-parse", "HEAD", cwd=self.wt))
        msg = sh("git", "log", "-1", "--format=%B", cwd=self.wt)
        for t in TRAILERS.splitlines():
            self.assertEqual(msg.count(t), 1)
        pr = self.gh_state()["prs"]["100"]
        self.assertEqual(pr["title"], "feat: add n")
        self.assertIn("Why it matters.", pr["body"])
        self.assertTrue(pr["body"].rstrip().endswith(FOOTER))
        self.assertNotIn("Claude-Session", pr["body"])
        self.assertEqual(sh("git", "rev-parse", "--abbrev-ref", "feat@{upstream}", cwd=self.wt), "origin/feat")

    def test_trailers_already_in_the_message_are_not_duplicated(self):
        self.edit()
        code, _, line = self.ship("pr", "-C", str(self.wt), "-m", "fix: x\n\n" + TRAILERS)
        self.assertEqual(code, 0, line)
        msg = sh("git", "log", "-1", "--format=%B", cwd=self.wt)
        for t in TRAILERS.splitlines():
            self.assertEqual(msg.count(t), 1, msg)

    def test_existing_pr_is_reused_and_a_rerun_is_a_noop(self):
        self.edit()
        self.assertEqual(self.ship("pr", "-C", str(self.wt), "-m", "one")[0], 0)
        self.edit("two.rs")
        code, f, _ = self.ship("pr", "-C", str(self.wt), "-m", "two", "--title", "ignored")
        self.assertEqual((code, f["status"], f["pr"]), (0, "ok", "100"))
        creates = [c for c in self.gh_state()["calls"] if c[:2] == ["pr", "create"]]
        self.assertEqual(len(creates), 1)
        code, f, _ = self.ship("pr", "-C", str(self.wt), "-m", "three")
        self.assertEqual((code, f["status"], f["pr"]), (0, "noop", "100"))

    def test_nothing_on_the_branch_is_a_noop(self):
        code, f, _ = self.ship("pr", "-C", str(self.wt), "-m", "x")
        self.assertEqual((code, f["status"]), (0, "noop"))
        self.assertEqual(self.remote_head(), "")

    def test_paths_stage_only_those_files(self):
        self.edit("a.rs")
        self.edit("b.rs")
        code, _, line = self.ship("pr", "-C", str(self.wt), "-m", "a only", "--paths", "a.rs")
        self.assertEqual(code, 0, line)
        self.assertEqual(sh("git", "show", "--name-only", "--format=", "HEAD", cwd=self.wt), "a.rs")
        self.assertIn("b.rs", sh("git", "status", "--porcelain", cwd=self.wt))

    def test_kind_is_docs_for_markdown_and_agent_memory_only(self):
        self.edit("docs/guide.md", "# G\n")
        self.edit(".claude/agent-memory/main-session/note.md", "n\n")
        code, f, line = self.ship("pr", "-C", str(self.wt), "-m", "docs: g", "--draft")
        self.assertEqual((code, f["kind"]), (0, "docs"), line)
        self.assertTrue(self.gh_state()["prs"]["100"]["isDraft"])

    def test_diverged_origin_needs_force_with_lease(self):
        self.edit()
        self.assertEqual(self.ship("pr", "-C", str(self.wt), "-m", "one")[0], 0)
        sh("git", "commit", "-q", "--amend", "-m", "one, amended", cwd=self.wt)
        code, f, _ = self.ship("pr", "-C", str(self.wt), "-m", "unused")
        self.assertEqual((code, f["status"]), (4, "push-failed"))
        self.assertTrue(Path(f["log"]).exists(), "the log is kept on failure")
        code, f, _ = self.ship("pr", "-C", str(self.wt), "-m", "unused", "--force-with-lease")
        self.assertEqual(code, 0, f)
        self.assertEqual(self.remote_head(), sh("git", "rev-parse", "HEAD", cwd=self.wt))


class MergeCase(ShipCase):
    def add_pr(self, files, merge_state="CLEAN", checks=(None,), **extra):
        st = self.gh_state()
        head = sh("git", "rev-parse", "HEAD", cwd=self.wt)
        st["prs"]["7"] = {"number": 7, "url": "https://example.invalid/pull/7", "state": "OPEN", "isDraft": False,
                          "headRefName": "feat", "headRefOid": head, "files": [{"path": p} for p in files],
                          "mergeStateStatus": merge_state, **extra}
        st["checks"] = list(checks)
        self.save_state(st)

    def merge(self, *extra):
        return self.ship("merge", "7", "--repo", str(self.repo.main), *extra)

    def calls(self, prefix):
        return [c for c in self.gh_state()["calls"] if c[:2] == prefix]


class MergeTests(MergeCase):
    def test_docs_pr_merges_at_once_with_admin(self):
        self.add_pr(["docs/a.md", ".claude/agent-memory/x/y.json"])
        code, f, line = self.merge()
        self.assertEqual(code, 0, line)
        self.assertEqual((f["status"], f["kind"], f["retired"]), ("merged", "docs", "none"))
        self.assertEqual(f["merged_at"], "2026-10-03T12:00:00Z")
        self.assertEqual(self.calls(["pr", "merge"]), [["pr", "merge", "7", "--squash", "--admin"]])
        self.assertEqual(self.calls(["pr", "checks"]), [])

    def test_code_pr_waits_for_the_gating_checks(self):
        pending = {g: "pending" for g in ship.GATING}
        skipped = dict(GREEN, **{ship.GATING[2]: "skipping"}, **{"cargo llvm-cov (live DB)": "pending"})
        self.add_pr(["src.rs"], checks=[None, pending, skipped])
        code, f, line = self.merge()
        self.assertEqual((code, f["kind"]), (0, "code"), line)
        self.assertEqual(self.calls(["pr", "merge"]), [["pr", "merge", "7", "--squash"]])
        self.assertEqual(len(self.calls(["pr", "checks"])), 3, "no checks yet, pending, then green")

    def test_failed_check_stops_the_merge(self):
        self.add_pr(["src.rs"], checks=[dict(GREEN, **{"cargo clippy -D warnings": "fail"})])
        code, f, _ = self.merge()
        self.assertEqual((code, f["status"], f["checks"]), (1, "ci-failed", "cargo clippy -D warnings"))
        self.assertEqual(self.calls(["pr", "merge"]), [])

    def test_timeout_exits_3(self):
        self.add_pr(["src.rs"], checks=[{g: "pending" for g in ship.GATING}])
        code, f, _ = self.merge("--timeout", "0s")
        self.assertEqual((code, f["status"]), (3, "timeout"))
        self.assertEqual(self.calls(["pr", "merge"]), [])

    def test_behind_runs_the_rebase_first(self):
        self.add_pr(["src.rs"], checks=[GREEN], mergeStateSeq=["BEHIND", "CLEAN"])
        record = self.tmp / "rebase.args"
        fake = self.tmp / "fake_rebase.py"
        fake.write_text(f"import sys\nopen({str(record)!r}, 'w').write(' '.join(sys.argv[1:]))\n")
        with mock.patch.object(ship, "REBASE", [sys.executable, str(fake)]):
            code, _, line = self.merge()
        self.assertEqual(code, 0, line)
        self.assertTrue(record.read_text().endswith("--push 7"))

    def test_clean_pr_is_not_rebased(self):
        self.add_pr(["src.rs"], checks=[GREEN])
        with mock.patch.object(ship, "REBASE", [sys.executable, "-c", "raise SystemExit(9)"]):
            self.assertEqual(self.merge()[0], 0)

    def test_semantic_conflict_is_reported(self):
        self.add_pr(["src.rs"], merge_state="DIRTY")
        fake = [sys.executable, "-c", "print('status=conflict\\nsemantic=src.rs\\nstopped_at=abc'); raise SystemExit(1)"]
        with mock.patch.object(ship, "REBASE", fake):
            code, f, _ = self.merge()
        self.assertEqual((code, f["status"], f["semantic"]), (1, "conflict", "src.rs"))
        self.assertEqual(self.calls(["pr", "merge"]), [])

    def test_closed_and_draft_prs_are_refused(self):
        self.add_pr(["src.rs"], state="CLOSED")
        self.assertEqual(self.merge()[0], 2)
        self.add_pr(["src.rs"], isDraft=True)
        self.assertEqual(self.merge()[0], 2)


@unittest.skipUnless(find_bash(), "no bash")
class RetireTests(MergeCase):
    def setUp(self):
        super().setUp()
        ext = self.wt / "external"
        if os.name == "nt":
            sh("cmd", "/c", "mklink", "/J", str(ext), str(self.repo.main / "external"), cwd=self.tmp)
        else:
            ext.symlink_to(self.repo.main / "external", target_is_directory=True)
        self.edit()
        sh("git", "add", "-A", cwd=self.wt)
        sh("git", "commit", "-q", "-m", "work", cwd=self.wt)
        # Another worktree's entry whose recorded path this git cannot resolve: a prune
        # would delete it, which is how live entries vanished on 2026-10-03.
        stale = self.repo.main / ".git" / "worktrees" / "elsewhere"
        stale.mkdir(parents=True)
        (stale / "gitdir").write_text("/no/such/place/.git\n")
        (stale / "commondir").write_text("../..\n")
        (stale / "HEAD").write_text("ref: refs/heads/main\n")
        self.stale = stale
        self.add_pr(["src.rs"], checks=[GREEN])

    def test_retire_after_merge_without_prune(self):
        code, f, line = self.merge("--retire", "feat")
        self.assertEqual(code, 0, line)
        self.assertEqual(f["retired"], "feat")
        self.assertFalse(self.wt.exists())
        self.assertFalse((self.troot / "feat").exists(), "target dir deleted")
        self.assertEqual(sh("git", "branch", "--list", "feat", cwd=self.repo.main), "")
        self.assertEqual((self.repo.main / "external" / "keep.txt").read_text(), "real external\n")
        self.assertTrue(self.stale.exists(), "no git worktree prune")
        self.assertIn('DROP DATABASE "sgw_feat"', (self.tmp / "psql.log").read_text())

    def test_uncommitted_changes_refuse_before_merging(self):
        self.edit("dirty.rs")
        code, f, _ = self.merge("--retire", "feat")
        self.assertEqual(code, 2)
        self.assertIn("uncommitted", f["reason"])
        self.assertEqual(self.calls(["pr", "merge"]), [])
        self.assertTrue(self.wt.exists())

    def test_external_that_is_not_a_link_stops_the_retire(self):
        ext = self.wt / "external"
        subprocess.run(["cmd", "/c", "rmdir", str(ext)] if os.name == "nt" else ["rm", "-f", str(ext)], check=True)
        ext.mkdir()
        (ext / "real.txt").write_text("not a link\n")
        code, f, _ = self.merge("--retire", "feat")
        self.assertEqual((code, f["status"], f["retired"]), (5, "merged", "none"))
        self.assertTrue((ext / "real.txt").exists())
        self.assertTrue(self.wt.exists(), "git worktree remove never ran")
        self.assertEqual((self.repo.main / "external" / "keep.txt").read_text(), "real external\n")


@unittest.skipUnless(find_bash(), "no bash")
class WrapperTests(ShipCase):
    def test_wrapper_runs_the_script(self):
        env = dict(os.environ, PYTHON=sys.executable)
        p = subprocess.run([find_bash(), str(HERE / "ship.sh"), "pr", "-C", str(self.tmp / "gone"), "-m", "x"],
                           capture_output=True, text=True, env=env)
        self.assertEqual(p.returncode, 2, p.stderr)
        self.assertIn("status=refused", p.stdout)


if __name__ == "__main__":
    unittest.main()
