--
-- Crafting item effects: what using an item does to the player's crafting
-- state (crafting campaign, docs/analysis/crafting/).
--
-- A row with `blueprint_id` makes the item a Blueprint item: using it
-- teaches that blueprint. An item may teach more than one (one row each;
-- item 8882 teaches 367 and 369). A row with `racial_paradigm_id` makes the
-- item a Racial Paradigm Guide: using it raises that paradigm by 1, to at
-- most 10. Exactly one of the two is set. The item is consumed in the same
-- transaction that changes the crafting state; a use that would change
-- nothing is refused and consumes nothing.
--
-- No cooked-data field links a Blueprint item to its blueprint; the mapping
-- was recovered from the item and product names
-- (docs/reverse-engineering/findings/crafting-items.md). The seed is
-- GENERATED by tools/crafting/generate_item_effects.py from
-- docs/analysis/crafting/source/blueprint-items.csv; edit the CSV and rerun
-- the script, never the seed by hand.
--
-- Read by the item-use path
-- (crates/base-methods/src/base/world_entry/methods/inventory/core/use_crafting_item.rs).
--
-- Name: crafting_item_effects; Type: TABLE; Schema: resources; Owner: -
--

CREATE TABLE crafting_item_effects (
    item_id integer NOT NULL,
    blueprint_id integer,
    racial_paradigm_id integer,
    CONSTRAINT crafting_item_effects_one_effect CHECK ((blueprint_id IS NULL) <> (racial_paradigm_id IS NULL)),
    CONSTRAINT crafting_item_effects_blueprint_key UNIQUE (item_id, blueprint_id),
    CONSTRAINT crafting_item_effects_paradigm_key UNIQUE (item_id, racial_paradigm_id)
);
