//! Category 4 — known-answer ciphertext tests.
//!
//! Pins the byte-exact output of `MercuryEncryption::encrypt` against
//! reference vectors generated by an implementation independent of
//! both Crypto++ (the SGW.exe C++ stack) and RustCrypto (our Rust
//! stack). The vectors live in [`super::kat_vectors`] with full
//! generator provenance.
//!
//! **Why this catches what the other category-4 tests miss:** the
//! sibling `encryption::multi_bundle_encryption_round_trips_each_payload`
//! test asserts our encrypt → decrypt cycle is self-consistent
//! (`decrypt(encrypt(x)) == x`). That cannot catch an algorithm
//! parameter change where both directions drift in sync — e.g., if a
//! refactor accidentally swapped PKCS7 for ANSI X.923 padding, the
//! round-trip would still pass. The KAT compares against a frozen
//! reference, so any parameter drift fails.
//!
//! **What this pins** (each is a real failure mode if it ever drifts):
//!
//! 1. Padding scheme = PKCS7 (not zero, not ANSI X.923, not ISO/IEC
//!    7816-4).
//! 2. CBC IV = all zeros (per `EncryptionFilter::setKey`'s zero-IV
//!    policy — each session derives a fresh key during the handshake
//!    so IV reuse across packets is acceptable within a single
//!    session, but the **literal value** of the IV matters because
//!    the first cipher block XORs with it).
//! 3. HMAC key = AES key (the full 32-byte session key is passed to
//!    both `EVP_aes_256_cbc` and `EVP_md5`/`HMAC_Init` in the C++
//!    flow).
//! 4. Order = encrypt-then-MAC (HMAC computed over the ciphertext
//!    AFTER encryption, not over plaintext or padded plaintext).
//! 5. Output layout = `[ciphertext || hmac_md5_tag]`, tag length = 16
//!    (not `[tag || ciphertext]`, not a truncated tag).

use crate::encryption::MercuryEncryption;

use super::kat_vectors::{
    kat_long_plaintext, KAT_LONG_EXPECTED, KAT_LONG_KEY_BYTE, KAT_MID_EXPECTED, KAT_MID_KEY_BYTE,
    KAT_MID_PLAINTEXT, KAT_SHORT_EXPECTED, KAT_SHORT_KEY_BYTE, KAT_SHORT_PLAINTEXT,
};

#[test]
fn kat_short_one_aes_block_aligned() {
    let enc = MercuryEncryption::from_session_key([KAT_SHORT_KEY_BYTE; 32]);
    let got = enc.encrypt(KAT_SHORT_PLAINTEXT).expect("encrypt");
    assert_eq!(
        got.as_slice(),
        KAT_SHORT_EXPECTED,
        "16-byte (block-aligned) plaintext must produce the reference ciphertext+tag exactly",
    );
}

#[test]
fn kat_mid_crosses_block_boundary_with_partial_last_block() {
    let enc = MercuryEncryption::from_session_key([KAT_MID_KEY_BYTE; 32]);
    let got = enc.encrypt(KAT_MID_PLAINTEXT).expect("encrypt");
    assert_eq!(
        got.as_slice(),
        KAT_MID_EXPECTED,
        "257-byte plaintext (16 full blocks + 1 partial) must produce reference ciphertext+tag",
    );
}

#[test]
fn kat_long_bulk_encrypt_matches_reference() {
    let plaintext = kat_long_plaintext();
    let enc = MercuryEncryption::from_session_key([KAT_LONG_KEY_BYTE; 32]);
    let got = enc.encrypt(&plaintext).expect("encrypt");
    assert_eq!(
        got.as_slice(),
        KAT_LONG_EXPECTED,
        "1024-byte plaintext must produce reference ciphertext+tag (catches bulk-encrypt drift)",
    );
}

/// Round-trip the KAT: encrypt with our impl, then decrypt with our
/// impl, asserting we recover the original plaintext. The KAT test
/// alone proves we agree with the reference; this proves the
/// decrypt path is the inverse of the encrypt path for every sample.
#[test]
fn kat_decrypt_recovers_each_plaintext() {
    for (name, plaintext, key_byte) in [
        ("SHORT", KAT_SHORT_PLAINTEXT.to_vec(), KAT_SHORT_KEY_BYTE),
        ("MID", KAT_MID_PLAINTEXT.to_vec(), KAT_MID_KEY_BYTE),
        ("LONG", kat_long_plaintext(), KAT_LONG_KEY_BYTE),
    ] {
        let enc = MercuryEncryption::from_session_key([key_byte; 32]);
        let ct = enc.encrypt(&plaintext).expect("encrypt");
        let pt = enc.decrypt(&ct).expect("decrypt");
        assert_eq!(
            pt, plaintext,
            "{name}: decrypt(encrypt(plaintext)) must recover the original plaintext",
        );
    }
}
