//! Seed-shape guards for the FINAL v2 ability trees (AT-05b).
//!
//! `db/resources/Archetypes/Seed/archetype_ability_tree.sql` and
//! `db/resources/Abilities/Seed/trainer_abilities.sql` are generated by
//! `tools/ability_trees/generate_seed.py`, which validates the workbook
//! before writing. These tests pin what a fresh `db/database.sql` actually
//! loads, so a hand edit, a stale regeneration or a schema change that drops
//! rows fails here rather than in a trainer window.

use super::super::*;
use crate::test_support::require_db_or_skip;

/// Node counts per `EArchetype` position, from the v1 handoff section 11.
/// Any (0) and Jaffa (8) have no tree: the Free Jaffa / Shol'va tree maps to
/// `ARCHETYPE_Sholva` only (D-AT04).
const EXPECTED_NODES: [(i32, &str, usize); 9] = [
    (0, "Any", 0),
    (1, "Soldier", 72),
    (2, "Commando", 64),
    (3, "Scientist", 59),
    (4, "Archaeologist", 65),
    (5, "Asgard", 66),
    (6, "Goa'uld", 62),
    (7, "Sholva", 51),
    (8, "Jaffa", 0),
];

const TOTAL_NODES: usize = 439;
const MAX_LEVEL: i32 = 50;

#[tokio::test]
async fn seed_per_archetype_node_counts_match_final_v2() {
    let pool = require_db_or_skip!();
    let catalog = AbilityTreeCatalog::load(&pool).await.expect("catalog load");

    for (arch, name, expected) in EXPECTED_NODES {
        assert_eq!(
            catalog.tree(arch).len(),
            expected,
            "{name} (archetype {arch}) node count"
        );
    }
    assert_eq!(catalog.len(), TOTAL_NODES, "total seeded nodes");
    assert_eq!(catalog.archetype_count(), 7, "seven archetypes carry a tree");
}

/// Every seeded archetype has three branches, and each branch has exactly
/// one root (node 1, no prerequisites) and exactly one capstone that unlocks
/// at the level cap.
#[tokio::test]
async fn seed_every_branch_has_one_root_and_one_level_50_capstone() {
    let pool = require_db_or_skip!();
    let catalog = AbilityTreeCatalog::load(&pool).await.expect("catalog load");

    let mut branches = 0;
    for (arch, name, expected) in EXPECTED_NODES {
        if expected == 0 {
            continue;
        }
        for tree_index in 0..=2 {
            let branch: Vec<&TreeNode> = catalog
                .tree(arch)
                .iter()
                .filter(|n| n.tree_index == tree_index)
                .collect();
            assert!(!branch.is_empty(), "{name} branch {tree_index} is empty");
            branches += 1;

            let roots: Vec<_> = branch.iter().filter(|n| n.is_branch_root).collect();
            assert_eq!(roots.len(), 1, "{name} branch {tree_index}: one root");
            assert_eq!(
                (roots[0].node_order, roots[0].prerequisites.as_slice()),
                (1, &[][..]),
                "{name} branch {tree_index}: the root is node 1 with no prerequisites"
            );

            let capstones: Vec<_> = branch.iter().filter(|n| n.is_capstone).collect();
            assert_eq!(capstones.len(), 1, "{name} branch {tree_index}: one capstone");
            assert_eq!(
                capstones[0].level, MAX_LEVEL,
                "{name} branch {tree_index}: capstone {} unlocks at the level cap",
                capstones[0].ability_id
            );
        }
        assert!(
            catalog.tree(arch).iter().all(|n| (0..=2).contains(&n.tree_index)),
            "{name}: every node sits in branch 0..=2"
        );
    }
    assert_eq!(branches, 21, "7 archetypes x 3 branches");
}

/// Every prerequisite names a node of the same archetype and branch, so a
/// prerequisite can always be trained before the node that needs it.
#[tokio::test]
async fn seed_prerequisites_are_nodes_of_the_same_branch() {
    let pool = require_db_or_skip!();
    let catalog = AbilityTreeCatalog::load(&pool).await.expect("catalog load");

    for (arch, name, _) in EXPECTED_NODES {
        for node in catalog.tree(arch) {
            for &prereq in &node.prerequisites {
                let parent = catalog.node(arch, prereq).unwrap_or_else(|| {
                    panic!(
                        "{name} ability {}: prerequisite {prereq} is not in the tree",
                        node.ability_id
                    )
                });
                assert_eq!(
                    parent.tree_index, node.tree_index,
                    "{name} ability {}: prerequisite {prereq} is in another branch",
                    node.ability_id
                );
            }
        }
    }
}

/// The trainer list and the tree agree in both directions: every
/// `trainer_abilities` row names a node of its archetype's tree (the cell
/// drops unmatched rows with a WARN), and debug list 1 offers every node
/// (D-AT06).
#[tokio::test]
async fn seed_trainer_rows_and_tree_rows_match() {
    let pool = require_db_or_skip!();

    let trainer_rows: i64 = sqlx::query_scalar("SELECT count(*) FROM resources.trainer_abilities")
        .fetch_one(&pool)
        .await
        .unwrap();
    assert!(trainer_rows > 0, "seed must provide trainer rows");

    let orphan_trainer_rows: Vec<(i32, String, i32)> = sqlx::query_as(
        "SELECT ta.list_id, ta.archetype::text, ta.ability_id \
         FROM resources.trainer_abilities ta \
         LEFT JOIN resources.archetype_ability_tree t \
           ON t.archetype = ta.archetype AND t.ability_id = ta.ability_id \
         WHERE t.ability_id IS NULL \
         ORDER BY 1, 2, 3",
    )
    .fetch_all(&pool)
    .await
    .unwrap();
    assert!(
        orphan_trainer_rows.is_empty(),
        "trainer rows without a tree node: {orphan_trainer_rows:?}"
    );

    let nodes_not_offered: Vec<(String, i32)> = sqlx::query_as(
        "SELECT t.archetype::text, t.ability_id \
         FROM resources.archetype_ability_tree t \
         LEFT JOIN resources.trainer_abilities ta \
           ON ta.list_id = 1 AND ta.archetype = t.archetype AND ta.ability_id = t.ability_id \
         WHERE ta.ability_id IS NULL \
         ORDER BY 1, 2",
    )
    .fetch_all(&pool)
    .await
    .unwrap();
    assert!(
        nodes_not_offered.is_empty(),
        "tree nodes debug list 1 does not offer: {nodes_not_offered:?}"
    );
}

/// Every tree row names an existing ability. The foreign key enforces this
/// today; the explicit check keeps the guarantee if the constraint is ever
/// dropped, because `AbilityTreeCatalog::load` inner-joins `abilities` and
/// would silently lose the row.
#[tokio::test]
async fn seed_every_tree_row_has_an_ability() {
    let pool = require_db_or_skip!();

    let missing: Vec<(String, i32)> = sqlx::query_as(
        "SELECT t.archetype::text, t.ability_id \
         FROM resources.archetype_ability_tree t \
         LEFT JOIN resources.abilities a ON a.ability_id = t.ability_id \
         WHERE a.ability_id IS NULL \
         ORDER BY 1, 2",
    )
    .fetch_all(&pool)
    .await
    .unwrap();
    assert!(missing.is_empty(), "tree rows without an ability: {missing:?}");

    let rows: i64 = sqlx::query_scalar("SELECT count(*) FROM resources.archetype_ability_tree")
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(rows as usize, TOTAL_NODES, "table row count");
}
