# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import EffectScript

class RangedPhysicalDamage(EffectScript):
	def onPulseBegin(self):
		self.n4_trigger_In()

	n3_var_Value = None
	def n4_trigger_In(self):
		result = self.effect.qrCombatDamage(8, 14, (self.n4_var_Base_Damage or 0), True, True)
		self.n4_var_Remaining_Dmg_Percent = result['remaining'] * 100 / result['total']
		self.n6_var_A = self.n4_var_Remaining_Dmg_Percent
		self.n9_var_A = self.n4_var_Remaining_Dmg_Percent
		if self.n6_var_A > self.n6_var_B:
			self.n9_var_Output = self.n9_var_A * self.n9_var_B
			self.n10_var_A = self.n9_var_Output
			self.n10_trigger_In()

	n4_var_Remaining_Dmg_Percent = None
	n4_var_Base_Damage = None
	n5_var_Value = None
	n6_var_A = None
	n6_var_B = None
	n7_var_Set = None
	n7_var_Value = None
	n8_var_Base_Damage = None
	n9_var_A = None
	n9_var_B = None
	n9_var_Output = None
	def n10_trigger_In(self):
		self.n10_var_Output = self.n10_var_A / self.n10_var_B
		self.n12_var_A = self.n10_var_Output
		self.n12_var_Output = self.n12_var_A + self.n12_var_B
		self.n8_var_Base_Damage = self.n12_var_Output
		result = self.effect.qrCombatDamage(7, 14, (self.n8_var_Base_Damage or 0), True, True)

	n10_var_A = None
	n10_var_B = None
	n10_var_Output = None
	n11_var_Set = None
	n11_var_Value = None
	n12_var_A = None
	n12_var_B = None
	n12_var_Output = None
	def __init__(self, owner, effect, nvps):
		EffectScript.__init__(self, owner, effect, nvps)
		self.n3_var_Value = int(self.params.get('HealthDamage'))
		self.n12_var_B = self.n3_var_Value
		self.n5_var_Value = int(self.params.get('FocusDamage'))
		self.n4_var_Base_Damage = self.n5_var_Value
		self.n9_var_B = self.n5_var_Value
		self.n7_var_Value = 0
		self.n6_var_B = self.n7_var_Value
		self.n11_var_Value = 300
		self.n10_var_B = self.n11_var_Value

