# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import EffectScript

class RangedEnergyDamage(EffectScript):
	def onPulseBegin(self):
		self.effect.qrCombatDamage(7, 15, (self.n2_var_Base_Damage or 0), True, True)
		self.effect.qrCombatDamage(8, 15, (self.n4_var_Base_Damage or 0), True, True)

	n2_var_Base_Damage = None
	n3_var_Value = None
	n4_var_Base_Damage = None
	n5_var_Value = None
	def __init__(self, owner, effect, nvps):
		EffectScript.__init__(self, owner, effect, nvps)
		self.n3_var_Value = int(self.params.get('HealthDamage'))
		self.n2_var_Base_Damage = self.n3_var_Value
		self.n5_var_Value = int(self.params.get('FocusDamage'))
		self.n4_var_Base_Damage = self.n5_var_Value

