# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import EffectScript
from common import Constants
from common.defs.Def import DefMgr
import Atrea
import Atrea.enums

class TestEffect(EffectScript):
	def onPulseEnd(self):
		self.n15_propagator_Pulse_End()

	def n15_propagator_Pulse_End(self):
		if True:
			self.n51_var_Player.missions.abandon(1627)
			self.n54_trigger_In()
		if True:
			self.n92_trigger_In()
		if True:
			self.n120_trigger_In()
			self.n134_trigger_In()
			self.n143_trigger_In()
		if True:
			self.n149_trigger_In()
		if True:
			self.n41_trigger_In()

	def n41_trigger_In(self):
		self.n41_var_Output = self.n41_var_A + self.n41_var_B
		self.n44_var_A = self.n41_var_Output
		self.n44_var_Output = self.n44_var_A - self.n44_var_B
		self.n46_var_A = self.n44_var_Output
		self.n46_trigger_In()

	n41_var_A = None
	n41_var_B = None
	n41_var_Output = None
	n42_var_Set = None
	n42_var_Value = None
	n43_var_Set = None
	n43_var_Value = None
	n44_var_A = None
	n44_var_B = None
	n44_var_Output = None
	n45_var_Set = None
	n45_var_Value = None
	def n46_trigger_In(self):
		self.n46_var_Output = self.n46_var_A * self.n46_var_B
		self.n47_var_A = self.n46_var_Output
		self.n47_var_Output = self.n47_var_A / self.n47_var_B
		self.n48_var_A = self.n47_var_Output
		if self.n48_var_A != self.n48_var_B:
			self.owner.debug('Integer math test FAILED')

	n46_var_A = None
	n46_var_B = None
	n46_var_Output = None
	n47_var_A = None
	n47_var_B = None
	n47_var_Output = None
	n48_var_A = None
	n48_var_B = None
	n51_var_Player = None
	n53_var_Player = None
	def n54_trigger_In(self):
		status = self.n54_var_Player.missions.getMissionStatus(1627)
		if status == Constants.MISSION_Not_Active:
			self.n53_var_Player.missions.accept(1627)
			self.n57_trigger_In()
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission abandon test FAILED')
		if status == Constants.MISSION_Failed:
			self.n53_var_Player.missions.accept(1627)
			self.n57_trigger_In()
		if status == Constants.MISSION_Completed:
			self.n53_var_Player.missions.accept(1627)
			self.n57_trigger_In()

	n54_var_Player = None
	n55_var_Player = None
	def n55_propagator_Player(self):
		self.n51_var_Player = self.n55_var_Player
		self.n54_var_Player = self.n55_var_Player
		self.n53_var_Player = self.n55_var_Player
		self.n57_var_Player = self.n55_var_Player
		self.n58_var_Player = self.n55_var_Player
		self.n61_var_Player = self.n55_var_Player
		self.n69_var_Player = self.n55_var_Player
		self.n68_var_Player = self.n55_var_Player
		self.n71_var_Player = self.n55_var_Player
		self.n72_var_Player = self.n55_var_Player
		self.n74_var_Player = self.n55_var_Player
		self.n76_var_Player = self.n55_var_Player
		self.n80_var_Player = self.n55_var_Player
		self.n81_var_Player = self.n55_var_Player
		self.n84_var_Player = self.n55_var_Player
		self.n85_var_Player = self.n55_var_Player
		self.n87_var_Player = self.n55_var_Player
		self.n89_var_Player = self.n55_var_Player

	def n57_trigger_In(self):
		status = self.n57_var_Player.missions.getMissionStatus(1627)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission assign test FAILED')
		if status == Constants.MISSION_Active:
			self.n58_trigger_In()
		if status == Constants.MISSION_Failed:
			self.owner.debug('Mission assign test FAILED')
		if status == Constants.MISSION_Completed:
			self.owner.debug('Mission assign test FAILED')

	n57_var_Player = None
	def n58_trigger_In(self):
		status = self.n58_var_Player.missions.getStepStatus(1627, 4839)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission assign step test FAILED')
		if status == Constants.MISSION_Active:
			self.n61_trigger_In()
		if status == Constants.MISSION_Completed:
			self.owner.debug('Mission assign step test FAILED')

	n58_var_Player = None
	def n61_trigger_In(self):
		status = self.n61_var_Player.missions.getObjectiveStatus(1627, 5540)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission assign objective test FAILED')
		if status == Constants.MISSION_Active:
			if True:
				self.n68_var_Player.missions.completeObjective(1627, 5540)
				self.n69_trigger_In()
		if status == Constants.MISSION_Completed:
			self.owner.debug('Mission assign objective test FAILED')
		if status == Constants.MISSION_Failed:
			self.owner.debug('Mission assign objective test FAILED')

	n61_var_Player = None
	n68_var_Player = None
	def n69_trigger_In(self):
		status = self.n69_var_Player.missions.getObjectiveStatus(1627, 5540)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission complete objective test FAILED')
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission complete objective test FAILED')
		if status == Constants.MISSION_Completed:
			self.n71_var_Player.missions.advance(1627, 4834)
			self.n72_trigger_In()
		if status == Constants.MISSION_Failed:
			self.owner.debug('Mission complete objective test FAILED')

	n69_var_Player = None
	n71_var_Player = None
	def n72_trigger_In(self):
		status = self.n72_var_Player.missions.getObjectiveStatus(1627, 5548)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission complete step objective test FAILED')
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission complete step objective test FAILED')
		if status == Constants.MISSION_Completed:
			self.n74_trigger_In()
		if status == Constants.MISSION_Failed:
			self.owner.debug('Mission complete step objective test FAILED')

	n72_var_Player = None
	def n74_trigger_In(self):
		status = self.n74_var_Player.missions.getStepStatus(1627, 4839)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission complete step test FAILED')
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission complete step test FAILED')
		if status == Constants.MISSION_Completed:
			self.n76_trigger_In()

	n74_var_Player = None
	def n76_trigger_In(self):
		status = self.n76_var_Player.missions.getStepStatus(1627, 4834)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission advance step test FAILED')
		if status == Constants.MISSION_Active:
			if True:
				self.n80_var_Player.missions.failObjective(1627, 5541)
				self.n81_trigger_In()
		if status == Constants.MISSION_Completed:
			self.owner.debug('Mission advance step test FAILED')

	n76_var_Player = None
	n80_var_Player = None
	def n81_trigger_In(self):
		status = self.n81_var_Player.missions.getObjectiveStatus(1627, 5541)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission fail objective test FAILED')
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission fail objective test FAILED')
		if status == Constants.MISSION_Completed:
			self.owner.debug('Mission fail objective test FAILED')
		if status == Constants.MISSION_Failed:
			self.n84_var_Player.missions.complete(1627)
			self.n85_trigger_In()

	n81_var_Player = None
	n84_var_Player = None
	def n85_trigger_In(self):
		status = self.n85_var_Player.missions.getStepStatus(1627, 4835)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission complete-all step test FAILED')
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission complete-all step test FAILED')
		if status == Constants.MISSION_Completed:
			self.n87_trigger_In()

	n85_var_Player = None
	def n87_trigger_In(self):
		status = self.n87_var_Player.missions.getObjectiveStatus(1627, 5550)
		if status == Constants.MISSION_Not_Active:
			self.owner.debug('Mission complete-all objective test FAILED')
		if status == Constants.MISSION_Active:
			self.owner.debug('Mission complete-all objective test FAILED')
		if status == Constants.MISSION_Completed:
			status = self.n89_var_Player.missions.getMissionStatus(1627)
		if status == Constants.MISSION_Failed:
			self.owner.debug('Mission complete-all objective test FAILED')

	n87_var_Player = None
	n89_var_Player = None
	def n91_trigger_In(self):
		tpl = DefMgr.get('template', 15)
		if tpl and self.n91_var_Location:
			entity = self.owner.space.createEntity(tpl, self.n91_var_Location)
			self.n91_var_Entity = entity
			self.n104_var_Set = self.n91_var_Entity
			self.n104_var_Value = self.n104_var_Set
			self.n104_propagator_Value()
			self.n95_trigger_In()
		else:
			self.owner.debug('Entity spawn test FAILED')

	n91_var_Entity = None
	n91_var_Location = None
	def n92_trigger_In(self):
		entity = self.n92_var_Entity
		if entity is not None:
			self.n92_var_Position = entity.position
			self.n91_var_Location = self.n92_var_Position
		self.n91_trigger_In()

	n92_var_Entity = None
	n92_var_Position = None
	def n95_trigger_In(self):
		if self.n95_var_Entity and 'BS_HumanMale.BS_HM_Head_01':
			self.n95_var_Entity.removeBodyComponent('BS_HumanMale.BS_HM_Head_01')
			self.n96_trigger_In()
		else:
			self.owner.debug('Entity body component update FAILED!')

	n95_var_Entity = None
	def n96_trigger_In(self):
		if self.n96_var_Entity and 'NPC_Human.NPC_HM_Nerus_Head00':
			self.n96_var_Entity.addBodyComponent('NPC_Human.NPC_HM_Nerus_Head00')
			self.n98_trigger_In()
		else:
			self.owner.debug('Entity body component update FAILED!')

	n96_var_Entity = None
	def n98_trigger_In(self):
		ent = self.n98_var_Entity
		if ent is None:
			self.owner.debug('Entity property update FAILED!')
			return
		if self.n98_var_Name is not None:
			ent.setName(self.n98_var_Name)
		self.n103_trigger_In()

	n98_var_Entity = None
	n98_var_Name = None
	n100_var_Set = None
	n100_var_Value = None
	def n102_trigger_In(self):
		if self.n102_var_Entity:
			self.n102_var_Entity.getStat(Atrea.enums.health).setCurrent(0)
			self.n106_trigger_In()
		else:
			self.owner.debug('Entity timed kill FAILED!')

	n102_var_Entity = None
	def n103_trigger_In(self):
		entity = self.n103_var_Entity
		if entity is None:
			self.owner.debug('Entity property get FAILED!')
		if entity is not None:
			self.n103_var_Name = entity.beingName
			self.n105_var_B = self.n103_var_Name
			if self.n105_var_A == self.n105_var_B:
				self.n112_trigger_In()
			if self.n105_var_A != self.n105_var_B:
				self.owner.debug('Entity property name cmp FAILED!')

	n103_var_Entity = None
	n103_var_Name = None
	n104_var_Set = None
	n104_var_Value = None
	def n104_propagator_Value(self):
		self.n103_var_Entity = self.n104_var_Value
		self.n95_var_Entity = self.n104_var_Value
		self.n96_var_Entity = self.n104_var_Value
		self.n98_var_Entity = self.n104_var_Value
		self.n102_var_Entity = self.n104_var_Value
		self.n110_var_Entity = self.n104_var_Value
		self.n112_var_Target = self.n104_var_Value
		self.n106_var_Entity = self.n104_var_Value

	n105_var_A = None
	n105_var_B = None
	def n106_trigger_In(self):
		if self.n106_var_Entity:
			stat = self.n106_var_Entity.getStat(7)
			self.n106_var_Current = stat.cur
			self.n107_var_A = self.n106_var_Current
			self.n107_trigger_In()
		else:
			self.owner.debug('Entity health check FAILED!')

	n106_var_Entity = None
	n106_var_Current = None
	def n107_trigger_In(self):
		if self.n107_var_A == self.n107_var_B:
			# TODO: CancelTimer, avoid multiple In() calls and multiple parallel timers?
			def timerCb():
				self.n110_trigger_In()
			Atrea.addTimer(Atrea.getGameTime() + 5, timerCb)
		if self.n107_var_A != self.n107_var_B:
			self.owner.debug('Entity health check FAILED!')

	n107_var_A = None
	n107_var_B = None
	n108_var_Set = None
	n108_var_Value = None
	def n110_trigger_In(self):
		if self.n110_var_Entity is not None:
			if Atrea.destroyCellEntity(self.n110_var_Entity.entityId):
				pass
			else:
				self.owner.debug('Entity timed despawn FAILED!')
		else:
			self.owner.debug('Entity timed despawn FAILED!')

	n110_var_Entity = None
	def n112_trigger_In(self):
		pos = self.n112_var_Entity.position
		tpos = self.n112_var_Target.position
		dv = Atrea.Vector3(pos.x - tpos.x, pos.y - tpos.y, pos.z - tpos.z)
		self.n112_var_Distance = dv.length()
		self.n114_var_A = self.n112_var_Distance
		self.n114_trigger_In()

	n112_var_Distance = None
	n112_var_Entity = None
	n112_var_Target = None
	n113_var_Player = None
	def n114_trigger_In(self):
		if self.n114_var_A == self.n114_var_B:
			# TODO: CancelTimer, avoid multiple In() calls and multiple parallel timers?
			def timerCb():
				self.n102_trigger_In()
			Atrea.addTimer(Atrea.getGameTime() + 5, timerCb)
		if self.n114_var_A < self.n114_var_B:
			# TODO: CancelTimer, avoid multiple In() calls and multiple parallel timers?
			def timerCb():
				self.n102_trigger_In()
			Atrea.addTimer(Atrea.getGameTime() + 5, timerCb)
		if self.n114_var_A > self.n114_var_B:
			self.owner.debug('Spawned distance check FAILED')

	n114_var_A = None
	n114_var_B = None
	n115_var_Set = None
	n115_var_Value = None
	def n120_trigger_In(self):
		id = 597
		ability = DefMgr.get('ability', id)
		if ability and self.n120_var_Actor and self.n120_var_Actor.abilities.launchAbility(ability, targetId = self.n120_var_Target.entityId if self.n120_var_Target else None,
			targetLoc = None, autoCycle = False, isEntityAbility = False):
			self.n124_trigger_In()
		else:
			self.owner.debug('Ability launch FAILED!')

	n120_var_Actor = None
	n120_var_Target = None
	n121_var_Player = None
	def n121_propagator_Player(self):
		self.n120_var_Actor = self.n121_var_Player
		self.n120_var_Target = self.n121_var_Player
		self.n124_var_Entity = self.n121_var_Player
		self.n124_var_Invoker = self.n121_var_Player
		self.n127_var_Entity = self.n121_var_Player
		self.n126_var_Entity = self.n121_var_Player
		self.n133_var_Target = self.n121_var_Player
		self.n134_var_Source = self.n121_var_Player
		self.n134_var_Target = self.n121_var_Player
		self.n135_var_Entity = self.n121_var_Player
		self.n137_var_Entity = self.n121_var_Player
		self.n142_var_Entity = self.n121_var_Player

	def n124_trigger_In(self):
		invoker = self.n124_var_Invoker
		effect = DefMgr.get('effect', 1635)
		self.n124_var_Entity.abilities.addEffect(effect, invoker.entityId if invoker else 0)
		# TODO: CancelTimer, avoid multiple In() calls and multiple parallel timers?
		def timerCb():
			self.n127_trigger_In()
		Atrea.addTimer(Atrea.getGameTime() + 10, timerCb)

	n124_var_Entity = None
	n124_var_Invoker = None
	n126_var_Entity = None
	def n127_trigger_In(self):
		if self.n127_var_Entity.abilities.hasEffect(1635):
			self.n126_var_Entity.abilities.removeEffect(DefMgr.get('effect', 1635))
			self.n130_trigger_In()
			self.n132_trigger_In()
		else:
			self.owner.debug('Effect check FAILED!')

	n127_var_Entity = None
	def n129_trigger_In(self):
		entity = self.n129_var_Entity
		if entity is not None:
			self.n129_var_Position = entity.position
			self.n133_var_Destination = self.n129_var_Position
		pos = self.n133_var_Destination
		self.n133_var_Target.moveTo(pos.x, pos.y, pos.z, worldName = '' or None)

	n129_var_Entity = None
	n129_var_Position = None
	def n130_trigger_In(self):
		self.n130_var_Entity = None
		if None is not None:
			self.n130_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'Prisoner_329'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n130_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n130_var_Entity = entity
						break
			else:
				self.n130_var_Entity = None
		self.n129_var_Entity = self.n130_var_Entity
		if self.n130_var_Entity is not None:
			self.n129_trigger_In()
		else:
			self.owner.debug('Get entity FAILED!')

	n130_var_Entity = None
	def n132_trigger_In(self):
		self.n132_var_Entity = None
		if None is not None:
			self.n132_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'aasdadadsadsdsadadsadasaad_NONEXISTENT'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n132_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n132_var_Entity = entity
						break
			else:
				self.n132_var_Entity = None
		if self.n132_var_Entity is not None:
			self.owner.debug('Get entity FAILED!')

	n132_var_Entity = None
	n133_var_Target = None
	n133_var_Destination = None
	def n134_trigger_In(self):
		if self.n134_var_Source is not None and 0 is not None:
			target = self.n134_var_Target
			targetId = target.entityId if target else None
			self.n134_var_Source.playSequence(0, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)
		self.n135_var_Entity.addMovementLock()
		self.n136_trigger_In()

	n134_var_Source = None
	n134_var_Target = None
	n135_var_Entity = None
	def n136_trigger_In(self):
		# TODO: CancelTimer, avoid multiple In() calls and multiple parallel timers?
		def timerCb():
			self.n137_var_Entity.removeMovementLock()
			self.n140_trigger_In()
		Atrea.addTimer(Atrea.getGameTime() + 15, timerCb)

	n137_var_Entity = None
	def n139_trigger_Set(self):
		entity = self.n139_var_Entity
		if entity is None:
			self.owner.debug('Interaction type update FAILED!')
			return
		entity.setInteractionType(entity.interactionType | 4539628428684427264)
		self.n142_var_Entity.setCombatantStateFlag(4)

	def n139_trigger_Unset(self):
		entity = self.n139_var_Entity
		if entity is None:
			self.owner.debug('Interaction type update FAILED!')
			return
		entity.setInteractionType(entity.interactionType & ~4539628428684427264)
		self.n142_var_Entity.setCombatantStateFlag(4)

	n139_var_Entity = None
	def n140_trigger_In(self):
		self.n140_var_Entity = None
		if None is not None:
			self.n140_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'Prisoner_329'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n140_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n140_var_Entity = entity
						break
			else:
				self.n140_var_Entity = None
		self.n139_var_Entity = self.n140_var_Entity
		if self.n140_var_Entity is not None:
			self.n139_trigger_Set()

	n140_var_Entity = None
	n142_var_Entity = None
	def n143_trigger_In(self):
		changed = self.effect.changeStat(8, 0, 100, False)
		self.n143_var_Difference = changed
		self.n144_var_A = self.n143_var_Difference
		if self.n144_var_A == self.n144_var_B:
			result = self.effect.qrCombatDamage(7, 14, 100, True, True)
		if self.n144_var_A != self.n144_var_B:
			self.owner.debug('Effect stat change FAILED!')

	n143_var_Difference = None
	n144_var_A = None
	n144_var_B = None
	n146_var_Set = None
	n146_var_Value = None
	def n149_trigger_In(self):
		item = self.n149_var_Player.inventory.findItem(1874, 0 or None, not False)
		if item is not None:
			self.owner.debug('Player already has debug item - FAILED!')
		else:
			self.n152_trigger_In()

	n149_var_Player = None
	n150_var_Player = None
	def n150_propagator_Player(self):
		self.n149_var_Player = self.n150_var_Player
		self.n152_var_Player = self.n150_var_Player
		self.n154_var_Player = self.n150_var_Player
		self.n156_var_Player = self.n150_var_Player
		self.n158_var_Player = self.n150_var_Player

	def n152_trigger_In(self):
		if self.n152_var_Player is None or not 1874:
			self.owner.debug('Give items to player FAILED!')
			return
		if not 0:
			added = self.n152_var_Player.inventory.pickedUpItem(1874, 2 or 1)
		else:
			added = self.n152_var_Player.inventory.addItem(0, 1874, 2 or 1)
		self.n152_var_Player.inventory.flushUpdates()
		if added:
			self.n154_trigger_In()
		else:
			self.owner.debug('Give items to player FAILED!')

	n152_var_Player = None
	def n154_trigger_In(self):
		item = self.n154_var_Player.inventory.findItem(1874, 0 or None, not False)
		if item is not None:
			self.n156_trigger_In()
		else:
			self.owner.debug('Give items to player FAILED!')

	n154_var_Player = None
	def n156_trigger_In(self):
		if self.n156_var_Player and (1874 or None):
			removed = False
			if not removed and 1874:
				removed = self.n156_var_Player.inventory.removeItemByDesign(1874, 2, False)
			self.n156_var_Player.inventory.flushUpdates()
			if removed:
				self.n158_trigger_In()
			else:
				self.owner.debug('Remove items from player FAILED!')
		else:
			self.owner.debug('Remove items from player FAILED!')

	n156_var_Player = None
	def n158_trigger_In(self):
		if self.n158_var_Player and (1874 or None):
			removed = False
			if not removed and 1874:
				removed = self.n158_var_Player.inventory.removeItemByDesign(1874, 1, False)
			self.n158_var_Player.inventory.flushUpdates()
			if removed:
				self.owner.debug('Nonexistent item removed - FAILED!')

	n158_var_Player = None
	def __init__(self, owner, effect, nvps):
		EffectScript.__init__(self, owner, effect, nvps)
		self.n42_var_Value = 10
		self.n41_var_A = self.n42_var_Value
		self.n43_var_Value = 2
		self.n41_var_B = self.n43_var_Value
		self.n46_var_B = self.n43_var_Value
		self.n45_var_Value = 4
		self.n44_var_B = self.n45_var_Value
		self.n47_var_B = self.n45_var_Value
		self.n48_var_B = self.n45_var_Value
		self.n55_var_Player = self.owner
		self.n55_propagator_Player()
		self.n100_var_Value = 'DEBUG ENTITY'
		self.n98_var_Name = self.n100_var_Value
		self.n105_var_A = self.n100_var_Value
		self.n108_var_Value = 0
		self.n107_var_B = self.n108_var_Value
		self.n113_var_Player = self.owner
		self.n112_var_Entity = self.n113_var_Player
		self.n92_var_Entity = self.n113_var_Player
		self.n115_var_Value = 0.1
		self.n114_var_B = self.n115_var_Value
		self.n121_var_Player = self.owner
		self.n121_propagator_Player()
		self.n146_var_Value = 100
		self.n144_var_B = self.n146_var_Value
		self.n150_var_Player = self.owner
		self.n150_propagator_Player()

