<#
.SYNOPSIS
    Run the shared lab supervisor (`cimmeria-lab --http`) as a per-user
    scheduled task: install, start, stop, restart, status, uninstall.

.DESCRIPTION
    One daemon serves every Claude session on this machine over MCP
    streamable HTTP (loopback, token-gated). It replaces one stdio
    `cimmeria-lab` per session, each with its own watchdog. Design: the
    "One shared daemon" addendum of docs/architecture/live-research-lab.md;
    runbook: docs/guides/live-research-lab.md.

    Everything lives in %LOCALAPPDATA%\cimmeria-lab:
      labd\cimmeria-lab.exe the daemon's own copy of the exe, so neither a
                            rebuild in target\ nor tools/lab/install.ps1
                            (which writes bin\) is blocked by the running
                            daemon; `restart` picks up the newer build
      labd\daemon.ps1       this script, which the task runs (`run`)
      labd.env              KEY=VALUE lines: the supervisor's environment
                            (CIMMERIA_LAB_INSTALL_DIR, _START32, ...)
      labd.log              the daemon log (rotates at 10 MiB, 5 kept)
      labd-task.log         this wrapper's restart log
      labd.pid              pid + bind of the running daemon

    The bearer token is the user environment variable
    CIMMERIA_LAB_DAEMON_TOKEN (generated by `install` when missing). Claude
    Code reads it through tools/lab/labd-headers.ps1 (`headersHelper`), so
    the token never lands in .mcp.json.

.PARAMETER Command
    install | uninstall | start | stop | restart | status | run
    `run` is what the scheduled task executes; you do not call it yourself.

.PARAMETER Bind
    Loopback address to listen on. Default 127.0.0.1:8779.

.PARAMETER Exe
    The cimmeria-lab.exe to install (install / restart). Default: the
    first that exists of %LOCALAPPDATA%\cimmeria-lab\bin\cimmeria-lab.exe
    (what tools/lab/install.ps1 installs) and the repo's
    target\debug\cimmeria-lab.exe. `restart` without -Exe copies it only
    when it is newer than the daemon's copy.

.PARAMETER EnvFrom
    A .mcp.json whose stdio `cimmeria-lab` entry's `env` block seeds
    labd.env on install. Default: the repo's .mcp.json.

.PARAMETER Force
    install: overwrite an existing labd.env from -EnvFrom.

.EXAMPLE
    pwsh tools/lab/daemon.ps1 install
    pwsh tools/lab/daemon.ps1 status
    pwsh tools/lab/daemon.ps1 restart -Exe $env:CIMMERIA_TARGET_ROOT\Cimmeria\debug\cimmeria-lab.exe
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0, Mandatory = $true)]
    [ValidateSet('install', 'uninstall', 'start', 'stop', 'restart', 'status', 'run')]
    [string]$Command,
    [string]$Bind = '127.0.0.1:8779',
    [string]$Exe,
    [string]$EnvFrom,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$TaskName = 'CimmeriaLabDaemon'
$TokenVar = 'CIMMERIA_LAB_DAEMON_TOKEN'
$State = Join-Path $env:LOCALAPPDATA 'cimmeria-lab'
$Bin = Join-Path $State 'labd'
$DaemonExe = Join-Path $Bin 'cimmeria-lab.exe'
$EnvFile = Join-Path $State 'labd.env'
$LogFile = Join-Path $State 'labd.log'
$TaskLog = Join-Path $State 'labd-task.log'
$PidFile = Join-Path $State 'labd.pid'
# Exit codes of `cimmeria-lab --http` (crates/lab/src/daemon/mod.rs).
$ExitRefused = 2
$ExitAlreadyRunning = 3

function Get-RepoRoot {
    $here = Split-Path -Parent $PSCommandPath
    $root = Resolve-Path (Join-Path $here '..\..') -ErrorAction SilentlyContinue
    if ($root -and (Test-Path (Join-Path $root 'Cargo.toml'))) { return $root.Path }
    return $null
}

function Write-TaskLog([string]$msg) {
    $line = '{0:yyyy-MM-ddTHH:mm:ss} {1}' -f (Get-Date), $msg
    Add-Content -Path $TaskLog -Value $line -Encoding ascii
    $item = Get-Item $TaskLog -ErrorAction SilentlyContinue
    if ($item -and $item.Length -gt 1MB) {
        Move-Item -Force $TaskLog "$TaskLog.1"
    }
}

function Get-Token {
    $t = [Environment]::GetEnvironmentVariable($TokenVar, 'User')
    if (-not $t) { $t = [Environment]::GetEnvironmentVariable($TokenVar, 'Process') }
    return $t
}

function New-Token {
    $bytes = New-Object byte[] 32
    # Create().GetBytes, not ::Fill: the task runs Windows PowerShell 5.1.
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

function Read-DaemonPid {
    if (-not (Test-Path $PidFile)) { return $null }
    try { return (Get-Content -Raw $PidFile | ConvertFrom-Json) } catch { return $null }
}

function Import-EnvFile {
    if (-not (Test-Path $EnvFile)) { return }
    foreach ($line in Get-Content $EnvFile) {
        $l = $line.Trim()
        if (-not $l -or $l.StartsWith('#')) { continue }
        $i = $l.IndexOf('=')
        if ($i -lt 1) { continue }
        [Environment]::SetEnvironmentVariable($l.Substring(0, $i).Trim(), $l.Substring($i + 1), 'Process')
    }
}

function Write-EnvFile([string]$from) {
    $lines = @(
        '# Environment for the shared lab daemon (tools/lab/daemon.ps1).',
        '# KEY=VALUE per line; the same variables the stdio cimmeria-lab took',
        '# from its .mcp.json env block. Restart the daemon after editing.'
    )
    if ($from -and (Test-Path $from)) {
        $json = Get-Content -Raw $from | ConvertFrom-Json
        $entry = $json.mcpServers.'cimmeria-lab'
        if ($entry -and $entry.env) {
            foreach ($p in $entry.env.PSObject.Properties) {
                $lines += '{0}={1}' -f $p.Name, $p.Value
            }
            Write-Host "labd.env: imported $(@($entry.env.PSObject.Properties).Count) variables from $from"
        } else {
            Write-Warning "$from has no stdio cimmeria-lab env block; labd.env is a stub, fill it in"
        }
    } else {
        Write-Warning 'no .mcp.json to import from; labd.env is a stub, fill it in'
        $lines += '# CIMMERIA_LAB_INSTALL_DIR=C:\path\to\Stargate Worlds'
        $lines += '# CIMMERIA_LAB_START32=C:\path\to\sgw-start32.exe'
    }
    Set-Content -Path $EnvFile -Value $lines -Encoding ascii
}

function Get-DefaultExe {
    $installed = Join-Path $State 'bin\cimmeria-lab.exe'
    if (Test-Path $installed) { return $installed }
    $root = Get-RepoRoot
    if ($root) {
        $built = Join-Path $root 'target\debug\cimmeria-lab.exe'
        if (Test-Path $built) { return $built }
    }
    return $null
}

function Copy-DaemonExe([string]$src) {
    if (-not $src) { $src = Get-DefaultExe }
    if (-not $src -or -not (Test-Path $src)) {
        throw "cimmeria-lab.exe not found ($src). Build it (bash tools/build-lane/lane.sh cargo build -p cimmeria-lab) and pass -Exe <path>."
    }
    New-Item -ItemType Directory -Force $Bin | Out-Null
    Copy-Item -Force $src $DaemonExe
    # The sgw-start32 helper defaults to "beside the exe"; copy it along when
    # it sits beside the source so an unset CIMMERIA_LAB_START32 still works.
    $helper = Join-Path (Split-Path -Parent $src) 'sgw-start32.exe'
    if (Test-Path $helper) { Copy-Item -Force $helper (Join-Path $Bin 'sgw-start32.exe') }
    Write-Host "installed $src -> $DaemonExe"
}

function Stop-Daemon {
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task -and $task.State -eq 'Running') { Stop-ScheduledTask -TaskName $TaskName }
    $info = Read-DaemonPid
    if ($info -and $info.pid) {
        $p = Get-Process -Id $info.pid -ErrorAction SilentlyContinue
        if ($p -and $p.ProcessName -eq 'cimmeria-lab') {
            Stop-Process -Id $info.pid -Force
            Write-Host "stopped daemon pid $($info.pid)"
        }
    }
    # A daemon whose pidfile is gone still holds the exe open; stop any
    # process running our copy.
    Get-Process cimmeria-lab -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -eq $DaemonExe } |
        ForEach-Object { Stop-Process -Id $_.Id -Force; Write-Host "stopped daemon pid $($_.Id)" }
    Remove-Item -Force $PidFile -ErrorAction SilentlyContinue
}

function Test-Port([string]$addr) {
    $hostPart, $port = $addr -split ':(?=\d+$)'
    $c = New-Object System.Net.Sockets.TcpClient
    try { $c.Connect($hostPart.Trim('[', ']'), [int]$port); return $true } catch { return $false } finally { $c.Dispose() }
}

switch ($Command) {
    'install' {
        New-Item -ItemType Directory -Force $State, $Bin | Out-Null
        Stop-Daemon
        Copy-DaemonExe $Exe
        Copy-Item -Force $PSCommandPath (Join-Path $Bin 'daemon.ps1')

        $token = Get-Token
        if (-not $token -or $token.Length -lt 32) {
            $token = New-Token
            [Environment]::SetEnvironmentVariable($TokenVar, $token, 'User')
            Write-Host "generated $TokenVar (user environment variable)"
        }

        if ($Force -or -not (Test-Path $EnvFile)) {
            if (-not $EnvFrom) {
                $root = Get-RepoRoot
                if ($root) { $EnvFrom = Join-Path $root '.mcp.json' }
            }
            Write-EnvFile $EnvFrom
        } else {
            Write-Host "labd.env: keeping the existing $EnvFile (-Force to re-import)"
        }

        $script = Join-Path $Bin 'daemon.ps1'
        $action = New-ScheduledTaskAction -Execute 'powershell.exe' `
            -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$script`" run -Bind $Bind" `
            -WorkingDirectory $State
        $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
        $trigger = New-ScheduledTaskTrigger -AtLogOn -User $user
        # Interactive: the daemon launches SGW.exe, which needs the desktop.
        $principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Limited
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
            -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit ([TimeSpan]::Zero) `
            -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1)
        Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
            -Principal $principal -Settings $settings -Force | Out-Null
        Write-Host "registered scheduled task $TaskName (at logon, restart on failure)"
        Start-ScheduledTask -TaskName $TaskName
        Write-Host "started; check with: pwsh tools/lab/daemon.ps1 status"
    }
    'uninstall' {
        Stop-Daemon
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
        Write-Host "removed task $TaskName; $State (logs, labd.env, labd\) is left in place"
    }
    'start' {
        Start-ScheduledTask -TaskName $TaskName
        Write-Host "started $TaskName"
    }
    'stop' {
        Stop-Daemon
    }
    'restart' {
        Stop-Daemon
        if ($Exe) {
            Copy-DaemonExe $Exe
        } else {
            $src = Get-DefaultExe
            if ($src -and (-not (Test-Path $DaemonExe) -or
                    (Get-Item $src).LastWriteTime -gt (Get-Item $DaemonExe).LastWriteTime)) {
                Copy-DaemonExe $src
            }
        }
        $taskScript = Join-Path $Bin 'daemon.ps1'
        if ($PSCommandPath -ne $taskScript) { Copy-Item -Force $PSCommandPath $taskScript }
        Start-ScheduledTask -TaskName $TaskName
        Write-Host "restarted $TaskName; MCP sessions reconnect on their next call (or /mcp)"
    }
    'status' {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        if (-not $task) { Write-Host "task ${TaskName}: not installed"; break }
        $ti = Get-ScheduledTaskInfo -TaskName $TaskName
        Write-Host "task ${TaskName}: $($task.State) (last result $($ti.LastTaskResult), last run $($ti.LastRunTime))"
        $info = Read-DaemonPid
        if ($info) {
            $alive = [bool](Get-Process -Id $info.pid -ErrorAction SilentlyContinue)
            Write-Host "daemon: pid $($info.pid) on $($info.bind), alive=$alive, since $($info.started_at)"
        } else {
            Write-Host 'daemon: no pidfile (not running)'
        }
        Write-Host "port $Bind listening: $(Test-Port $Bind)"
        Write-Host "token ($TokenVar): $(if (Get-Token) { 'set' } else { 'MISSING' })"
        if (Test-Path $LogFile) {
            Write-Host "--- last lines of $LogFile"
            Get-Content $LogFile -Tail 8
        }
    }
    'run' {
        # The scheduled task's action. Restarts the daemon after a crash,
        # stops on a clean exit or a refusal (restarting cannot fix those).
        New-Item -ItemType Directory -Force $State | Out-Null
        $token = Get-Token
        if ($token) { [Environment]::SetEnvironmentVariable($TokenVar, $token, 'Process') }
        $recent = New-Object System.Collections.Generic.List[datetime]
        while ($true) {
            Import-EnvFile
            Write-TaskLog "starting $DaemonExe --http $Bind"
            & $DaemonExe --http $Bind --log-file $LogFile
            $code = $LASTEXITCODE
            Write-TaskLog "daemon exited with $code"
            if ($code -eq 0) { exit 0 }
            if ($code -eq $ExitRefused -or $code -eq $ExitAlreadyRunning) { exit $code }
            $now = Get-Date
            $recent.Add($now)
            $recent.RemoveAll({ param($t) ($now - $t).TotalMinutes -gt 5 }) | Out-Null
            if ($recent.Count -ge 5) {
                # Hand back to the task scheduler's own restart (1 min).
                Write-TaskLog 'five crashes in five minutes; exiting for the task restart'
                exit 1
            }
            Start-Sleep -Seconds 5
        }
    }
}
