"""Command line: before-and-after measures across the ledger's cut lines.

    python tools/token-profile/cutlines --db <profile.sqlite> [--out <dir>] [--since ISO] [--cut TP-03=ISO ...]

Writes cutlines.md and cutlines.json (or prints the Markdown), through the
same privacy gate as the reports (exit code 3 if it refuses).
"""

import argparse
import json
import sys
from pathlib import Path

from report import db as dbmod
from report.render import dist_table, num
from report.scrub import PrivacyError, Scrubber

from . import measures

# The ledger's cut-line log (docs/analysis/token-usage/README.md).
CUTS = {"TP-00": "2026-10-03T11:39:49Z", "TP-03": "2026-10-03T12:04:06Z", "TP-02": "2026-10-03T12:33:56Z"}


def _pair(label, d):
    return [(f"{label}, before", d["before"]), (f"{label}, after", d["after"])]


def markdown(r):
    sc_, lo, wl = r["static_context"], r["lane_output"], r["worker_lifetime"]
    parts = [
        "# Token profile cut lines\n",
        "Generated by `tools/token-profile/cutlines`. Aggregates only. Requests from"
        f" {r['since']} to the last ingested request, {r['last_request']}. Cuts: "
        + ", ".join(f"{k} {v}" for k, v in r["cuts"].items()) + ".\n",
        f"## Static context: first request of each transcript ({sc_['cut']})\n",
        "Context tokens of a transcript's first request, for transcripts that started before or after the cut.\n",
        dist_table([x for k, v in sc_["by_scope"].items() for x in _pair(k, v)], first="scope"),
        "\nBy agent type:\n",
        dist_table([x for k, v in sc_["by_agent_type"].items() for x in _pair(k, v)], first="agent type"),
        f"\n## Lane output ({lo['cut']})\n",
        "Result characters of `lane.sh` calls. A background call's result is its task notice only.\n",
        dist_table(_pair("foreground", lo["foreground"]) + _pair("background", lo["background"]), first="calls"),
        f"\n## Worker lifetime ({wl['cut']})\n",
        "Per subagent transcript, by when it started. Transcripts still running at ingest are cut short.\n",
        dist_table(_pair("requests", {s: wl[s]["requests"] for s in ("before", "after")})
                   + _pair("peak context", {s: wl[s]["peak_context"] for s in ("before", "after")}),
                   first="measure"),
        "\nOver 200 requests: before " + num(wl["before"]["over_200_requests"]) + ", after "
        + num(wl["after"]["over_200_requests"]) + ".\n",
    ]
    return "\n".join(parts)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="token-profile cutlines", description=__doc__.split("\n\n")[0])
    ap.add_argument("--db", required=True)
    ap.add_argument("--out", help="directory for cutlines.md and cutlines.json")
    ap.add_argument("--since", default="2026-09-14T00:00:00Z", help="first request included (ISO-8601 UTC)")
    ap.add_argument("--cut", action="append", default=[], help="NAME=ISO, overriding a ledger cut (repeatable)")
    ap.add_argument("--deny", action="append", default=[])
    args = ap.parse_args(argv)
    cuts = dict(CUTS)
    for c in args.cut:
        name, _, iso = c.partition("=")
        cuts[name] = iso
    sc = Scrubber(deny=args.deny)
    try:
        db = dbmod.open_db(args.db)
        try:
            result = sc.obj(measures.build(db, sc, args.since, cuts))
        finally:
            db.close()
        md, js = markdown(result), json.dumps(result, indent=1) + "\n"
        sc.assert_clean(md, "Markdown cut lines")
        sc.assert_clean(js, "JSON cut lines")
    except PrivacyError as e:
        print(f"status=refused {e}", file=sys.stderr)
        return 3
    except dbmod.ReportError as e:
        print(f"status=error {e}", file=sys.stderr)
        return 2
    if args.out:
        out = Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        (out / "cutlines.md").write_text(md, encoding="utf-8", newline="\n")
        (out / "cutlines.json").write_text(js, encoding="utf-8", newline="\n")
        print(f"status=ok wrote cutlines.md and cutlines.json to {args.out}")
    else:
        print(md)
    return 0
