--
-- Special-ammo reserve items (ammo campaign AM-F, issue #1026).
--
-- One stackable item per special EAmmoType. A stack counts individual
-- rounds (D-AM05), lives in the carried bags (D-AM01) and is what a reload
-- of a special type draws from once `ammo.finite_special` is on. Default
-- ammo (Bullet_Default / Dart_Default) has no item: its reloads stay free
-- (D-AM02).
--
-- Ids 9000-9014 are reserved for this block (audit A-15: nothing under
-- db/resources/ used 9000-9999); 9015-9099 stay in reserve. Code never names
-- these ids: it goes through resources.ammo_item_types (ammo_item_types.sql).
--
-- Column choices:
--   container_sets '{1,15,17}'  main bag, crafting bag, personal vault
--   max_stack_size 500          rounds per stack
--   clip_size 0                 a reserve stack, not a weapon, so
--                               load_item_defs (WHERE clip_size > 0) skips it
--   flags 3072                  ITEM_FLAG_CanBeSold | ITEM_FLAG_CanBeDeleted
--                               (1 << 10 | 1 << 11); not bound
--   icon                        the stock placeholder until AM-07 pushes the
--                               cooked definitions the client renders from
--
-- RECONSTRUCTION: the 2009 client has no ammo item category and no reserve
-- (docs/reverse-engineering/findings/ammo-system.md Q1). Names follow the
-- EAmmoType tokens and the toggle abilities' names.
--

SET search_path = resources, pg_catalog;

INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9000, NULL, 'Special Ammunition - Bullet', 'set:CoreWidgets image:IconMissing', 'Armor Piercing Rounds', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9001, NULL, 'Special Ammunition - Bullet', 'set:CoreWidgets image:IconMissing', 'Hollow Point Rounds', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9002, NULL, 'Special Ammunition - Bullet', 'set:CoreWidgets image:IconMissing', 'Incendiary Rounds', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9003, NULL, 'Special Ammunition - Bullet', 'set:CoreWidgets image:IconMissing', 'EMP Rounds', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9004, NULL, 'Special Ammunition - Bullet', 'set:CoreWidgets image:IconMissing', 'Explosive Rounds', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9005, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Poison Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9006, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Disease Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9007, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Tranquilizer Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9008, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'EMP Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9009, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Radioactive Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9010, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Stim Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9011, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Coagulant Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9012, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Nanite Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9013, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Antidote Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
INSERT INTO items (item_id, applied_science_id, description, icon_location, name, quality_id, tech_comp, tier, container_sets, max_stack_size, moniker_ids, max_ranged_range, min_ranged_range, visual_component, max_melee_range, min_melee_range, discipline_ids, flags, ammo_types, default_ammo_type, clip_size, charges) VALUES (9014, NULL, 'Special Ammunition - Dart', 'set:CoreWidgets image:IconMissing', 'Adrenaline Darts', 'ITEM_QUALITY_Normal', 1, 1, '{1,15,17}', 500, '{}', 0, 0, NULL, 0, 0, '{}', 3072, '{}', NULL, 0, 0);
