--
-- Data for Name: crafting_item_effects; Type: TABLE DATA; Schema: resources; Owner: -
--
-- GENERATED by tools/crafting/generate_item_effects.py; do not edit by hand.
-- Blueprint items come from docs/analysis/crafting/source/blueprint-items.csv
-- (confidence high, medium-high or medium only); the Racial Paradigm Guides
-- are matched to racial_paradigm by name.
--

-- Blueprint items: using one teaches its blueprint(s).
-- Blueprint: Steel Plating (Materials Subcombine A)
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (6483, 25, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8666, 311, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8667, 415, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8668, 422, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8669, 429, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8670, 436, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8671, 443, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8672, 450, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8673, 457, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8674, 464, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8675, 471, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8676, 478, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8677, 485, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8678, 492, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8679, 499, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8680, 506, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8681, 513, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8682, 520, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8683, 527, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8684, 534, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8685, 541, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8687, 548, NULL);
-- Blueprint: Archaeologist Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8688, 555, NULL);
-- Blueprint: Asgard Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8689, 312, NULL);
-- Blueprint: Asgard Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8690, 416, NULL);
-- Blueprint: Asgard Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8691, 423, NULL);
-- Blueprint: Asgard Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8692, 430, NULL);
-- Blueprint: Asgard Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8693, 437, NULL);
-- Blueprint: Asgard Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8694, 444, NULL);
-- Blueprint: Asgard Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8695, 451, NULL);
-- Blueprint: Asgard Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8696, 458, NULL);
-- Blueprint: Asgard Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8697, 465, NULL);
-- Blueprint: Asgard Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8698, 472, NULL);
-- Blueprint: Asgard Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8699, 479, NULL);
-- Blueprint: Asgard Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8700, 486, NULL);
-- Blueprint: Asgard Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8701, 493, NULL);
-- Blueprint: Asgard Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8702, 500, NULL);
-- Blueprint: Asgard Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8703, 507, NULL);
-- Blueprint: Asgard Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8704, 514, NULL);
-- Blueprint: Asgard Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8705, 521, NULL);
-- Blueprint: Asgard Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8706, 528, NULL);
-- Blueprint: Asgard Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8707, 535, NULL);
-- Blueprint: Asgard Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8708, 542, NULL);
-- Blueprint: Asgard Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8709, 549, NULL);
-- Blueprint: Asgard Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8710, 556, NULL);
-- Blueprint: Commando Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8711, 313, NULL);
-- Blueprint: Commando Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8712, 417, NULL);
-- Blueprint: Commando Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8713, 424, NULL);
-- Blueprint: Commando Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8714, 431, NULL);
-- Blueprint: Commando Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8715, 438, NULL);
-- Blueprint: Commando Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8716, 445, NULL);
-- Blueprint: Commando Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8717, 452, NULL);
-- Blueprint: Commando Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8718, 459, NULL);
-- Blueprint: Commando Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8719, 466, NULL);
-- Blueprint: Commando Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8720, 473, NULL);
-- Blueprint: Commando Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8721, 480, NULL);
-- Blueprint: Commando Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8722, 487, NULL);
-- Blueprint: Commando Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8723, 494, NULL);
-- Blueprint: Commando Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8724, 501, NULL);
-- Blueprint: Commando Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8725, 508, NULL);
-- Blueprint: Commando Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8726, 515, NULL);
-- Blueprint: Commando Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8727, 522, NULL);
-- Blueprint: Commando Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8728, 529, NULL);
-- Blueprint: Commando Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8729, 536, NULL);
-- Blueprint: Commando Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8730, 543, NULL);
-- Blueprint: Commando Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8731, 550, NULL);
-- Blueprint: Commando Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8732, 557, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8733, 314, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8734, 418, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8735, 425, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8736, 432, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8737, 439, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8738, 446, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8739, 453, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8740, 460, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8741, 467, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8742, 474, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8743, 481, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8744, 488, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8745, 495, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8746, 502, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8747, 509, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8748, 516, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8749, 523, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8750, 530, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8751, 537, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8752, 544, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8753, 551, NULL);
-- Blueprint: Goa'uld Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8754, 558, NULL);
-- Blueprint: Jaffa Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8755, 315, NULL);
-- Blueprint: Jaffa Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8756, 419, NULL);
-- Blueprint: Jaffa Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8757, 426, NULL);
-- Blueprint: Jaffa Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8758, 433, NULL);
-- Blueprint: Jaffa Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8759, 440, NULL);
-- Blueprint: Jaffa Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8760, 447, NULL);
-- Blueprint: Jaffa Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8761, 454, NULL);
-- Blueprint: Jaffa Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8762, 461, NULL);
-- Blueprint: Jaffa Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8763, 468, NULL);
-- Blueprint: Jaffa Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8764, 475, NULL);
-- Blueprint: Jaffa Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8765, 482, NULL);
-- Blueprint: Jaffa Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8766, 489, NULL);
-- Blueprint: Jaffa Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8767, 496, NULL);
-- Blueprint: Jaffa Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8768, 503, NULL);
-- Blueprint: Jaffa Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8769, 510, NULL);
-- Blueprint: Jaffa Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8770, 517, NULL);
-- Blueprint: Jaffa Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8771, 524, NULL);
-- Blueprint: Jaffa Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8772, 531, NULL);
-- Blueprint: Jaffa Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8773, 538, NULL);
-- Blueprint: Jaffa Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8774, 545, NULL);
-- Blueprint: Jaffa Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8775, 552, NULL);
-- Blueprint: Jaffa Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8776, 559, NULL);
-- Blueprint: Scientist Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8777, 316, NULL);
-- Blueprint: Scientist Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8778, 420, NULL);
-- Blueprint: Scientist Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8779, 427, NULL);
-- Blueprint: Scientist Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8780, 434, NULL);
-- Blueprint: Scientist Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8781, 441, NULL);
-- Blueprint: Scientist Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8782, 448, NULL);
-- Blueprint: Scientist Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8783, 455, NULL);
-- Blueprint: Scientist Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8784, 462, NULL);
-- Blueprint: Scientist Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8785, 469, NULL);
-- Blueprint: Scientist Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8786, 476, NULL);
-- Blueprint: Scientist Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8787, 483, NULL);
-- Blueprint: Scientist Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8788, 490, NULL);
-- Blueprint: Scientist Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8789, 497, NULL);
-- Blueprint: Scientist Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8790, 504, NULL);
-- Blueprint: Scientist Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8791, 511, NULL);
-- Blueprint: Scientist Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8792, 518, NULL);
-- Blueprint: Scientist Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8793, 525, NULL);
-- Blueprint: Scientist Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8794, 532, NULL);
-- Blueprint: Scientist Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8795, 539, NULL);
-- Blueprint: Scientist Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8796, 546, NULL);
-- Blueprint: Scientist Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8797, 553, NULL);
-- Blueprint: Scientist Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8798, 560, NULL);
-- Blueprint: Soldier Minigame Consumable TC3
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8799, 317, NULL);
-- Blueprint: Soldier Minigame Consumable TC5
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8800, 421, NULL);
-- Blueprint: Soldier Minigame Consumable TC8
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8801, 428, NULL);
-- Blueprint: Soldier Minigame Consumable TC10
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8802, 435, NULL);
-- Blueprint: Soldier Minigame Consumable TC13
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8803, 442, NULL);
-- Blueprint: Soldier Minigame Consumable TC15
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8804, 449, NULL);
-- Blueprint: Soldier Minigame Consumable TC18
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8805, 456, NULL);
-- Blueprint: Soldier Minigame Consumable TC20
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8806, 463, NULL);
-- Blueprint: Soldier Minigame Consumable TC23
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8807, 470, NULL);
-- Blueprint: Soldier Minigame Consumable TC25
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8808, 477, NULL);
-- Blueprint: Soldier Minigame Consumable TC28
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8809, 484, NULL);
-- Blueprint: Soldier Minigame Consumable TC30
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8810, 491, NULL);
-- Blueprint: Soldier Minigame Consumable TC33
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8811, 498, NULL);
-- Blueprint: Soldier Minigame Consumable TC35
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8812, 505, NULL);
-- Blueprint: Soldier Minigame Consumable TC38
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8813, 512, NULL);
-- Blueprint: Soldier Minigame Consumable TC40
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8814, 519, NULL);
-- Blueprint: Soldier Minigame Consumable TC43
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8815, 526, NULL);
-- Blueprint: Soldier Minigame Consumable TC45
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8816, 533, NULL);
-- Blueprint: Soldier Minigame Consumable TC48
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8817, 540, NULL);
-- Blueprint: Soldier Minigame Consumable TC50
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8818, 547, NULL);
-- Blueprint: Soldier Minigame Consumable TC53
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8819, 554, NULL);
-- Blueprint: Soldier Minigame Consumable TC55
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8820, 561, NULL);
-- Blueprint: Omni Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8870, 377, NULL);
-- Blueprint: Double Omni Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8871, 379, NULL);
-- Blueprint: Panacea Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8872, 378, NULL);
-- Blueprint: Health/Mental Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8873, 371, NULL);
-- Blueprint: Health/Kinetic Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8874, 370, NULL);
-- Blueprint: Kinetic/Mental Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8875, 372, NULL);
-- Blueprint: Kinetic/Mental/Health Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8877, 376, NULL);
-- Blueprint: Kinetic/Mental Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8878, 372, NULL);
-- Blueprint: Double Health/Kinetic Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8880, 373, NULL);
-- Blueprint: Double Kinetic/Mental Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8881, 375, NULL);
-- Blueprint: Health Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8882, 367, NULL);
-- Blueprint: Health Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8882, 369, NULL);
-- Blueprint: Double Health/Mental Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8883, 374, NULL);
-- Blueprint: Double Omni Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8884, 379, NULL);
-- Blueprint: Kinetic Antidote
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8886, 368, NULL);
-- Blueprint: Mark III Stimpack: Fortitude
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8922, 382, NULL);
-- Blueprint: Mark III Stimpack: Perception
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8923, 385, NULL);
-- Blueprint: Mark III Stimpack: Engagement
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8924, 381, NULL);
-- Blueprint: Mark III Stimpack: Morale
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8925, 384, NULL);
-- Blueprint: Mark III Stimpack: Intellect
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8926, 383, NULL);
-- Blueprint: Mark III Stimpack: Coordination
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8927, 380, NULL);
-- Blueprint: Mark V Stimpack: Coordination/Engagement
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8928, 386, NULL);
-- Blueprint: Mark VII Stimpack: Coordination/Engagement
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8929, 392, NULL);
-- Blueprint: Mark X Stimpack: Coordination/Engagement
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8930, 398, NULL);
-- Blueprint: Mark V Stimpack: Engagement/Perception
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8931, 387, NULL);
-- Blueprint: Mark VII Stimpack: Engagement/Perception
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8932, 393, NULL);
-- Blueprint: Mark X Stimpack: Engagement/Perception
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8933, 399, NULL);
-- Blueprint: Mark V Stimpack: Fortitude/Coordination
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8934, 388, NULL);
-- Blueprint: Mark VII Stimpack: Fortitude/Coordination
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8935, 394, NULL);
-- Blueprint: Mark X Stimpack: Fortitude/Coordination
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8936, 400, NULL);
-- Blueprint: Mark V Stimpack: Intellect/Morale
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8937, 390, NULL);
-- Blueprint: Mark VII Stimpack: Intellect/Morale
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8938, 396, NULL);
-- Blueprint: Mark X Stimpack: Intellect/Morale
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8939, 402, NULL);
-- Blueprint: Mark V Stimpack:Morale/Fortitude
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8940, 391, NULL);
-- Blueprint: Mark VII Stimpack:Morale/Fortitude
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8941, 397, NULL);
-- Blueprint: Mark X Stimpack:Morale/Fortitude
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8942, 403, NULL);
-- Blueprint: Mark V Stimpack:Perception/Intellect
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8943, 389, NULL);
-- Blueprint: Mark VII Stimpack:Perception/Intellect
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8944, 395, NULL);
-- Blueprint: Mark X Stimpack:Perception/Intellect
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (8945, 401, NULL);

-- Racial Paradigm Guides: using one raises its paradigm by 1, to at most 10.
-- Racial Paradigm Guide: Human
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (7805, NULL, 2);
-- Racial Paradigm Guide: Common
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (7806, NULL, 1);
-- Racial Paradigm Guide: Asgard
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (7807, NULL, 4);
-- Racial Paradigm Guide: Goa'uld
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (7808, NULL, 3);
-- Racial Paradigm Guide: Ancient
INSERT INTO crafting_item_effects (item_id, blueprint_id, racial_paradigm_id) VALUES (7809, NULL, 5);
