//! Cross-package export index for resolving references across .upk/.umap files.
//!
//! StaticMeshActors in .umap files reference meshes via import entries pointing to
//! .upk packages. The scene editor needs a package index built at startup to resolve
//! these cross-package references efficiently.
//!
//! Building the index scans all ~5,000 packages' export tables (~50 seconds).
//! The result is cached to disk via bincode for instant subsequent launches.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{ObjectError, Result};

/// Codec config for the on-disk index cache.
///
/// This MUST stay `legacy()`. bincode 2's `config::standard()` varint-encodes
/// integers, whereas bincode 1.x — which wrote every index cache that exists on
/// a developer's disk today — used fixed-width little-endian. `legacy()` is
/// bincode 2's bug-for-bug reproduction of those 1.x defaults, so keeping it
/// makes the 1.x -> 2.x bump a pure API migration with no data migration.
///
/// `index_cache_is_bincode_1x_compatible` pins this against a byte fixture
/// generated by actual bincode 1.3.3; changing this constant will fail it.
const CACHE_CONFIG: bincode::config::Configuration<
    bincode::config::LittleEndian,
    bincode::config::Fixint,
> = bincode::config::legacy();

/// Index of all exports across all packages for cross-reference resolution.
#[derive(Serialize, Deserialize)]
pub struct PackageIndex {
    /// `(package_name, object_name)` -> `ExportLocation`
    pub exports: HashMap<(String, String), ExportLocation>,
    /// `class_name` -> list of `(package_name, object_name)` keys
    pub by_class: HashMap<String, Vec<(String, String)>>,
    /// Total packages scanned.
    pub package_count: u32,
    /// Total exports indexed.
    pub export_count: u32,
}

/// Location of an export within a package file.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ExportLocation {
    pub file_path: PathBuf,
    pub export_index: usize,
    pub class_name: String,
    pub serial_size: i32,
}

impl PackageIndex {
    /// Build an index from a CookedPC directory by scanning all `.upk` and `.umap` files.
    ///
    /// This walks the directory recursively, opens each package, and records every
    /// export with `serial_size > 0` into the index.
    pub fn build(cooked_pc_path: &Path) -> Result<Self> {
        let mut exports = HashMap::new();
        let mut by_class: HashMap<String, Vec<(String, String)>> = HashMap::new();
        let mut package_count = 0u32;
        let mut export_count = 0u32;

        // Collect all .upk and .umap files recursively
        let mut files = Vec::new();
        collect_package_files(cooked_pc_path, &mut files);
        files.sort();

        let total_files = files.len();

        for file_path in &files {
            let pkg = match cimmeria_upk::Package::open(file_path) {
                Ok(p) => p,
                Err(e) => {
                    tracing::warn!("Failed to open {}: {}", file_path.display(), e);
                    continue;
                }
            };
            package_count += 1;

            // Derive package name from filename (without extension)
            let pkg_name = file_path
                .file_stem()
                .unwrap_or_default()
                .to_string_lossy()
                .to_string();

            for (i, export) in pkg.exports.iter().enumerate() {
                if export.serial_size <= 0 {
                    continue;
                }
                let class_name = pkg.export_class_name(export).to_string();
                let obj_name = export.object_name.clone();

                let key = (pkg_name.clone(), obj_name.clone());
                let loc = ExportLocation {
                    file_path: file_path.clone(),
                    export_index: i,
                    class_name: class_name.clone(),
                    serial_size: export.serial_size,
                };

                exports.insert(key.clone(), loc);
                by_class.entry(class_name).or_default().push(key);
                export_count += 1;
            }

            if package_count.is_multiple_of(500) {
                tracing::info!(
                    "Indexed {}/{} packages ({} exports so far)...",
                    package_count,
                    total_files,
                    export_count
                );
            }
        }

        Ok(Self {
            exports,
            by_class,
            package_count,
            export_count,
        })
    }

    /// Look up an export by package name and object name.
    pub fn find(&self, package_name: &str, object_name: &str) -> Option<&ExportLocation> {
        self.exports
            .get(&(package_name.to_string(), object_name.to_string()))
    }

    /// Find all exports of a given class.
    pub fn find_by_class(&self, class_name: &str) -> &[(String, String)] {
        self.by_class
            .get(class_name)
            .map(|v| v.as_slice())
            .unwrap_or(&[])
    }

    /// Save the index to a bincode file for fast subsequent loading.
    ///
    /// Writes the bincode 1.x on-disk format — see [`CACHE_CONFIG`].
    pub fn save(&self, path: &Path) -> Result<()> {
        let data = bincode::serde::encode_to_vec(self, CACHE_CONFIG)
            .map_err(|e| ObjectError::InvalidData(format!("bincode serialize: {e}")))?;
        std::fs::write(path, data)?;
        Ok(())
    }

    /// Load the index from a previously saved bincode file.
    ///
    /// Reads caches written by this crate both before and after the bincode
    /// 1.x -> 2.x bump; the wire format is identical.
    pub fn load(path: &Path) -> Result<Self> {
        let data = std::fs::read(path)?;
        // Trailing bytes past the struct are ignored, matching the tolerance of
        // the bincode 1.x `deserialize` call this replaced.
        bincode::serde::decode_from_slice(&data, CACHE_CONFIG)
            .map(|(index, _bytes_read)| index)
            .map_err(|e| ObjectError::InvalidData(format!("bincode deserialize: {e}")))
    }
}

/// Recursively collect all `.upk` and `.umap` files under a directory.
fn collect_package_files(dir: &Path, files: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_package_files(&path, files);
        } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            if ext.eq_ignore_ascii_case("upk") || ext.eq_ignore_ascii_case("umap") {
                files.push(path);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Bytes emitted by **actual bincode 1.3.3** `bincode::serialize()` — the
    /// exact call `save` used before the 2.x bump — for the index built by
    /// [`fixture_index`].
    ///
    /// Generated once by a throwaway crate pinned to `bincode = "=1.3.3"` with
    /// the `PackageIndex`/`ExportLocation` definitions copied verbatim. This is
    /// the ground truth that makes the "legacy config is 1.x-compatible" claim
    /// evidence rather than assumption.
    #[rustfmt::skip]
    const BINCODE_1X_FIXTURE: &[u8] = &[
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x53, 0x47, 0x57, 0x43, 0x61, 0x73, 0x74, 0x6c,
        0x65, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x43, 0x65, 0x6c,
        0x6c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x68, 0x5f, 0x30,
        0x31, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x43, 0x6f, 0x6f,
        0x6b, 0x65, 0x64, 0x50, 0x43, 0x2f, 0x4d, 0x61, 0x70, 0x73, 0x2f, 0x53,
        0x47, 0x57, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x2e, 0x75, 0x70, 0x6b,
        0x92, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4d, 0x65,
        0x73, 0x68, 0x39, 0x05, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x53, 0x74,
        0x61, 0x74, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x68, 0x01, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x53, 0x47, 0x57, 0x43, 0x61, 0x73, 0x74, 0x6c, 0x65, 0x10, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x43, 0x65, 0x6c, 0x6c, 0x62, 0x6c, 0x6f,
        0x63, 0x6b, 0x4d, 0x65, 0x73, 0x68, 0x5f, 0x30, 0x31, 0x88, 0x13, 0x00,
        0x00, 0x06, 0x12, 0x0f, 0x00,
    ];

    /// The index the fixture bytes encode.
    ///
    /// Deliberately holds exactly ONE entry per `HashMap`: map iteration order
    /// is not deterministic, so a multi-entry index has no single canonical
    /// byte encoding and could not be compared against a fixture at all.
    fn fixture_index() -> PackageIndex {
        let key = ("SGWCastle".to_string(), "CellblockMesh_01".to_string());

        let mut exports = HashMap::new();
        exports.insert(
            key.clone(),
            ExportLocation {
                file_path: PathBuf::from("CookedPC/Maps/SGWCastle.upk"),
                export_index: 4242,
                class_name: "StaticMesh".to_string(),
                serial_size: 1337,
            },
        );

        let mut by_class: HashMap<String, Vec<(String, String)>> = HashMap::new();
        by_class.insert("StaticMesh".to_string(), vec![key]);

        PackageIndex {
            exports,
            by_class,
            package_count: 5000,
            export_count: 987_654,
        }
    }

    fn assert_matches_fixture(index: &PackageIndex) {
        assert_eq!(index.package_count, 5000);
        assert_eq!(index.export_count, 987_654);

        let loc = index
            .find("SGWCastle", "CellblockMesh_01")
            .expect("fixture export present");
        assert_eq!(loc.file_path, PathBuf::from("CookedPC/Maps/SGWCastle.upk"));
        assert_eq!(loc.export_index, 4242);
        assert_eq!(loc.class_name, "StaticMesh");
        assert_eq!(loc.serial_size, 1337);

        assert_eq!(
            index.find_by_class("StaticMesh"),
            &[("SGWCastle".to_string(), "CellblockMesh_01".to_string())]
        );
    }

    /// Guards the on-disk format across the bincode 1.x -> 2.x bump, in BOTH
    /// directions:
    ///
    /// - read: index caches already sitting on developers' disks (written by
    ///   bincode 1.3.3) still decode.
    /// - write: bytes this crate emits today are still byte-identical to what
    ///   1.3.3 emitted, so a cache is readable by either version.
    ///
    /// Switching `CACHE_CONFIG` to `config::standard()` fails this — standard
    /// varint-encodes integers where 1.x used fixed width. Measured, not
    /// assumed: under `standard()` the decode does **not** error, it returns a
    /// garbage `PackageIndex` having consumed 10 of the fixture's 197 bytes.
    /// That silence is why the `consumed == len` assertion below is load-
    /// bearing, and why `save_then_load_round_trips_through_a_file` — which
    /// still passes under `standard()`, since it writes and reads with the same
    /// wrong config — cannot be the only guard here.
    #[test]
    fn index_cache_is_bincode_1x_compatible() {
        // Read direction: decode genuine bincode 1.3.3 output.
        let (decoded, consumed): (PackageIndex, usize) =
            bincode::serde::decode_from_slice(BINCODE_1X_FIXTURE, CACHE_CONFIG)
                .expect("bincode 1.3.3 output must decode under the legacy config");
        assert_eq!(consumed, BINCODE_1X_FIXTURE.len(), "no trailing bytes");
        assert_matches_fixture(&decoded);

        // Write direction: re-encoding must reproduce the 1.3.3 bytes exactly.
        let encoded = bincode::serde::encode_to_vec(fixture_index(), CACHE_CONFIG)
            .expect("encode under the legacy config");
        assert_eq!(
            encoded, BINCODE_1X_FIXTURE,
            "on-disk index format drifted from bincode 1.x"
        );
    }

    /// The plain save-then-load guard: a multi-entry index survives a trip
    /// through a real file on disk unchanged.
    #[test]
    fn save_then_load_round_trips_through_a_file() {
        let mut original = fixture_index();
        // Grow past the single-entry fixture so map/vec framing is exercised
        // with more than one element (byte order is unconstrained here, which
        // is why this test compares values rather than bytes).
        for i in 0..64u32 {
            let key = (format!("Pkg{i}"), format!("Obj{i}"));
            original.exports.insert(
                key.clone(),
                ExportLocation {
                    file_path: PathBuf::from(format!("CookedPC/Pkg{i}.upk")),
                    export_index: i as usize * 7,
                    class_name: "Texture2D".to_string(),
                    serial_size: -(i as i32), // negative: pins signed encoding
                },
            );
            original
                .by_class
                .entry("Texture2D".to_string())
                .or_default()
                .push(key);
        }

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("package_index.bin");

        original.save(&path).expect("save");
        let loaded = PackageIndex::load(&path).expect("load");

        assert_eq!(loaded.package_count, original.package_count);
        assert_eq!(loaded.export_count, original.export_count);
        assert_eq!(loaded.exports.len(), original.exports.len());

        for (key, want) in &original.exports {
            let got = loaded
                .find(&key.0, &key.1)
                .unwrap_or_else(|| panic!("missing export {key:?} after round-trip"));
            assert_eq!(got.file_path, want.file_path);
            assert_eq!(got.export_index, want.export_index);
            assert_eq!(got.class_name, want.class_name);
            assert_eq!(got.serial_size, want.serial_size);
        }

        let mut want_textures = original.find_by_class("Texture2D").to_vec();
        let mut got_textures = loaded.find_by_class("Texture2D").to_vec();
        want_textures.sort();
        got_textures.sort();
        assert_eq!(got_textures, want_textures);

        assert_matches_fixture(&loaded);
    }

    /// A truncated cache — the realistic damage shape, an interrupted write —
    /// must surface as a clean `ObjectError`, not a panic. The two
    /// navmesh-extractor tests that opportunistically load an index off the
    /// repo root depend on `load` returning `Err` so they can skip.
    ///
    /// Note this only covers *truncation*. `CACHE_CONFIG` inherits bincode
    /// 1.x's absence of a decode size limit, so a cache corrupted into a bogus
    /// length prefix still aborts on allocation rather than erroring. That is
    /// unchanged from the pre-bump behaviour and deliberately not "fixed" here
    /// — adding `with_limit` would be a behaviour change riding along on a
    /// dependency bump.
    #[test]
    fn load_of_a_truncated_cache_is_an_error_not_a_panic() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("package_index.bin");
        // Valid header, cut off mid-record.
        std::fs::write(&path, &BINCODE_1X_FIXTURE[..64]).expect("write");

        // `let Err(..) else` rather than `expect_err` so this test does not
        // force a `Debug` bound onto the public `PackageIndex` type.
        let Err(err) = PackageIndex::load(&path) else {
            panic!("truncated cache must error");
        };
        assert!(
            matches!(err, ObjectError::InvalidData(_)),
            "expected InvalidData, got {err:?}"
        );
    }
}
