#pragma once

namespace Mercury
{

enum unified_opcode
{
	FES_REGISTER_SHARD = 0x10,
	FES_REGISTER_SHARD_ACK = 0x11,
	FES_UPDATE_SHARD_STATUS = 0x12,
	FES_LOGON_NOTIFICATION = 0x13,
	FES_LOGOFF_NOTIFICATION = 0x14,
	FES_KICK_PLAYER = 0x15,
	FES_KICK_PLAYER_ACK = 0x16,
	FES_REQUEST_LOGON = 0x17,
	FES_LOGON_ACK = 0x18,
	FES_LOGON_NAK = 0x19,

	GENERIC_KEEPALIVE = 0xFF
};

}
