# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common.defs.Def import DefMgr
from common import Constants

class GivingTheWallsEars(Script):
	n1_var_Player = None
	n7_var_Player = None
	n8_var_Player = None
	def n9_trigger_In(self):
		if self.n9_var_Player is None or not 2819:
			return
		if not 0:
			added = self.n9_var_Player.inventory.pickedUpItem(2819, 1 or 1)
		else:
			added = self.n9_var_Player.inventory.addItem(0, 2819, 1 or 1)
		self.n9_var_Player.inventory.flushUpdates()
		if added:
			dialogSet = DefMgr.get('interaction_set_map', 3129)
			if self.n10_var_Player is not None and dialogSet is not None and self.n10_var_Player.removeDialog(163, dialogSet):
				pass
			self.n11_var_Player.missions.advance(742, 2503)
		else:
			pass

	n9_var_Player = None
	n10_var_Player = None
	n11_var_Player = None
	n12_var_Player = None
	def n13_trigger_Step(self):
		self.n13_var_Player.missions.advance(742, 2504)
		self.n16_var_Player.displayDialog(None, 2637)
		dialogSet = DefMgr.get('interaction_set_map', 1000000)
		if self.n14_var_Player is not None and dialogSet is not None and self.n14_var_Player.addDialog(164, dialogSet, 742 or None):
			pass

	n13_var_Player = None
	n14_var_Player = None
	n16_var_Player = None
	n17_var_Player = None
	def n17_propagator_Player(self):
		self.n25_var_Player = self.n17_var_Player
		self.n26_var_Player = self.n17_var_Player
		self.n27_var_Player = self.n17_var_Player
		self.n31_var_Player = self.n17_var_Player
		self.n32_var_Player = self.n17_var_Player
		self.n50_var_Player = self.n17_var_Player
		self.n49_var_Player = self.n17_var_Player
		self.n47_var_Player = self.n17_var_Player

	n17_var_Target = None
	def n18_trigger_In(self):
		entity = self.n18_var_Entity
		if entity is not None:
			if entity.tag is not None:
				self.n18_var_Tag = entity.tag
				self.n19_var_A = self.n18_var_Tag
				self.n20_var_A = self.n18_var_Tag
				self.n21_var_A = self.n18_var_Tag
			self.n19_trigger_In()
			self.n20_trigger_In()
			self.n21_trigger_In()

	n18_var_Entity = None
	n18_var_Tag = None
	def n19_trigger_In(self):
		if self.n19_var_A == self.n19_var_B:
			status = self.n50_var_Player.missions.getObjectiveStatus(742, 2913)
			if status == Constants.MISSION_Active:
				self.n25_var_Player.missions.completeObjective(742, 2913)
				self.n28_trigger_In()

	n19_var_A = None
	n19_var_B = None
	def n20_trigger_In(self):
		if self.n20_var_A == self.n20_var_B:
			status = self.n49_var_Player.missions.getObjectiveStatus(742, 2914)
			if status == Constants.MISSION_Active:
				self.n26_var_Player.missions.completeObjective(742, 2914)
				self.n28_trigger_In()

	n20_var_A = None
	n20_var_B = None
	def n21_trigger_In(self):
		if self.n21_var_A == self.n21_var_B:
			status = self.n47_var_Player.missions.getObjectiveStatus(742, 2915)
			if status == Constants.MISSION_Active:
				self.n27_var_Player.missions.completeObjective(742, 2915)
				self.n28_trigger_In()

	n21_var_A = None
	n21_var_B = None
	n22_var_Set = None
	n22_var_Value = None
	n23_var_Set = None
	n23_var_Value = None
	n24_var_Set = None
	n24_var_Value = None
	n25_var_Player = None
	n26_var_Player = None
	n27_var_Player = None
	def n28_trigger_Set(self):
		self.n28_lvar_Value = None
		a = 3
		if self.n28_lvar_Value == a:
			self.n28_propagator_Value_equal_equal__A()
		if self.n28_lvar_Value < a:
			self.n30_trigger_In()

	def n28_trigger_In(self):
		self.n28_lvar_Value += 1
		a = 3
		if self.n28_lvar_Value == a:
			self.n28_propagator_Value_equal_equal__A()
		if self.n28_lvar_Value < a:
			self.n30_trigger_In()

	def n28_propagator_Value_equal_equal__A(self):
		self.n30_trigger_In()
		self.n31_var_Player.missions.advance(742, 2505)
		dialogSet = DefMgr.get('interaction_set_map', 3130)
		if self.n32_var_Player is not None and dialogSet is not None and self.n32_var_Player.addDialog(43, dialogSet, 742 or None):
			pass

	def n30_trigger_In(self):
		if None and (2820 or None):
			removed = False
			if not removed and 2820:
				removed = None.inventory.removeItemByDesign(2820, 1, False)
			None.inventory.flushUpdates()
			if removed:
				pass

	n31_var_Player = None
	n32_var_Player = None
	n33_var_Player = None
	def n34_propagator_Successful(self):
		self.n40_trigger_In()
		self.n41_var_Player.missions.advance(742, 2506)
		dialogSet = DefMgr.get('interaction_set_map', 3131)
		if None is not None and dialogSet is not None and None.addDialog(53, dialogSet, 742 or None):
			pass

	n34_var_Player = None
	def n40_trigger_In(self):
		if self.n40_var_Player is None or not 2864:
			return
		if not 0:
			added = self.n40_var_Player.inventory.pickedUpItem(2864, 1 or 1)
		else:
			added = self.n40_var_Player.inventory.addItem(0, 2864, 1 or 1)
		self.n40_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n40_var_Player = None
	n41_var_Player = None
	n43_var_Player = None
	def n44_trigger_In(self):
		if self.n44_var_Player and (2864 or None):
			removed = False
			if not removed and 2864:
				removed = self.n44_var_Player.inventory.removeItemByDesign(2864, 1, False)
			self.n44_var_Player.inventory.flushUpdates()
			if removed:
				pass

	n44_var_Player = None
	n45_var_Player = None
	n47_var_Player = None
	n49_var_Player = None
	n50_var_Player = None
	def n52_trigger_In(self):
		if self.n52_var_Player is None or not 2820:
			return
		if not 0:
			added = self.n52_var_Player.inventory.pickedUpItem(2820, 3 or 1)
		else:
			added = self.n52_var_Player.inventory.addItem(0, 2820, 3 or 1)
		self.n52_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n52_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n22_var_Value = 'FirstBug'
		self.n19_var_B = self.n22_var_Value
		self.n23_var_Value = 'SecondBug'
		self.n20_var_B = self.n23_var_Value
		self.n24_var_Value = 'ThirdBug'
		self.n21_var_B = self.n24_var_Value
		self.n28_lvar_Value = 0
		def acceptedCb(args):
			self.n1_var_Player = self.owner
			self.n7_var_Player = self.n1_var_Player
			self.n52_var_Player = self.n1_var_Player
			dialogSet = DefMgr.get('interaction_set_map', 3129)
			if self.n7_var_Player is not None and dialogSet is not None and self.n7_var_Player.addDialog(163, dialogSet, 742 or None):
				pass
			self.n52_trigger_In()
			return True
		self.n1_lvar_AcceptedId = self.owner.subscribe("mission.accepted::" + str(742), acceptedCb, once = False)
		def dialogChoiceCb(args):
			self.n8_var_Player = args['player']
			self.n9_var_Player = self.n8_var_Player
			self.n10_var_Player = self.n8_var_Player
			self.n11_var_Player = self.n8_var_Player
			self.n9_trigger_In()
			return True
		self.n8_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2638), dialogChoiceCb, once = False)
		def itemCb(params):
			self.n12_var_Player = params['player']
			self.n13_var_Player = self.n12_var_Player
			self.n16_var_Player = self.n12_var_Player
			self.n14_var_Player = self.n12_var_Player
			self.n13_trigger_Step()
			return True
		self.n12_lvar_HandlerId = self.owner.subscribe('item.use::' + str(2819), itemCb, once = True)
		def dialogSetCb(args):
			self.n17_var_Player = args['player']
			self.n17_propagator_Player()
			self.n17_var_Target = args['target']
			self.n18_var_Entity = self.n17_var_Target
			self.n18_trigger_In()
			return True
		self.n17_lvar_SubscriptionId = self.owner.subscribe("dialog_set.open::" + str(1000000), dialogSetCb, once = False)
		def dialogChoiceCb(args):
			self.n33_var_Player = args['player']
			self.n34_var_Player = self.n33_var_Player
			self.n40_var_Player = self.n33_var_Player
			self.n41_var_Player = self.n33_var_Player
			dialogSet = DefMgr.get('interaction_set_map', 3130)
			if self.n34_var_Player is not None and dialogSet is not None and self.n34_var_Player.removeDialog(43, dialogSet):
				self.n34_propagator_Successful()
			return True
		self.n33_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2639), dialogChoiceCb, once = False)
		def dialogChoiceCb(args):
			self.n43_var_Player = args['player']
			self.n44_var_Player = self.n43_var_Player
			self.n45_var_Player = self.n43_var_Player
			self.n44_trigger_In()
			self.n45_var_Player.missions.complete(742)
			return True
		self.n43_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2640), dialogChoiceCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_AcceptedId)
		self.owner.unsubscribe(self.n8_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n12_lvar_HandlerId)
		self.owner.unsubscribe(self.n17_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n33_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n43_lvar_SubscriptionId)

