# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants
import Atrea
from common.defs.Def import DefMgr
from cell.Minigame import Minigame
from common.Config import Config

class Castle(Script):
	n1_var_Player = None
	n4_var_Invoker = None
	n5_var_Player = None
	n6_var_Invoker = None
	n7_var_Player = None
	n11_var_Player = None
	def n13_trigger_In(self):
		self.n13_var_Entity = None
		if None is not None:
			self.n13_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'Castle_SgtGerschon'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n13_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n13_var_Entity = entity
						break
			else:
				self.n13_var_Entity = None
		if self.n13_var_Entity is not None:
			dialogSet = DefMgr.get('interaction_set_map', 3062)
			if self.n15_var_Player is not None and dialogSet is not None and self.n15_var_Player.addDialog(149, dialogSet, 0 or None):
				pass

	n13_var_Entity = None
	n15_var_Player = None
	n18_var_Player = None
	n19_var_Player = None
	n20_var_Player = None
	def n21_trigger_In(self):
		self.n21_var_Entity = None
		if None is not None:
			self.n21_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'Castle_Coppleman'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n21_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n21_var_Entity = entity
						break
			else:
				self.n21_var_Entity = None
		if self.n21_var_Entity is not None:
			dialogSet = DefMgr.get('interaction_set_map', 3062)
			if self.n22_var_Player is not None and dialogSet is not None and self.n22_var_Player.addDialog(48, dialogSet, 0 or None):
				pass

	n21_var_Entity = None
	n22_var_Player = None
	n27_var_Player = None
	n27_var_Target = None
	n29_var_Player = None
	n30_var_Player = None
	n30_var_NPC = None
	def n31_propagator_Out(self):
		status = self.n32_var_Player.missions.getStepStatus(701, 2399)
		if status == Constants.MISSION_Active:
			self.n33_var_Player.displayDialog(self.n33_var_NPC, 2574)
		status = self.n36_var_Player.missions.getStepStatus(701, 2400)
		if status == Constants.MISSION_Active:
			self.n37_trigger_In()

	n31_var_Player = None
	n31_var_Target = None
	n32_var_Player = None
	n33_var_Player = None
	n33_var_NPC = None
	n34_var_Player = None
	def n34_propagator_Player(self):
		self.n35_var_Player = self.n34_var_Player
		self.n38_var_Player = self.n34_var_Player
		self.n40_var_Player = self.n34_var_Player
		self.n41_var_Player = self.n34_var_Player
		self.n37_var_Player = self.n34_var_Player

	n35_var_Player = None
	n36_var_Player = None
	def n37_trigger_In(self):
		def mgHandler(self, result):
			if result == Constants.MINIGAME_RESULT_Victory:
				self.n37_propagator_Won()
			elif result == Constants.MINIGAME_RESULT_Defeat:
				pass
			else:
				pass
		gameIds = [k for k, v in Config.MINIGAME_NAMES.items() if v == 'Livewire']
		assert(len(gameIds) == 1)
		minigame = Minigame('', 1, gameIds[0], 1, 0xffff, lambda mg, rc: mgHandler(self, rc))
		if not self.n37_var_Player.requestStartMinigame(minigame):
			pass

	def n37_propagator_Won(self):
		dialogSet = DefMgr.get('interaction_set_map', 3062)
		if self.n38_var_Player is not None and dialogSet is not None and self.n38_var_Player.removeDialog(48, dialogSet):
			pass
		self.n40_var_Player.displayDialog(None, 2575)
		self.n41_var_Player.missions.advance(701, 2401)

	n37_var_Player = None
	n38_var_Player = None
	n40_var_Player = None
	n41_var_Player = None
	n42_var_Invoker = None
	n43_var_Player = None
	def n44_trigger_In(self):
		tpl = DefMgr.get('template', 48)
		if tpl and self.n44_var_Location:
			entity = self.owner.space.createEntity(tpl, self.n44_var_Location)
			self.n44_var_Entity = entity
			self.n51_var_Entity = self.n44_var_Entity
			self.n51_trigger_In()

	n44_var_Entity = None
	n44_var_Location = None
	n45_var_Set = None
	n45_var_Value = None
	def n46_trigger_In(self):
		ent = self.n46_var_Entity
		if ent is None:
			return
		if self.n46_var_Visible is not None:
			ent.setVisible(self.n46_var_Visible)

	n46_var_Entity = None
	n46_var_Visible = None
	n47_var_Set = None
	n47_var_Value = None
	def n51_trigger_In(self):
		if self.n51_var_Entity is not None:
			def waypointCb():
				dialogSet = DefMgr.get('interaction_set_map', 3062)
				if self.n55_var_Player is not None and dialogSet is not None and self.n55_var_Player.addDialog(48, dialogSet, 0 or None):
					pass
			self.n51_var_Entity.addWaypoint(self.n51_var_Position, waypointCb)

	n51_var_Entity = None
	n51_var_Position = None
	n52_var_Set = None
	n52_var_Value = None
	n54_var_Player = None
	n55_var_Player = None
	def n56_trigger_In(self):
		self.n56_var_Entity = None
		if None is not None:
			self.n56_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'Castle_Coppleman'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n56_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n56_var_Entity = entity
						break
			else:
				self.n56_var_Entity = None
		self.n46_var_Entity = self.n56_var_Entity
		if self.n56_var_Entity is not None:
			self.n46_trigger_In()

	n56_var_Entity = None
	n58_var_Player = None
	n59_var_Player = None
	n60_var_Player = None
	n61_var_Player = None
	def n65_propagator_Out(self):
		status = self.n58_var_Player.missions.getStepStatus(701, 2401)
		if status == Constants.MISSION_Active:
			self.n59_var_Player.missions.advance(701, 2421)
		status = self.n60_var_Player.missions.getStepStatus(701, 2421)
		if status == Constants.MISSION_Active:
			self.n61_var_Player.displayDialog(None, 2576)

	n65_var_Player = None
	n66_var_Player = None
	n67_var_Player = None
	n68_var_Player = None
	n69_var_Player = None
	def n71_trigger_In(self):
		status = self.n71_var_Player.missions.getStepStatus(701, 2421)
		if status == Constants.MISSION_Active:
			dialogSet = DefMgr.get('interaction_set_map', 3062)
			if self.n67_var_Player is not None and dialogSet is not None and self.n67_var_Player.removeDialog(48, dialogSet):
				self.n68_var_Player.missions.complete(701)
				self.n69_var_Player.missions.accept(702)

	n71_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n45_var_Value = self.str2vec('354.419,70.272,952.801')
		self.n44_var_Location = self.n45_var_Value
		self.n47_var_Value = False
		self.n46_var_Visible = self.n47_var_Value
		self.n52_var_Value = self.str2vec('358.809,70.156,889.724')
		self.n51_var_Position = self.n52_var_Value
		def loaded(args):
			self.n1_var_Player = self.owner
			self.n11_var_Player = self.n1_var_Player
			self.n15_var_Player = self.n1_var_Player
			status = self.n11_var_Player.missions.getMissionStatus(701)
			if status == Constants.MISSION_Not_Active:
				self.n13_trigger_In()
		self.n1_lvar_SubscriptionId = self.owner.subscribe("player.loaded", loaded)
		def regionCb(args):
			self.n4_var_Invoker = args['entity']
			self.n5_var_Player = self.n4_var_Invoker
			if args['entering']:
				if self.n5_var_Player:
					self.n5_var_Player.client.onSystemCommunication(11, 5189, '', [])
			else:
				pass
		self.n4_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle.ThroneRoom', regionCb, once = False)
		def regionCb(args):
			self.n6_var_Invoker = args['entity']
			self.n7_var_Player = self.n6_var_Invoker
			if args['entering']:
				if self.n7_var_Player:
					self.n7_var_Player.client.onSystemCommunication(11, 5190, '', [])
			else:
				pass
		self.n6_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle.CastleFrontCourtyard', regionCb, once = False)
		def dialogChoiceCb(args):
			self.n18_var_Player = args['player']
			self.n19_var_Player = self.n18_var_Player
			self.n20_var_Player = self.n18_var_Player
			self.n22_var_Player = self.n18_var_Player
			self.n19_var_Player.missions.accept(701)
			dialogSet = DefMgr.get('interaction_set_map', 3062)
			if self.n20_var_Player is not None and dialogSet is not None and self.n20_var_Player.removeDialog(149, dialogSet):
				self.n21_trigger_In()
			return True
		self.n18_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2573), dialogChoiceCb, once = False)
		def interactCb(args):
			self.n27_var_Target = args['target']
			self.n30_var_NPC = self.n27_var_Target
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n27_var_Player = self.owner
			self.n29_var_Player = self.n27_var_Player
			self.n30_var_Player = self.n27_var_Player
			status = self.n29_var_Player.missions.getStepStatus(701, 2399)
			if status == Constants.MISSION_Not_Active:
				self.n30_var_Player.displayDialog(self.n30_var_NPC, 2573)
			return True
		self.n27_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Castle_SgtGerschon', interactCb, once = False)
		def interactCb(args):
			self.n31_var_Target = args['target']
			self.n33_var_NPC = self.n31_var_Target
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n31_var_Player = self.owner
			self.n32_var_Player = self.n31_var_Player
			self.n33_var_Player = self.n31_var_Player
			self.n36_var_Player = self.n31_var_Player
			self.n31_propagator_Out()
			return True
		self.n31_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Castle_Coppleman', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n34_var_Player = args['player']
			self.n34_propagator_Player()
			self.n35_var_Player.missions.advance(701, 2400)
			return True
		self.n34_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2574), dialogChoiceCb, once = False)
		def regionCb(args):
			self.n42_var_Invoker = args['entity']
			self.n43_var_Player = self.n42_var_Invoker
			if args['entering']:
				if self.n43_var_Player:
					self.n43_var_Player.client.onSystemCommunication(11, 5188, '', [])
			else:
				pass
		self.n42_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle.Infirmary', regionCb, once = False)
		def dialogChoiceCb(args):
			self.n54_var_Player = args['player']
			self.n55_var_Player = self.n54_var_Player
			self.n44_trigger_In()
			self.n56_trigger_In()
			return True
		self.n54_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2575), dialogChoiceCb, once = False)
		def dialogSetCb(args):
			self.n65_var_Player = args['player']
			self.n58_var_Player = self.n65_var_Player
			self.n59_var_Player = self.n65_var_Player
			self.n60_var_Player = self.n65_var_Player
			self.n61_var_Player = self.n65_var_Player
			self.n65_propagator_Out()
			return True
		self.n65_lvar_SubscriptionId = self.owner.subscribe("dialog_set.open::" + str(3062), dialogSetCb, once = False)
		def dialogChoiceCb(args):
			self.n66_var_Player = args['player']
			self.n68_var_Player = self.n66_var_Player
			self.n69_var_Player = self.n66_var_Player
			self.n71_var_Player = self.n66_var_Player
			self.n67_var_Player = self.n66_var_Player
			self.n71_trigger_In()
			return True
		self.n66_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2576), dialogChoiceCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_SubscriptionId)
		if self.n4_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n4_lvar_SubscriptionId)
		if self.n6_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n6_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n18_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n27_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n31_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n34_lvar_SubscriptionId)
		if self.n42_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n42_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n54_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n65_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n66_lvar_SubscriptionId)

