# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants
from common.defs.Def import DefMgr
import Atrea

class Castle_CellBlock(Script):
	n13_var_Player = None
	def n13_propagator_Player(self):
		self.n81_var_Player = self.n13_var_Player
		self.n82_var_Player = self.n13_var_Player
		self.n83_var_Player = self.n13_var_Player
		self.n83_var_NPC = self.n13_var_Player
		self.n112_var_Actor = self.n13_var_Player
		self.n112_var_Target = self.n13_var_Player
		self.n182_var_Player = self.n13_var_Player
		self.n229_var_Source = self.n13_var_Player
		self.n229_var_Target = self.n13_var_Player

	def n81_trigger_In(self):
		status = self.n81_var_Player.missions.getMissionStatus(622)
		if status == Constants.MISSION_Not_Active:
			self.n82_trigger_Accept()
		if status == Constants.MISSION_Completed:
			self.n229_trigger_In()

	n81_var_Player = None
	def n82_trigger_Accept(self):
		self.n82_var_Player.missions.accept(622)
		self.n83_var_Player.displayDialog(self.n83_var_NPC, 2982)
		dialogSet = DefMgr.get('interaction_set_map', 5229)
		if self.n182_var_Player is not None and dialogSet is not None and self.n182_var_Player.addDialog(14, dialogSet, 622 or None):
			pass

	def n82_trigger_Display_Rewards(self):
		self.n82_var_Player.missions.displayRewards(622)
		self.n83_var_Player.displayDialog(self.n83_var_NPC, 2982)
		dialogSet = DefMgr.get('interaction_set_map', 5229)
		if self.n182_var_Player is not None and dialogSet is not None and self.n182_var_Player.addDialog(14, dialogSet, 622 or None):
			pass

	def n82_trigger_Complete(self):
		self.n82_var_Player.missions.complete(622)
		self.n83_var_Player.displayDialog(self.n83_var_NPC, 2982)
		dialogSet = DefMgr.get('interaction_set_map', 5229)
		if self.n182_var_Player is not None and dialogSet is not None and self.n182_var_Player.addDialog(14, dialogSet, 622 or None):
			pass

	def n82_trigger_Fail(self):
		self.n82_var_Player.missions.fail(622)
		self.n83_var_Player.displayDialog(self.n83_var_NPC, 2982)
		dialogSet = DefMgr.get('interaction_set_map', 5229)
		if self.n182_var_Player is not None and dialogSet is not None and self.n182_var_Player.addDialog(14, dialogSet, 622 or None):
			pass

	def n82_trigger_Abandon(self):
		self.n82_var_Player.missions.abandon(622)
		self.n83_var_Player.displayDialog(self.n83_var_NPC, 2982)
		dialogSet = DefMgr.get('interaction_set_map', 5229)
		if self.n182_var_Player is not None and dialogSet is not None and self.n182_var_Player.addDialog(14, dialogSet, 622 or None):
			pass

	n82_var_Player = None
	n83_var_Player = None
	n83_var_NPC = None
	def n112_trigger_In(self):
		id = 1372
		ability = DefMgr.get('ability', id)
		if ability and self.n112_var_Actor and self.n112_var_Actor.abilities.launchAbility(ability, targetId = self.n112_var_Target.entityId if self.n112_var_Target else None,
			targetLoc = None, autoCycle = False, isEntityAbility = False):
			pass

	n112_var_Actor = None
	n112_var_Target = None
	n116_var_Invoker = None
	def n117_trigger_In(self):
		self.n117_var_Entity = None
		if None is not None:
			self.n117_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'ArmYourself_NIDGuard'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n117_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n117_var_Entity = entity
						break
			else:
				self.n117_var_Entity = None
		self.n118_var_Entity = self.n117_var_Entity
		self.n120_var_Entity = self.n117_var_Entity
		self.n180_var_Target = self.n117_var_Entity
		if self.n117_var_Entity is not None:
			if self.n118_var_Entity is not None:
				self.n118_var_Entity.addWaypoint(self.n118_var_Position, lambda: None)
			self.n120_trigger_In()

	n117_var_Entity = None
	n118_var_Entity = None
	n118_var_Position = None
	n119_var_Set = None
	n119_var_Value = None
	def n120_trigger_In(self):
		ent = self.n120_var_Entity
		if ent is None:
			return
		if self.n120_var_Aggression is not None:
			ent.setAggression(self.n120_var_Aggression)
		target = self.n180_var_Target
		instigator = self.n180_var_Instigator
		if target is not None and instigator is not None and hasattr(target, 'threatGenerated'):
			target.threatGenerated(instigator.entityId, 1000)

	n120_var_Entity = None
	n120_var_Aggression = None
	n121_var_Set = None
	n121_var_Value = None
	n123_var_Invoker = None
	def n123_propagator_Invoker(self):
		self.n124_var_Player = self.n123_var_Invoker
		self.n125_var_Player = self.n123_var_Invoker
		self.n172_var_Entity = self.n123_var_Invoker
		self.n176_var_Player = self.n123_var_Invoker
		self.n179_var_Player = self.n123_var_Invoker

	n124_var_Player = None
	n125_var_Player = None
	n128_var_Invoker = None
	n129_var_Player = None
	n130_var_Invoker = None
	n131_var_Player = None
	n135_var_Invoker = None
	n136_var_Player = None
	n141_var_Player = None
	n142_var_Player = None
	def n143_trigger_In(self):
		self.n143_var_Entity = None
		if None is not None:
			self.n143_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'Preparation_ColMarsh'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n143_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n143_var_Entity = entity
						break
			else:
				self.n143_var_Entity = None
		self.n144_var_Entity = self.n143_var_Entity
		if self.n143_var_Entity is not None:
			entity = self.n144_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 8388608)

	n143_var_Entity = None
	n144_var_Entity = None
	n146_var_Player = None
	n147_var_Player = None
	n149_var_Player = None
	n151_var_Player = None
	n153_var_Player = None
	n154_var_Player = None
	n155_var_Invoker = None
	n156_var_Player = None
	n157_var_Invoker = None
	n158_var_Player = None
	n159_var_Invoker = None
	n160_var_Player = None
	def n161_trigger_In(self):
		entity = self.n161_var_Entity
		if entity is not None:
			self.n161_var_Archetype = entity.archetype
			self.n162_var_Set = self.n161_var_Archetype
			self.n162_var_Value = self.n162_var_Set
			self.n163_var_A = self.n162_var_Value
			self.n165_var_A = self.n162_var_Value
			if self.n163_var_A == self.n163_var_B:
				self.n167_var_Player.displayDialog(None, 5022)
			if self.n165_var_A < self.n165_var_B:
				self.n151_var_Player.displayDialog(None, 4001)

	n161_var_Entity = None
	n161_var_Archetype = None
	n162_var_Set = None
	n162_var_Value = None
	n163_var_A = None
	n163_var_B = None
	n164_var_Set = None
	n164_var_Value = None
	n165_var_A = None
	n165_var_B = None
	n166_var_Set = None
	n166_var_Value = None
	n167_var_Player = None
	n168_var_Player = None
	def n172_trigger_In(self):
		entity = self.n172_var_Entity
		if entity is not None:
			self.n172_var_Archetype = entity.archetype
			self.n173_var_Set = self.n172_var_Archetype
			self.n173_var_Value = self.n173_var_Set
			self.n174_var_A = self.n173_var_Value
			self.n177_var_A = self.n173_var_Value
			self.n172_propagator_Successful()

	def n172_propagator_Successful(self):
		if self.n174_var_A == self.n174_var_B:
			dialogSet = DefMgr.get('interaction_set_map', 5866)
			if self.n176_var_Player is not None and dialogSet is not None and self.n176_var_Player.addDialog(17, dialogSet, 0 or None):
				pass
		if self.n177_var_A < self.n177_var_B:
			dialogSet = DefMgr.get('interaction_set_map', 2794)
			if self.n179_var_Player is not None and dialogSet is not None and self.n179_var_Player.addDialog(17, dialogSet, 0 or None):
				pass

	n172_var_Entity = None
	n172_var_Archetype = None
	n173_var_Set = None
	n173_var_Value = None
	n174_var_A = None
	n174_var_B = None
	n175_var_Set = None
	n175_var_Value = None
	n176_var_Player = None
	n177_var_A = None
	n177_var_B = None
	n178_var_Set = None
	n178_var_Value = None
	n179_var_Player = None
	n180_var_Target = None
	n180_var_Instigator = None
	n182_var_Player = None
	n187_var_Invoker = None
	def n188_trigger_In(self):
		status = self.n188_var_Player.missions.getMissionStatus(681)
		if status == Constants.MISSION_Completed:
			status = self.n190_var_Player.missions.getMissionStatus(682)
			if status == Constants.MISSION_Not_Active:
				self.n189_var_Player.missions.accept(682)

	n188_var_Player = None
	n189_var_Player = None
	n190_var_Player = None
	n211_var_Invoker = None
	def n213_trigger_In(self):
		status = self.n213_var_Player.missions.getMissionStatus(683)
		if status == Constants.MISSION_Completed:
			status = self.n214_var_Player.missions.getMissionStatus(684)
			if status == Constants.MISSION_Not_Active:
				self.n215_var_Player.missions.accept(684)

	n213_var_Player = None
	n214_var_Player = None
	n215_var_Player = None
	n220_var_Invoker = None
	def n221_trigger_In(self):
		status = self.n221_var_Player.missions.getMissionStatus(685)
		if status == Constants.MISSION_Completed:
			status = self.n222_var_Player.missions.getMissionStatus(686)
			if status == Constants.MISSION_Not_Active:
				self.n223_var_Player.missions.accept(686)

	n221_var_Player = None
	n222_var_Player = None
	n223_var_Player = None
	n225_var_Invoker = None
	n226_var_Player = None
	n227_var_Player = None
	def n228_trigger_In(self):
		status = self.n228_var_Player.missions.getMissionStatus(686)
		if status == Constants.MISSION_Completed:
			status = self.n226_var_Player.missions.getMissionStatus(687)
			if status == Constants.MISSION_Not_Active:
				self.n227_var_Player.missions.accept(687)

	n228_var_Player = None
	def n229_trigger_In(self):
		if self.n229_var_Source is not None and 10000 is not None:
			target = self.n229_var_Target
			targetId = target.entityId if target else None
			self.n229_var_Source.playSequence(10000, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n229_var_Source = None
	n229_var_Target = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n119_var_Value = self.str2vec('-296.715,68.511,-166.125')
		self.n118_var_Position = self.n119_var_Value
		self.n121_var_Value = 1
		self.n120_var_Aggression = self.n121_var_Value
		self.n162_var_Value = 0
		self.n163_var_A = self.n162_var_Value
		self.n165_var_A = self.n162_var_Value
		self.n164_var_Value = 8
		self.n163_var_B = self.n164_var_Value
		self.n166_var_Value = 5
		self.n165_var_B = self.n166_var_Value
		self.n173_var_Value = 0
		self.n174_var_A = self.n173_var_Value
		self.n177_var_A = self.n173_var_Value
		self.n175_var_Value = 8
		self.n174_var_B = self.n175_var_Value
		self.n178_var_Value = 5
		self.n177_var_B = self.n178_var_Value
		def loaded(args):
			self.n13_var_Player = self.owner
			self.n13_propagator_Player()
			self.n81_trigger_In()
			self.n112_trigger_In()
		self.n13_lvar_SubscriptionId = self.owner.subscribe("player.loaded", loaded)
		def regionCb(args):
			self.n116_var_Invoker = args['entity']
			self.n180_var_Instigator = self.n116_var_Invoker
			if args['entering']:
				self.n117_trigger_In()
			else:
				pass
		self.n116_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_CellBlock.Region8', regionCb, once = True)
		def regionCb(args):
			self.n123_var_Invoker = args['entity']
			self.n123_propagator_Invoker()
			if args['entering']:
				status = self.n124_var_Player.missions.getMissionStatus(638)
				if status == Constants.MISSION_Not_Active:
					self.n125_var_Player.missions.accept(638)
					self.n172_trigger_In()
			else:
				pass
		self.n123_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region2', regionCb, once = False)
		def regionCb(args):
			self.n128_var_Invoker = args['entity']
			self.n129_var_Player = self.n128_var_Invoker
			if args['entering']:
				if self.n129_var_Player:
					self.n129_var_Player.client.onSystemCommunication(11, 5180, '', [])
			else:
				pass
		self.n128_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region11', regionCb, once = False)
		def regionCb(args):
			self.n130_var_Invoker = args['entity']
			self.n131_var_Player = self.n130_var_Invoker
			if args['entering']:
				if self.n131_var_Player:
					self.n131_var_Player.client.onSystemCommunication(11, 5040, '', [])
			else:
				pass
		self.n130_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region2', regionCb, once = False)
		def regionCb(args):
			self.n135_var_Invoker = args['entity']
			self.n136_var_Player = self.n135_var_Invoker
			if args['entering']:
				if self.n136_var_Player:
					self.n136_var_Player.client.onSystemCommunication(11, 5181, '', [])
			else:
				pass
		self.n135_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region10', regionCb, once = False)
		def teleportCb(args):
			if args['regionId'] != 2:
				return False
			self.n141_var_Player = self.owner
			self.n146_var_Player = self.n141_var_Player
			self.n142_var_Player = self.n141_var_Player
			status = self.n146_var_Player.missions.getMissionStatus(640)
			if status == Constants.MISSION_Active:
				self.n142_var_Player.missions.complete(640)
				self.n143_trigger_In()
			return True
		self.n141_lvar_HandlerId = self.owner.subscribe('teleport::in', teleportCb, once = True)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n147_var_Player = self.owner
			self.n149_var_Player = self.n147_var_Player
			self.n161_var_Entity = self.n147_var_Player
			self.n151_var_Player = self.n147_var_Player
			self.n167_var_Player = self.n147_var_Player
			status = self.n149_var_Player.missions.getStepStatus(641, 2121)
			if status == Constants.MISSION_Not_Active:
				self.n161_trigger_In()
			return False
		self.n147_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Preparation_ColMarshr', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n153_var_Player = args['player']
			self.n154_var_Player = self.n153_var_Player
			self.n154_var_Player.missions.accept(641)
			return True
		self.n153_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(4001), dialogChoiceCb, once = False)
		def regionCb(args):
			self.n155_var_Invoker = args['entity']
			self.n156_var_Player = self.n155_var_Invoker
			if args['entering']:
				if self.n156_var_Player:
					self.n156_var_Player.client.onSystemCommunication(11, 5182, '', [])
			else:
				pass
		self.n155_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region3', regionCb, once = False)
		def regionCb(args):
			self.n157_var_Invoker = args['entity']
			self.n158_var_Player = self.n157_var_Invoker
			if args['entering']:
				if self.n158_var_Player:
					self.n158_var_Player.client.onSystemCommunication(11, 5184, '', [])
			else:
				pass
		self.n157_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region12', regionCb, once = False)
		def regionCb(args):
			self.n159_var_Invoker = args['entity']
			self.n160_var_Player = self.n159_var_Invoker
			if args['entering']:
				if self.n160_var_Player:
					self.n160_var_Player.client.onSystemCommunication(11, 5185, '', [])
			else:
				pass
		self.n159_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region13', regionCb, once = False)
		def dialogChoiceCb(args):
			self.n168_var_Player = args['player']
			self.n154_var_Player = self.n168_var_Player
			self.n154_var_Player.missions.accept(641)
			return True
		self.n168_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5022), dialogChoiceCb, once = False)
		def regionCb(args):
			self.n187_var_Invoker = args['entity']
			self.n188_var_Player = self.n187_var_Invoker
			self.n190_var_Player = self.n187_var_Invoker
			self.n189_var_Player = self.n187_var_Invoker
			if args['entering']:
				pass
			else:
				self.n188_trigger_In()
		self.n187_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region3', regionCb, once = False)
		def regionCb(args):
			self.n211_var_Invoker = args['entity']
			self.n213_var_Player = self.n211_var_Invoker
			self.n214_var_Player = self.n211_var_Invoker
			self.n215_var_Player = self.n211_var_Invoker
			if args['entering']:
				self.n213_trigger_In()
			else:
				pass
		self.n211_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region4', regionCb, once = False)
		def regionCb(args):
			self.n220_var_Invoker = args['entity']
			self.n221_var_Player = self.n220_var_Invoker
			self.n222_var_Player = self.n220_var_Invoker
			self.n223_var_Player = self.n220_var_Invoker
			if args['entering']:
				self.n221_trigger_In()
			else:
				pass
		self.n220_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region5', regionCb, once = False)
		def regionCb(args):
			self.n225_var_Invoker = args['entity']
			self.n227_var_Player = self.n225_var_Invoker
			self.n228_var_Player = self.n225_var_Invoker
			self.n226_var_Player = self.n225_var_Invoker
			if args['entering']:
				self.n228_trigger_In()
			else:
				pass
		self.n225_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region6', regionCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n13_lvar_SubscriptionId)
		if self.n116_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n116_lvar_SubscriptionId)
		if self.n123_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n123_lvar_SubscriptionId)
		if self.n128_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n128_lvar_SubscriptionId)
		if self.n130_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n130_lvar_SubscriptionId)
		if self.n135_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n135_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n141_lvar_HandlerId)
		self.owner.unsubscribe(self.n147_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n153_lvar_SubscriptionId)
		if self.n155_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n155_lvar_SubscriptionId)
		if self.n157_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n157_lvar_SubscriptionId)
		if self.n159_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n159_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n168_lvar_SubscriptionId)
		if self.n187_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n187_lvar_SubscriptionId)
		if self.n211_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n211_lvar_SubscriptionId)
		if self.n220_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n220_lvar_SubscriptionId)
		if self.n225_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n225_lvar_SubscriptionId)

