# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class Harset(Script):
	n14_var_Invoker = None
	n15_var_Target = None
	n15_var_Destination = None
	n16_var_Set = None
	n16_var_Value = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n16_var_Value = self.str2vec('0,0.355,-20')
		self.n15_var_Destination = self.n16_var_Value
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(4)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'HarsetRingLeftBottom', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(5)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n4_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'HarsetRingRightBottom', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(6)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n8_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'HarsetRingLeft', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(7)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n10_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'HarsetRingLeftTop', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(8)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n12_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'HarsetRingRight', interactCb, once = False)
		def regionCb(args):
			self.n14_var_Invoker = args['entity']
			self.n15_var_Target = self.n14_var_Invoker
			if args['entering']:
				pos = self.n15_var_Destination
				self.n15_var_Target.moveTo(pos.x, pos.y, pos.z, worldName = 'Harset_CmdCenter' or None)
			else:
				pass
		self.n14_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Harset.CommandCenterTransition', regionCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n4_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n8_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n10_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n12_lvar_TagSubscriptionId)
		if self.n14_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n14_lvar_SubscriptionId)

