# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class Harset_CmdCenter(Script):
	n1_var_Invoker = None
	n2_var_Target = None
	n2_var_Destination = None
	n3_var_Set = None
	n3_var_Value = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n3_var_Value = self.str2vec('0,-67.600,-231')
		self.n2_var_Destination = self.n3_var_Value
		def regionCb(args):
			self.n1_var_Invoker = args['entity']
			self.n2_var_Target = self.n1_var_Invoker
			if args['entering']:
				pos = self.n2_var_Destination
				self.n2_var_Target.moveTo(pos.x, pos.y, pos.z, worldName = 'Harset' or None)
			else:
				pass
		self.n1_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Harset_CmdCenter.HarsetTransition', regionCb, once = False)

	def teardown(self):
		if self.n1_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n1_lvar_SubscriptionId)

