# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class Omega_Site_CmdCenter(Script):
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(17)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'OmegaSiteCmdCenterBeam', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)

