//! The static [`COMMANDS`] table — the Rust analogue of the legacy
//! `Command.add([...])` table plus the FanMMORPG `path_*` additions.
//!
//! Every name here is reachable from [`crate::cell::console::exec`];
//! `tests::every_spec_is_dispatched` asserts no entry falls through to the
//! "not implemented" arm.

use super::{spec, Spec, Target};

pub(crate) static COMMANDS: &[Spec] = &[
    // ── meta ────────────────────────────────────────────────────────────────
    spec(
        "help",
        0,
        1,
        Target::None,
        "List console commands (optionally filter by substring)",
    ),
    spec(
        "seedconfirm",
        0,
        0,
        Target::None,
        "Emit your pending authoring changes per seed file (log/Discord)",
    ),
    spec(
        "seedpending",
        0,
        0,
        Target::None,
        "List your pending authoring changes",
    ),
    spec(
        "seedcancel",
        0,
        0,
        Target::None,
        "Discard your pending authoring changes",
    ),
    // ── D. search / query ─────────────────────────────────────────────────────
    spec(
        "searchitem",
        1,
        2,
        Target::None,
        "Search item designs by name",
    ),
    spec(
        "searchmission",
        1,
        2,
        Target::None,
        "Search mission designs by name",
    ),
    spec(
        "searchtemplate",
        1,
        2,
        Target::None,
        "Search entity templates by name",
    ),
    spec(
        "players",
        0,
        0,
        Target::None,
        "List players online on this CellApp service",
    ),
    spec(
        "listabilities",
        0,
        0,
        Target::Player,
        "List the target player's known abilities by name",
    ),
    // ── I. entity / combat inspection (read-only) ──────────────────────────────
    spec(
        "info",
        0,
        1,
        Target::None,
        "Show detailed info about the target (selection wins over [entityId])",
    ),
    spec(
        "facing",
        0,
        0,
        Target::Spawnable,
        "Show facing angle/class and distance to the target",
    ),
    spec(
        "combatinfo",
        0,
        0,
        Target::Mob,
        "Diagnose combat-readiness issues on the targeted NPC",
    ),
    // ── F. granular stat readouts ──────────────────────────────────────────────
    spec(
        "stats",
        0,
        0,
        Target::Being,
        "Show basic health/focus stats of the target",
    ),
    spec(
        "primarystats",
        0,
        0,
        Target::Being,
        "Show primary attribute stats of the target",
    ),
    spec(
        "speedstats",
        0,
        0,
        Target::Being,
        "Show movement/action speed stats of the target",
    ),
    spec(
        "armorstats",
        0,
        0,
        Target::Being,
        "Show armor + resistance stats of the target",
    ),
    spec(
        "qrstats",
        0,
        0,
        Target::Being,
        "Show QR-system combat stats of the target",
    ),
    spec(
        "absorbstats",
        0,
        0,
        Target::Being,
        "Show damage-absorption stats of the target",
    ),
    spec(
        "stealthstats",
        0,
        0,
        Target::Being,
        "Show stealth/disguise stats of the target",
    ),
    // ── A. entity / content authoring ──────────────────────────────────────────
    spec(
        "tag",
        1,
        1,
        Target::Spawnable,
        "Set the content tag of the target ('none' clears)",
    ),
    spec(
        "name",
        1,
        usize::MAX,
        Target::Being,
        "Set the display name of the target",
    ),
    spec(
        "alignment",
        1,
        1,
        Target::Being,
        "Set alignment (undefined|praxis|sgu) of the target",
    ),
    spec(
        "nameid",
        1,
        1,
        Target::Spawnable,
        "Set the localized name-id of the target",
    ),
    spec(
        "staticmesh",
        1,
        1,
        Target::Spawnable,
        "Set the static mesh name of the target",
    ),
    spec(
        "bodyset",
        1,
        1,
        Target::Spawnable,
        "Set the body set of the target",
    ),
    spec(
        "eventset",
        1,
        1,
        Target::Spawnable,
        "Set the kismet event-set id of the target",
    ),
    spec(
        "interactiontype",
        1,
        1,
        Target::Spawnable,
        "Set the interaction-type flags of the target",
    ),
    spec(
        "lookat",
        0,
        0,
        Target::Spawnable,
        "Rotate the target to face you",
    ),
    spec(
        "visible",
        1,
        1,
        Target::Spawnable,
        "Show/hide the target (1/0)",
    ),
    spec(
        "setcombatant",
        1,
        1,
        Target::Being,
        "Set a combatant state flag on the target",
    ),
    spec(
        "unsetcombatant",
        1,
        1,
        Target::Being,
        "Clear a combatant state flag on the target",
    ),
    spec(
        "addcomponent",
        1,
        1,
        Target::Being,
        "Add a body component to the target",
    ),
    spec(
        "delcomponent",
        1,
        1,
        Target::Being,
        "Remove a body component from the target",
    ),
    spec(
        "adddialog",
        2,
        2,
        Target::Spawnable,
        "Add a dialog choice (templateId setMapId) to the target",
    ),
    spec(
        "removedialog",
        2,
        2,
        Target::Spawnable,
        "Remove a dialog choice (templateId setMapId) from the target",
    ),
    spec(
        "dynamicupdate",
        0,
        0,
        Target::Spawnable,
        "Re-broadcast the target's dynamic properties to witnesses",
    ),
    // ── H. low-level net / AI debug ────────────────────────────────────────────
    spec(
        "net_seq",
        1,
        2,
        Target::Spawnable,
        "Play a kismet sequence on the target",
    ),
    spec(
        "net_seqto",
        1,
        2,
        Target::None,
        "Play a sequence from you to the target",
    ),
    spec(
        "net_seqfrom",
        1,
        2,
        Target::Spawnable,
        "Play a sequence from the target to you",
    ),
    spec(
        "net_timer",
        2,
        4,
        Target::Spawnable,
        "Start a client timer on the target",
    ),
    spec(
        "net_mapinfo",
        3,
        5,
        Target::Player,
        "Send onMapInfo to the target",
    ),
    spec(
        "net_speak",
        1,
        2,
        Target::Spawnable,
        "Make the target speak (message [channel])",
    ),
    spec(
        "net_dialog",
        1,
        1,
        Target::None,
        "Open a dialog with the target",
    ),
    spec(
        "net_challenge",
        5,
        5,
        Target::None,
        "Send onClientChallenge to the target",
    ),
    spec(
        "debug_velocity",
        3,
        3,
        Target::Spawnable,
        "Set the velocity of the target",
    ),
    spec(
        "debug_controller",
        0,
        0,
        Target::Spawnable,
        "Toggle the debug movement controller on the target",
    ),
    spec(
        "debug_follow",
        0,
        0,
        Target::Spawnable,
        "Toggle the follow controller on the target",
    ),
    spec(
        "threaten",
        1,
        1,
        Target::Mob,
        "Generate threat on the targeted mob",
    ),
    spec(
        "aggression",
        1,
        1,
        Target::Mob,
        "Set the aggression level of the targeted mob",
    ),
    // ── E. crafting / discipline ───────────────────────────────────────────────
    spec(
        "allcraft",
        0,
        0,
        Target::Player,
        "Grant all blueprints + max disciplines to the target",
    ),
    spec(
        "learndiscipline",
        1,
        2,
        Target::Player,
        "Learn/raise a discipline (disciplineId [expertise])",
    ),
    spec(
        "forgetdiscipline",
        1,
        1,
        Target::Player,
        "Forget a discipline (disciplineId)",
    ),
    // ── Mission gaps ──────────────────────────────────────────────────────────
    spec(
        "missionfail",
        1,
        1,
        Target::Player,
        "Force-fail a mission on the target (designId)",
    ),
    spec(
        "missionrewards",
        1,
        1,
        Target::Player,
        "Preview a mission's reward set (designId)",
    ),
    // ── Player grants ───────────────────────────────────────────────────────────
    spec(
        "givecash",
        1,
        1,
        Target::Player,
        "Grant naquadah to the target (amount)",
    ),
    spec(
        "givexp",
        1,
        1,
        Target::Player,
        "Grant experience to the target (amount)",
    ),
    // ── Travel ──────────────────────────────────────────────────────────────────
    spec(
        "gotoxyz",
        3,
        3,
        Target::None,
        "Teleport the target (or yourself) to coordinates in this space (x y z)",
    ),
    spec(
        "goto",
        1,
        1,
        Target::None,
        "Move the target (or yourself) to a named online player's position/instance",
    ),
    spec(
        "summon",
        1,
        1,
        Target::None,
        "Move a named online player to the target's (or your) position/instance",
    ),
    spec(
        "gotolocation",
        4,
        4,
        Target::None,
        "Move the target (or yourself) to coordinates in a named world (worldName x y z)",
    ),
    spec(
        "gotospace",
        4,
        4,
        Target::None,
        "Move the target (or yourself) into an exact loaded space instance (spaceId x y z)",
    ),
    // ── J. placement (position / orientation) ───────────────────────────────────
    spec(
        "location",
        0,
        3,
        Target::Spawnable,
        "Report (no args) or set (x y z) the target's position",
    ),
    spec(
        "rotation",
        0,
        3,
        Target::Spawnable,
        "Report (no args) or set (pitch yaw roll) the target's orientation",
    ),
    // ── K. stat setters ──────────────────────────────────────────────────────────
    spec(
        "speed",
        1,
        1,
        Target::Being,
        "Set the target's current movement and rotation speed together",
    ),
    // ── G. server / maintenance ────────────────────────────────────────────────
    spec("save", 0, 0, Target::None, "Persist your player entity now"),
    spec(
        "reloadmap",
        0,
        0,
        Target::None,
        "Reload the current map on yourself",
    ),
    spec(
        "reloadres",
        0,
        1,
        Target::None,
        "Reload server resource caches",
    ),
    spec(
        "removerespawner",
        1,
        1,
        Target::Player,
        "Remove a respawner from the target (respawnerId)",
    ),
    spec(
        "loglevel",
        1,
        2,
        Target::None,
        "Set the server log level (level [category])",
    ),
    spec(
        "logclient",
        0,
        0,
        Target::None,
        "Toggle forwarding server logs to your client",
    ),
    // ── B. spawn lifecycle + authoring / persistence ───────────────────────────
    spec(
        "spawn",
        1,
        1,
        Target::None,
        "Spawn one entity of a template at your position and facing (templateId)",
    ),
    // Legacy registered `.despawn` as `SGWSpawnableEntity`, which `SGWPlayer`
    // derives from — so the legacy command would destroy a logged-in player's
    // cell entity. Corrected to `Target::Mob` (NPC / non-player spawnable
    // only) per D02; `SpaceManager::despawn_npc` refuses players again on its
    // own so the guard survives a registry edit.
    spec(
        "despawn",
        0,
        0,
        Target::Mob,
        "Destroy the selected NPC (runtime only — its spawnlist row is untouched)",
    ),
    spec(
        "savespawn",
        0,
        0,
        Target::Spawnable,
        "Persist the target's spawn to the spawnlist",
    ),
    spec(
        "delspawn",
        0,
        0,
        Target::Spawnable,
        "Delete the target's spawnlist row",
    ),
    spec(
        "autosavespawn",
        1,
        1,
        Target::None,
        "Toggle auto-persisting newly spawned entities (1/0)",
    ),
    spec(
        "respawnall",
        0,
        0,
        Target::None,
        "Respawn every NPC in your space",
    ),
    spec(
        "spawnrandom",
        3,
        4,
        Target::None,
        "Spawn N random-scattered copies of a template (templateId xRange zRange [count])",
    ),
    // ── C. patrol authoring (FanMMORPG) ─────────────────────────────────────────
    spec(
        "path_add",
        1,
        1,
        Target::None,
        "Append your position as the next waypoint of a path (pathId)",
    ),
    spec(
        "path_show",
        1,
        1,
        Target::None,
        "Show all waypoints of a path (pathId)",
    ),
    spec(
        "path_clear",
        1,
        1,
        Target::None,
        "Delete all waypoints of a path (pathId)",
    ),
    spec(
        "path_assign",
        1,
        2,
        Target::Mob,
        "Assign a path to the target NPC and start it (pathId [delay])",
    ),
    spec(
        "path_unassign",
        0,
        0,
        Target::Mob,
        "Remove the patrol from the target NPC",
    ),
    spec(
        "path_set_seq",
        3,
        3,
        Target::None,
        "Set a kismet sequence on a waypoint (pathId index seqId)",
    ),
    spec(
        "path_clear_seq",
        2,
        2,
        Target::None,
        "Clear the sequence on a waypoint (pathId index)",
    ),
    spec(
        "path_set_tp",
        2,
        2,
        Target::None,
        "Set a waypoint's teleport dest to your position (pathId index)",
    ),
    spec(
        "path_clear_tp",
        2,
        2,
        Target::None,
        "Clear a waypoint's teleport (pathId index)",
    ),
    spec(
        "path_set_tp_seq",
        3,
        3,
        Target::None,
        "Set a waypoint's arrival sequence (pathId index seqId)",
    ),
    spec(
        "path_set_tp_delay",
        3,
        3,
        Target::None,
        "Set a waypoint's teleport delay (pathId index delay)",
    ),
];
