--
-- NEW CONTENT (Debug Area, DA-09): the System Lords' summit on the Ihpet
-- courtyard of world 1300's south compound
-- (docs/content/debug-area.md#system-lords-summit).
--
-- Id block: templates 1400-1409 (DA-09). Six System Lords and Ra's Jaffa, all
-- faction 1 (World Object, friendly), no ability set, no loot: they stand,
-- squabble in say chat (ambient chatter group 1,
-- db/resources/Dialogs/Seed/ambient_chatter_lords.sql) and cannot be attacked.
--
-- Costumes are BodyComponent exports of the client's own packages (checked
-- with `query-index scan <package> BodyComponent`) and was seen in the
-- client (DA-09 lab check). Ra, Anat and Nerus wear their shipped NPC kits
-- (templates 41, 43 and 53). Ra's kit already includes his crowned head:
-- adding NPC_Ra_Head_00 or NPC_RaG_FingerNail_00 to it makes the client
-- draw its placeholder cube instead of Ra. Ba'al
-- (template 42 is his head on the bare base body) wears the Yellow Trader
-- robes. The client ships no female Goa'uld armour beyond Anat's NPC kit, so
-- Athena takes Anat's gown and bracer with a circlet, and Morrigan Anat's
-- breastplate, pauldron and boots with war paint and a ribbon device: no two
-- lords wear the same outfit. Names, speakers and skin tints are the shipped
-- templates' (41-45, 53 and 144).
--
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1400, NULL, 'BS_GoauldMale.BS_GoauldMale', '{BS_GoauldMale.BS_GM_Base_Boots00_00,BS_GoauldMale.BS_GM_Base_Hands00_00,BS_GoauldMale.BS_GM_Base_Legs00_00,BS_GoauldMale.BS_GM_Base_Torso00_00,NPC_Goauld.NPC_Ra_Cape_00,NPC_Goauld.NPC_Ra_Dress_00,NPC_Goauld.NPC_Ra_Helmet_00,NPC_Goauld.NPC_Ra_Torso_00,NPC_Goauld.NPC_Ra_TorsoArmor_00}', 0, 0, 570, 50, 0, 1, 20205, NULL, NULL, NULL, 'Debug Area - Ra', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, NULL, '{}', NULL, 2547, true, NULL, NULL, false, false);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1401, NULL, 'BS_GoauldMale.BS_GoauldMale', '{AR_G_Yellow_Trader.AR_GM_YB1_YH101,AR_G_Yellow_Trader.AR_GM_YG1_YG101YB101,AR_G_Yellow_Trader.AR_GM_YL1_YL101YB100YC100YS100,AR_G_Yellow_Trader.AR_GM_YT1_YT103YP100,BS_GoauldMale.BS_GM_Boots_00,BS_GoauldMale.BS_GM_Hands_00,BS_GoauldMale.BS_GM_Torso_00,NPC_Goauld.NPC_GM_Baal_Head_BC}', 0, 0, 570, 50, 0, 1, 8186, NULL, NULL, NULL, 'Debug Area - Ba''al', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, -1014470144, NULL, '{}', NULL, 942, true, NULL, NULL, false, false);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1402, NULL, 'BS_GoauldFemale.BS_GoauldFemale', '{BS_GoauldFemale.BS_GF_Base_Boots00_00,BS_GoauldFemale.BS_GF_Base_Hands00_00,BS_GoauldFemale.BS_GF_Base_Legs00_00,BS_GoauldFemale.BS_GF_Base_Torso00_00,NPC_Goauld.NPC_GF_Anat_Boots_BC,NPC_Goauld.NPC_GF_Anat_Bracer_BC,NPC_Goauld.NPC_GF_Anat_Dress_BC,NPC_Goauld.NPC_GF_Anat_Hair_BC,NPC_Goauld.NPC_GF_Anat_Head_BC,NPC_Goauld.NPC_GF_Anat_Pauldron_BC,NPC_Goauld.NPC_GF_Anat_TorsoArmor_BC}', 0, 0, 570, 50, 0, 1, 2850, NULL, NULL, NULL, 'Debug Area - Anat', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, -52773120, NULL, '{}', NULL, 944, true, NULL, NULL, false, false);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1403, NULL, 'BS_GoauldFemale.BS_GoauldFemale', '{ACC_GoauldFemale.ACC_GF_Accessory_03,BS_GoauldFemale.BS_GF_Base_Boots00_00,BS_GoauldFemale.BS_GF_Base_Hands00_00,BS_GoauldFemale.BS_GF_Base_Legs00_00,BS_GoauldFemale.BS_GF_Base_Torso00_00,NPC_Goauld.NPC_GF_Anat_Bracer_BC,NPC_Goauld.NPC_GF_Anat_Dress_BC,NPC_Goauld.NPC_GF_Athena_Hair_BC,NPC_Goauld.NPC_GF_Athena_Head_BC}', 0, 0, 570, 50, 0, 1, 7563, NULL, NULL, NULL, 'Debug Area - Athena', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, -52773120, NULL, '{}', NULL, 949, true, NULL, NULL, false, false);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1404, NULL, 'BS_GoauldFemale.BS_GoauldFemale', '{BS_GoauldFemale.BS_GF_Base_Hands00_00,BS_GoauldFemale.BS_GF_Base_Legs00_00,BS_GoauldFemale.BS_GF_Base_Torso00_00,BS_GoauldFemale.BS_GF_FacePaint_04,NPC_Goauld.NPC_GF_Anat_Boots_BC,NPC_Goauld.NPC_GF_Anat_Pauldron_BC,NPC_Goauld.NPC_GF_Anat_TorsoArmor_BC,NPC_Goauld.NPC_GF_Morri_Head_BC,WP-Goauld.WP_Ribbon_Elec_1A}', 0, 0, 570, 50, 0, 1, 7521, NULL, NULL, NULL, 'Debug Area - Morrigan', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, -340158464, NULL, '{}', NULL, 970, true, NULL, NULL, false, false);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1405, NULL, 'BS_HumanMale.BS_HumanMale', '{BS_HumanMale.BS_HM_Base_Torso00_00,BS_HumanMale.BS_HM_Boots_00,BS_HumanMale.BS_HM_Hands_00,BS_HumanMale.BS_HM_Legs_00,NPC_Human.NPC_HM_Nerus_Boots_BC,NPC_Human.NPC_HM_Nerus_Hands_BC,NPC_Human.NPC_HM_Nerus_Head_BC,NPC_Human.NPC_HM_Nerus_Legs_BC,NPC_Human.NPC_HM_Nerus_Robe_BC,NPC_Human.NPC_HM_Nerus_Torso_BC}', 0, 0, 570, 50, 0, 1, 7165, NULL, NULL, NULL, 'Debug Area - Nerus', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, -52773120, NULL, '{}', NULL, 943, true, NULL, NULL, false, false);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, name, patrol_path_id, patrol_point_delay, template_name, class, buy_item_list, sell_item_list, repair_item_list, recharge_item_list, ability_set_id, ammo_type, loot_table_id, primary_color_id, secondary_color_id, skin_tint, weapon_item_id, static_interaction_sets, trainer_ability_list_id, speaker_id, has_dynamic_properties, interaction_set_id, move_speed, use_cover, training_dummy) VALUES (1406, NULL, 'BS_JaffaMale.BS_JaffaMale', '{AR_J_Ra.AR_JM_RB1_RH100,AR_J_Ra.AR_JM_RG1_RB100,AR_J_Ra.AR_JM_RH1_RH100,AR_J_Ra.AR_JM_RL1_RS100,AR_J_Ra.AR_JM_RT1_RT100,BS_JaffaMale.BS_JM_Boots_00,BS_JaffaMale.BS_JM_Hands_00,BS_JaffaMale.BS_JM_Head_00,BS_JaffaMale.BS_JM_Legs_00,BS_JaffaMale.BS_JM_Torso_00,WP-Jaffa.WP_Staff_Plasma_4A}', 0, 0, 570, 30, 0, 1, 7455, NULL, NULL, NULL, 'Debug Area - Ra''s Jaffa', 'mob', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, NULL, '{}', NULL, NULL, true, NULL, NULL, false, false);

-- Keep default-id inserts past DA-09's reserved block 1400-1409.
SELECT pg_catalog.setval('entity_templates_template_id_seq', GREATEST((SELECT MAX(template_id) FROM entity_templates), (SELECT last_value FROM entity_templates_template_id_seq), 1409), true);
