--
-- Debug Area (world 1300) packet DA-03: the NPC templates of the faction yard
-- (Z4) and the AI behaviour slope (Z5). Block 1330-1369
-- (docs/analysis/debug-area/README.md). Reference: docs/content/debug-area.md.
--
-- Loaded by db/database.sql right after entity_templates.sql. The enemy
-- gallery (Z7) places the existing hostile templates and adds none here.
--
-- Faction choices (the reaction table, cell/combat/faction_reaction.rs):
--   1  World Object      friendly to players, no enemy in the table: never fights.
--   9  Friendly_Ambient  friendly to players, no enemy in the table: never fights.
--   7  Neutral_Ambient   neutral to players, no enemy in the table: never fights.
--   10 Straegis          hostile on sight. Only faction 10 can be damaged.
-- Faction 3 (Praxis, what players react as) is left out on purpose: it is
-- mutually hostile with 10, so a faction-3 "friendly" would start NPC-vs-NPC
-- fights with the hostile pen. That is DA-04's arena.
--
-- Level 1 throughout (250 HP). No ability set: every one falls back to 592
-- Pistol Shot. Respawn timers are on the spawn rows.
--
-- 1341 wanders (radius 8 u, dwell 3-8 s). 1342 leashes at 15 u (+5 u band)
-- and aggroes at 12 u. 1343 aggroes at 6 u and assists at 10 u, so a tester
-- can shoot one of the trio from range without pulling it by proximity.
-- The footer raises the id sequence past the Debug Area's whole reserved
-- block (templates up to 1399).
--

INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1330, NULL, 'BS_HumanMale.BS_HumanMale', '{ACC_HumanMale.ACC_HM_Accessory_09,AR_H_Ballistic00.AR_HM_BT1_BT101,AR_H_SGC.AR_HM_SB1_SH100,AR_H_SGC.AR_HM_SL1_SL100,BS_HumanMale.BS_HM_Boots_00,BS_HumanMale.BS_HM_Hair_01,BS_HumanMale.BS_HM_Hands_00,BS_HumanMale.BS_HM_Head_03,BS_HumanMale.BS_HM_Legs_00,BS_HumanMale.BS_HM_Torso_00}', 0, 0, 570, 1, 0, 1, 8360, 'DebugArea - Friendly (faction 1 World Object)', 'mob', NULL, 0, 0, -340158464, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1331, NULL, 'BS_HumanMale.BS_HumanMale', '{AR_Global.Prisoner_Boots,AR_H_Clothing00.AR_HM_PL1_PL100,AR_H_Clothing00.AR_HM_PT1_PT100,BS_HumanMale.BS_HM_Boots_00,BS_HumanMale.BS_HM_Feet_00,BS_HumanMale.BS_HM_Hands_00,BS_HumanMale.BS_HM_Head_02,BS_HumanMale.BS_HM_Legs_00,BS_HumanMale.BS_HM_Torso_00,WP-Human.WP_SMG_1A}', 0, 0, 570, 1, 0, 9, 7552, 'DebugArea - Friendly (faction 9 Friendly_Ambient)', 'mob', NULL, -256, -256, -52773120, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1332, NULL, 'BS_HumanMale.BS_HumanMale', '{AR_H_Lucia.AR_HM_ST1_SC100,AR_H_Lucia.AR_HM_TL1_TT100,BS_HumanMale.BS_HM_Boots_00,BS_HumanMale.BS_HM_Feet_00,BS_HumanMale.BS_HM_Hands_00,BS_HumanMale.BS_HM_Head_01,BS_HumanMale.BS_HM_Legs_00,BS_HumanMale.BS_HM_Torso_00}', 0, 0, 570, 1, 0, 7, 7120, 'DebugArea - Neutral (faction 7 Neutral_Ambient)', 'mob', NULL, -65536, -16777216, -52773120, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1333, NULL, 'BS_JaffaMale.BS_JaffaMale', '{AR_J_Standard.AR_JM_SB1_SH100,AR_J_Standard.AR_JM_SG1_SG100,AR_J_Standard.AR_JM_SH1_SH100,AR_J_Standard.AR_JM_SL1_SS100,AR_J_Standard.AR_JM_ST1_ST100SS100SP100,BS_JaffaMale.BS_JM_Boots_00,BS_JaffaMale.BS_JM_Hands_00,BS_JaffaMale.BS_JM_Head_00,BS_JaffaMale.BS_JM_Legs_00,BS_JaffaMale.BS_JM_Torso_00}', 0, 0, 570, 1, 0, 10, 7409, 'DebugArea - Neutral Jaffa (faction 10, spawn pinned NEUTRAL)', 'mob', NULL, 0, 0, 0, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1340, NULL, 'BS_JaffaMale.BS_JaffaMale', '{AR_J_Standard.AR_JM_SB1_SH100,AR_J_Standard.AR_JM_SG1_SG100,AR_J_Standard.AR_JM_SH1_SH100,AR_J_Standard.AR_JM_SL1_SS100,AR_J_Standard.AR_JM_ST1_ST100SS100SP100,BS_JaffaMale.BS_JM_Boots_00,BS_JaffaMale.BS_JM_Hands_00,BS_JaffaMale.BS_JM_Head_00,BS_JaffaMale.BS_JM_Legs_00,BS_JaffaMale.BS_JM_Torso_00}', 0, 0, 570, 1, 0, 10, 7405, 'DebugArea - Patroller', 'mob', NULL, 0, 0, 0, true, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1341, NULL, 'BS_HumanMale.BS_HumanMale', '{AR_H_Lucia.AR_HM_ST1_SC100,AR_H_Lucia.AR_HM_TL1_TT100,BS_HumanMale.BS_HM_Boots_00,BS_HumanMale.BS_HM_Feet_00,BS_HumanMale.BS_HM_Hands_00,BS_HumanMale.BS_HM_Head_01,BS_HumanMale.BS_HM_Legs_00,BS_HumanMale.BS_HM_Torso_00}', 0, 0, 570, 1, 0, 10, 7514, 'DebugArea - Wanderer', 'mob', NULL, -65536, -16777216, -52773120, true, 8.0, 3.0, 8.0, NULL, NULL, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1342, NULL, 'BS_JaffaMale.BS_JaffaMale', '{AR_J_Svarog.AR_JM_SB1_SH100,AR_J_Svarog.AR_JM_SG1_SG100SB200SB101SB102,AR_J_Svarog.AR_JM_SH1_SH100,AR_J_Svarog.AR_JM_SL1_SL100SB100SB101SS100,AR_J_Svarog.AR_JM_ST1_ST100SB100SS100,BS_JaffaMale.BS_JM_Boots_00,BS_JaffaMale.BS_JM_Hands_00,BS_JaffaMale.BS_JM_Head_00,BS_JaffaMale.BS_JM_Legs_00,BS_JaffaMale.BS_JM_Torso_00}', 0, 0, 570, 1, 0, 10, 7406, 'DebugArea - Leash test', 'mob', NULL, 0, 0, 0, true, NULL, NULL, NULL, 15.0, 12.0, NULL);
INSERT INTO entity_templates (template_id, static_mesh, body_set, components, flags, interaction_type, event_set_id, level, alignment, faction, name_id, template_name, class, ability_set_id, primary_color_id, secondary_color_id, skin_tint, has_dynamic_properties, wander_radius, wander_min_dwell_secs, wander_max_dwell_secs, leash_distance, aggro_radius, assist_radius) VALUES (1343, NULL, 'BS_JaffaMale.BS_JaffaMale', '{AR_J_Jackal.AR_JM_JB1_JH100,AR_J_Jackal.AR_JM_JG1_JG100,AR_J_Jackal.AR_JM_JH1_JH100,AR_J_Jackal.AR_JM_JL1_JS100JT100,AR_J_Jackal.AR_JM_JT1_JT100JS100JP100,BS_JaffaMale.BS_JM_Boots_00,BS_JaffaMale.BS_JM_Hands_00,BS_JaffaMale.BS_JM_Head_00,BS_JaffaMale.BS_JM_Legs_00,BS_JaffaMale.BS_JM_Torso_00}', 0, 0, 570, 1, 0, 10, 7509, 'DebugArea - Assist trio', 'mob', NULL, 0, 0, -52773120, true, NULL, NULL, NULL, NULL, 6.0, 10.0);

SELECT pg_catalog.setval('entity_templates_template_id_seq', GREATEST((SELECT MAX(template_id) FROM entity_templates), (SELECT last_value FROM entity_templates_template_id_seq), 1399), true);
