-- database.sql — single entry point for the Cimmeria database.
-- Replaces db/resources.sql + db/sgw.sql.
--
-- Usage (fresh load with Force bootstrap):
--   psql -U w-testing -d sgw -v ON_ERROR_STOP=1 -f db/database.sql
--
-- All paths are relative to this file (\ir = include-relative).

-- ════════════════════════════════════════════════════════════════
-- resources schema
-- ════════════════════════════════════════════════════════════════

\ir resources/_schema.sql

-- Types
\ir resources/AI/Types/CAH_DebugLevel.sql
\ir resources/AI/Types/EAIErrorStateAction.sql
\ir resources/AI/Types/EAIState.sql
\ir resources/AI/Types/ECASPosition.sql
\ir resources/AI/Types/ECoverHeight.sql
\ir resources/AI/Types/ECoverQuality.sql
\ir resources/AI/Types/EMobAggressionLevel.sql
\ir resources/AI/Types/EMobIntel.sql
\ir resources/AI/Types/EMobMovementType.sql
\ir resources/AI/Types/EMobRank.sql
\ir resources/AI/Types/EPatrolType.sql
\ir resources/AI/Types/EPetStance.sql
\ir resources/Abilities/Types/EAbilityFlags.sql
\ir resources/Abilities/Types/EAbilityTypes.sql
\ir resources/Abilities/Types/EActionHandlerEvent.sql
\ir resources/Abilities/Types/EAmmoType.sql
\ir resources/Abilities/Types/EReloadType.sql
\ir resources/Abilities/Types/ESpecialWordFlags.sql
\ir resources/Abilities/Types/EStance.sql
\ir resources/Abilities/Types/EWeaponRange.sql
\ir resources/Abilities/Types/EWeaponState.sql
\ir resources/Abilities/Types/EWeaponType.sql
\ir resources/Archetypes/Types/EAlignment.sql
\ir resources/Archetypes/Types/EArchetype.sql
\ir resources/Archetypes/Types/EGender.sql
\ir resources/Archetypes/Types/ESubsystem.sql
\ir resources/Archetypes/Types/EUnitType.sql
\ir resources/Combat/Types/ECombatantState.sql
\ir resources/Combat/Types/EDamageType.sql
\ir resources/Combat/Types/EDuelDefeatReason.sql
\ir resources/Combat/Types/EDuelState.sql
\ir resources/Combat/Types/EMitigationType.sql
\ir resources/Combat/Types/EStatLevel.sql
\ir resources/Combat/Types/EStatResultCode.sql
\ir resources/Combat/Types/EStatType.sql
\ir resources/Combat/Types/EStatValueType.sql
\ir resources/Combat/Types/EStats.sql
\ir resources/Combat/Types/EThreatLevel.sql
\ir resources/Dialogs/Types/EClientChallengeType.sql
\ir resources/Dialogs/Types/EClientLockBits.sql
\ir resources/Dialogs/Types/EDialogDialogType.sql
\ir resources/Dialogs/Types/EDialogType.sql
\ir resources/Dialogs/Types/EDialogUIScreenType.sql
\ir resources/Dialogs/Types/ESpeakerFlags.sql
\ir resources/Dialogs/Types/ETextType.sql
\ir resources/Effects/Types/EEffectClass.sql
\ir resources/Effects/Types/EEffectFlag.sql
\ir resources/Effects/Types/EEffectType.sql
\ir resources/Entities/Types/EEntityFlags.sql
\ir resources/Entities/Types/EEntityPropertyType.sql
\ir resources/Entities/Types/EMoniker.sql
\ir resources/Entities/Types/EMonikerFlags.sql
\ir resources/Entities/Types/EResourceType.sql
\ir resources/Events/Types/EKismetViewType.sql
\ir resources/Events/Types/ESequenceEventType.sql
\ir resources/Gameplay/Types/ContextTypes.sql
\ir resources/Gameplay/Types/EAggressionIDType.sql
\ir resources/Gameplay/Types/EBehaviorEventFlags.sql
\ir resources/Gameplay/Types/EConditionHandlerFeedback.sql
\ir resources/Gameplay/Types/ECooldownCategory.sql
\ir resources/Gameplay/Types/ECrystals.sql
\ir resources/Gameplay/Types/EEvent.sql
\ir resources/Gameplay/Types/EGameFunctionFlags.sql
\ir resources/Gameplay/Types/EGiveCashTag.sql
\ir resources/Gameplay/Types/EMovementType.sql
\ir resources/Gameplay/Types/EPollType.sql
\ir resources/Gameplay/Types/EProxyMessages.sql
\ir resources/Gameplay/Types/EReasons.sql
\ir resources/Gameplay/Types/EStateField.sql
\ir resources/Gameplay/Types/ETargetCollectionMethod.sql
\ir resources/Gameplay/Types/ETargetCollectionParams.sql
\ir resources/Gameplay/Types/ETargetType.sql
\ir resources/Gameplay/Types/ETimerType.sql
\ir resources/Gameplay/Types/ETimerUpdateType.sql
\ir resources/Gameplay/Types/Postures.sql
\ir resources/Gameplay/Types/WanderTypes.sql
\ir resources/Gameplay/Types/active_interaction_map.sql
\ir resources/Gameplay/Types/effect_action.sql
\ir resources/Gameplay/Types/effect_action_type.sql
\ir resources/Items/Types/ECostType.sql
\ir resources/Items/Types/ECraftFlags.sql
\ir resources/Items/Types/ECraftTypeFlags.sql
\ir resources/Items/Types/EInventoryContainerId.sql
\ir resources/Items/Types/EItemFlag.sql
\ir resources/Items/Types/EItemQuality.sql
\ir resources/Items/Types/EItemType.sql
\ir resources/Items/Types/EVendingSetFlag.sql
\ir resources/Loot/Types/ELootSetFlags.sql
\ir resources/Loot/Types/ELootType.sql
\ir resources/Missions/Types/EMinigameCallEndedResult.sql
\ir resources/Missions/Types/EMinigameCallResult.sql
\ir resources/Missions/Types/EMissionFlags.sql
\ir resources/Missions/Types/EMissionTaskFlag.sql
\ir resources/Missions/Types/EResultCode.sql
\ir resources/Social/Types/EBlackMarketError.sql
\ir resources/Social/Types/EBlackMarketFilter.sql
\ir resources/Social/Types/EBlackMarketSearchType.sql
\ir resources/Social/Types/EBlackMarketSortType.sql
\ir resources/Social/Types/EBlackMarketTime.sql
\ir resources/Social/Types/EContactListEvent.sql
\ir resources/Social/Types/EFaction.sql
\ir resources/Social/Types/EGroupLootType.sql
\ir resources/Social/Types/EMailFlags.sql
\ir resources/Social/Types/EMailResultCodes.sql
\ir resources/Social/Types/EMemberInfo.sql
\ir resources/Social/Types/EOrganizationPermission.sql
\ir resources/Social/Types/EOrganizationRank.sql
\ir resources/Social/Types/EOrganizationType.sql
\ir resources/Social/Types/EPersistentOrganizationType.sql
\ir resources/Social/Types/ERelationshipType.sql
\ir resources/Social/Types/ESide.sql
\ir resources/Social/Types/ETradeLockState.sql
\ir resources/Social/Types/ETradeResults.sql
\ir resources/System/Types/EDBErrorType.sql
\ir resources/System/Types/EErrorAIStateReason.sql
\ir resources/System/Types/EErrorCodeSystem.sql
\ir resources/System/Types/EGMInfoRequestType.sql
\ir resources/System/Types/ELoggingEvent.sql
\ir resources/Visuals/Types/EVisualGroupType.sql
\ir resources/Worlds/Types/EAoIRadiusType.sql
\ir resources/Worlds/Types/EChannel.sql
\ir resources/Worlds/Types/EGateAddress.sql
\ir resources/Worlds/Types/EInteractionDirection.sql
\ir resources/Worlds/Types/EInteractionNotificationType.sql
\ir resources/Worlds/Types/EInteractionType.sql
\ir resources/Worlds/Types/ELocales.sql
\ir resources/Worlds/Types/EMapPing.sql
\ir resources/Worlds/Types/EMapWaypoint.sql
\ir resources/Worlds/Types/ERegionEvents.sql
\ir resources/Worlds/Types/ERegionFlags.sql
\ir resources/Worlds/Types/EWorldFlags.sql
\ir resources/Worlds/Types/EWorldIdType.sql

-- Sequences
\ir resources/Abilities/Sequences/abilities_ability_id_seq.sql
\ir resources/Abilities/Sequences/ability_moniker_groups_group_id_seq.sql
\ir resources/Abilities/Sequences/ability_sets2_ability_set_id_seq.sql
\ir resources/Abilities/Sequences/trainer_ability_lists_list_id_seq.sql
\ir resources/Dialogs/Sequences/dialog_screen_buttons_2_screen_button_id_seq.sql
\ir resources/Dialogs/Sequences/dialog_screen_buttons_button_id_seq.sql
\ir resources/Dialogs/Sequences/dialog_screens_screen_id_seq.sql
\ir resources/Dialogs/Sequences/dialog_set_maps_dialog_set_map_id_seq.sql
\ir resources/Dialogs/Sequences/dialog_sets_dialog_set_id_seq.sql
\ir resources/Dialogs/Sequences/dialogs_dialog_id_seq.sql
\ir resources/Effects/Sequences/effect_nvps_2_nvp_id_seq.sql
\ir resources/Effects/Sequences/effects_effect_id_seq.sql
\ir resources/Entities/Sequences/entity_templates_template_id_seq.sql
\ir resources/Events/Sequences/event_sets_event_set_id_seq.sql
\ir resources/Events/Sequences/paths_path_id_seq.sql
\ir resources/Events/Sequences/point_set_points_point_id_seq.sql
\ir resources/Events/Sequences/point_sets_set_id_seq.sql
\ir resources/Events/Sequences/sequences_kismet_event_set_seq_id_seq.sql
\ir resources/Items/Sequences/item_list_items_item_id_seq.sql
\ir resources/Items/Sequences/item_lists_item_list_id_seq.sql
\ir resources/Items/Sequences/items_event_sets_2_item_event_id_seq.sql
\ir resources/Items/Sequences/items_item_id_seq.sql
\ir resources/Loot/Sequences/loot_loot_id_seq.sql
\ir resources/Loot/Sequences/loot_tables_loot_table_id_seq.sql
\ir resources/Missions/Sequences/mission_reward_groups_group_id_seq.sql
\ir resources/Missions/Sequences/mission_rewards_reward_id_seq.sql
\ir resources/Missions/Sequences/missions_mission_id_seq.sql
\ir resources/Worlds/Sequences/entity_interactions_entity_interaction_id_seq.sql
\ir resources/Worlds/Sequences/generic_regions_region_id_seq.sql
\ir resources/Worlds/Sequences/ring_transport_regions_region_id_seq.sql
\ir resources/Worlds/Sequences/spawn_points_point_id_seq.sql
\ir resources/Worlds/Sequences/spawn_sets_set_id_seq.sql
\ir resources/Worlds/Sequences/spawnlist_spawn_id_seq.sql
\ir resources/Worlds/Sequences/stargates_id_seq.sql

-- Tables
\ir resources/Abilities/Tables/abilities.sql
\ir resources/Abilities/Tables/ability_moniker_groups.sql
\ir resources/Abilities/Tables/ability_set_abilities.sql
\ir resources/Abilities/Tables/ability_sets.sql
\ir resources/Abilities/Tables/applied_science.sql
\ir resources/Abilities/Tables/trainer_abilities.sql
\ir resources/Abilities/Tables/trainer_ability_lists.sql
\ir resources/Archetypes/Tables/archetype_ability_tree.sql
\ir resources/Archetypes/Tables/archetypes.sql
\ir resources/Archetypes/Tables/char_creation.sql
\ir resources/Archetypes/Tables/char_creation_abilities.sql
\ir resources/Archetypes/Tables/char_creation_choices.sql
\ir resources/Archetypes/Tables/char_creation_visgroups.sql
\ir resources/Archetypes/Tables/disciplines.sql
\ir resources/Archetypes/Tables/racial_paradigm.sql
\ir resources/Dialogs/Tables/dialog_screen_buttons.sql
\ir resources/Dialogs/Tables/dialog_screens.sql
\ir resources/Dialogs/Tables/dialog_set_maps.sql
\ir resources/Dialogs/Tables/dialog_sets.sql
\ir resources/Dialogs/Tables/dialogs.sql
\ir resources/Dialogs/Tables/speakers.sql
\ir resources/Dialogs/Tables/special_words.sql
\ir resources/Effects/Tables/effect_nvps.sql
\ir resources/Effects/Tables/effects.sql
\ir resources/Entities/Tables/blueprints.sql
\ir resources/Entities/Tables/blueprints_components.sql
\ir resources/Entities/Tables/entity_templates.sql
\ir resources/Entities/Tables/monikers.sql
\ir resources/Entities/Tables/resource_types.sql
\ir resources/Entities/Tables/resource_versions.sql
\ir resources/Events/Tables/event_sets.sql
\ir resources/Events/Tables/event_sets_sequences.sql
\ir resources/Events/Tables/paths.sql
\ir resources/Events/Tables/point_set_points.sql
\ir resources/Events/Tables/point_sets.sql
\ir resources/Events/Tables/sequences.sql
\ir resources/Events/Tables/sequences_nvp.sql
\ir resources/Items/Tables/containers.sql
\ir resources/Items/Tables/item_list_items.sql
\ir resources/Items/Tables/item_list_prices.sql
\ir resources/Items/Tables/item_lists.sql
\ir resources/Items/Tables/items.sql
\ir resources/Items/Tables/items_event_sets.sql
\ir resources/Loot/Tables/loot.sql
\ir resources/Loot/Tables/loot_tables.sql
\ir resources/Missions/Tables/mission_objectives.sql
\ir resources/Missions/Tables/mission_reward_groups.sql
\ir resources/Missions/Tables/mission_rewards.sql
\ir resources/Missions/Tables/mission_steps.sql
\ir resources/Missions/Tables/mission_tasks.sql
\ir resources/Missions/Tables/missions.sql
\ir resources/Texts/Tables/error_texts.sql
\ir resources/Texts/Tables/texts.sql
\ir resources/Visuals/Tables/body_component_visuals.sql
\ir resources/Visuals/Tables/body_components.sql
\ir resources/Visuals/Tables/body_sets.sql
\ir resources/Visuals/Tables/skeletal_meshes.sql
\ir resources/Visuals/Tables/static_meshes.sql
\ir resources/Worlds/Tables/entity_interactions.sql
\ir resources/Worlds/Tables/generic_regions.sql
\ir resources/Worlds/Tables/interactions.sql
\ir resources/Worlds/Tables/respawners.sql
\ir resources/Worlds/Tables/ring_transport_regions.sql
\ir resources/Worlds/Tables/spawn_points.sql
\ir resources/Worlds/Tables/spawn_sets.sql
\ir resources/Worlds/Tables/spawnlist.sql
\ir resources/Worlds/Tables/stargates.sql
\ir resources/Worlds/Tables/worlds.sql

\ir resources/_sequence_ownership.sql

\ir resources/_primary_keys.sql

\ir resources/_foreign_keys.sql

\ir resources/_indexes.sql

\ir resources/_functions.sql

-- Seed data
\ir resources/Abilities/Seed/abilities.sql
\ir resources/Abilities/Seed/ability_moniker_groups.sql
\ir resources/Abilities/Seed/ability_set_abilities.sql
\ir resources/Abilities/Seed/ability_sets.sql
\ir resources/Abilities/Seed/applied_science.sql
\ir resources/Abilities/Seed/trainer_abilities.sql
\ir resources/Abilities/Seed/trainer_ability_lists.sql
\ir resources/Archetypes/Seed/archetype_ability_tree.sql
\ir resources/Archetypes/Seed/archetypes.sql
\ir resources/Archetypes/Seed/char_creation.sql
\ir resources/Archetypes/Seed/char_creation_abilities.sql
\ir resources/Archetypes/Seed/char_creation_choices.sql
\ir resources/Archetypes/Seed/char_creation_visgroups.sql
\ir resources/Archetypes/Seed/disciplines.sql
\ir resources/Archetypes/Seed/racial_paradigm.sql
\ir resources/Dialogs/Seed/dialog_screen_buttons.sql
\ir resources/Dialogs/Seed/dialog_screens.sql
\ir resources/Dialogs/Seed/dialog_set_maps.sql
\ir resources/Dialogs/Seed/dialog_sets.sql
\ir resources/Dialogs/Seed/dialogs.sql
\ir resources/Dialogs/Seed/speakers.sql
\ir resources/Dialogs/Seed/special_words.sql
\ir resources/Effects/Seed/effect_nvps.sql
\ir resources/Effects/Seed/effects.sql
\ir resources/Entities/Seed/blueprints.sql
\ir resources/Entities/Seed/blueprints_components.sql
\ir resources/Entities/Seed/entity_templates.sql
\ir resources/Entities/Seed/monikers.sql
\ir resources/Entities/Seed/resource_types.sql
\ir resources/Entities/Seed/resource_versions.sql
\ir resources/Events/Seed/event_sets.sql
\ir resources/Events/Seed/event_sets_sequences.sql
\ir resources/Events/Seed/paths.sql
\ir resources/Events/Seed/point_set_points.sql
\ir resources/Events/Seed/point_sets.sql
\ir resources/Events/Seed/sequences.sql
\ir resources/Events/Seed/sequences_nvp.sql
\ir resources/Items/Seed/containers.sql
\ir resources/Items/Seed/item_list_items.sql
\ir resources/Items/Seed/item_list_prices.sql
\ir resources/Items/Seed/item_lists.sql
\ir resources/Items/Seed/items.sql
\ir resources/Items/Seed/items_event_sets.sql
\ir resources/Loot/Seed/loot.sql
\ir resources/Loot/Seed/loot_tables.sql
\ir resources/Missions/Seed/mission_objectives.sql
\ir resources/Missions/Seed/mission_reward_groups.sql
\ir resources/Missions/Seed/mission_rewards.sql
\ir resources/Missions/Seed/mission_steps.sql
\ir resources/Missions/Seed/mission_tasks.sql
\ir resources/Missions/Seed/missions.sql
\ir resources/Texts/Seed/error_texts.sql
\ir resources/Texts/Seed/texts.sql
\ir resources/Visuals/Seed/body_component_visuals.sql
\ir resources/Visuals/Seed/body_components.sql
\ir resources/Visuals/Seed/body_sets.sql
\ir resources/Visuals/Seed/skeletal_meshes.sql
\ir resources/Visuals/Seed/static_meshes.sql
\ir resources/Worlds/Seed/entity_interactions.sql
\ir resources/Worlds/Seed/generic_regions.sql
\ir resources/Worlds/Seed/interactions.sql
\ir resources/Worlds/Seed/respawners.sql
\ir resources/Worlds/Seed/ring_transport_regions.sql
\ir resources/Worlds/Seed/spawn_points.sql
\ir resources/Worlds/Seed/spawn_sets.sql
\ir resources/Worlds/Seed/spawnlist.sql
\ir resources/Worlds/Seed/stargates.sql
\ir resources/Worlds/Seed/worlds.sql

\ir resources/_triggers.sql


-- ════════════════════════════════════════════════════════════════
-- public schema  (cross-schema FKs to resources are safe here)
-- ════════════════════════════════════════════════════════════════

\ir sgw/_schema.sql

-- Types
\ir sgw/Accounts/Types/player_interaction_map.sql

-- Sequences
\ir sgw/Accounts/Sequences/accounts_account_id_seq.sql
\ir sgw/Inventory/Sequences/sgw_inventory_base_item_id_seq.sql
\ir sgw/Inventory/Sequences/sgw_inventory_item_id_seq.sql
\ir sgw/Mail/Sequences/sgw_gate_mail_mail_id_seq.sql
\ir sgw/Players/Sequences/sgw_characters_character_id_seq.sql

-- Tables
\ir sgw/Accounts/Tables/account.sql
\ir sgw/Inventory/Tables/sgw_inventory_base.sql
\ir sgw/Inventory/Tables/sgw_inventory.sql
\ir sgw/Mail/Tables/sgw_gate_mail.sql
\ir sgw/Missions/Tables/sgw_mission.sql
\ir sgw/Players/Tables/sgw_player.sql
\ir sgw/Shards/Tables/shards.sql

\ir sgw/_sequence_ownership.sql

\ir sgw/_primary_keys.sql

\ir sgw/_foreign_keys.sql

\ir sgw/_indexes.sql

-- Seed data
\ir sgw/Accounts/Seed/account.sql
\ir sgw/Inventory/Seed/sgw_inventory.sql
\ir sgw/Inventory/Seed/sgw_inventory_base.sql
\ir sgw/Mail/Seed/sgw_gate_mail.sql
\ir sgw/Players/Seed/sgw_player.sql
\ir sgw/Shards/Seed/shards.sql

