//! Surface I: `crate::names::defs`, the method-name tables, are generated
//! from `entities/` by this test, so a name can never be typed by hand.
//!
//! The test renders the four files under `crates/wire/src/names/defs/` from
//! [`client_classes`] and [`flatten`] and fails when the committed files
//! differ. After a `.def` or `entities.xml` change, regenerate them:
//!
//! ```text
//! CIMMERIA_REGEN_NAMES=1 bash tools/build-lane/lane.sh cargo test -p cimmeria-wire names_codegen
//! ```
//!
//! A table that is a prefix of a longer one (SGWPlayer of SGWGmPlayer,
//! SGWMob of SGWPet) is emitted as a slice of it rather than a second copy.

use std::fmt::Write as _;

use super::flatten::{client_classes, flatten, Section};
use super::source::crate_file;

/// Where the generated files live, from `crates/`.
const OUT_DIR: &str = "wire/src/names/defs";
/// Set to regenerate instead of compare.
const REGEN_ENV: &str = "CIMMERIA_REGEN_NAMES";

const HEADER: &str = "\
// GENERATED by `mercury::def_conformance::names_codegen` from
// `entities/entities.xml` and `entities/defs/`. Do not edit by hand; after a
// `.def` change run
// `CIMMERIA_REGEN_NAMES=1 bash tools/build-lane/lane.sh cargo test -p cimmeria-wire names_codegen`.
";

/// `SGWGmPlayer` -> `SGW_GM_PLAYER`, `Account` -> `ACCOUNT`.
fn const_name(class: &str) -> String {
    let chars: Vec<char> = class.chars().collect();
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        let prev_lower = i > 0 && chars[i - 1].is_ascii_lowercase();
        let acronym_end = i > 0
            && chars[i - 1].is_ascii_uppercase()
            && chars.get(i + 1).is_some_and(char::is_ascii_lowercase);
        if c.is_ascii_uppercase() && (prev_lower || acronym_end) {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

/// One section's file: every non-empty class table, longest first, with a
/// table that is a prefix of an earlier one emitted as a slice of it.
fn render_section(section: Section, doc: &str, classes: &[(u8, String)]) -> String {
    let mut tables: Vec<(String, Vec<String>)> = classes
        .iter()
        .map(|(_, name)| (const_name(name), flatten(name, section)))
        .filter(|(_, t)| !t.is_empty())
        .collect();
    // Longest first so a prefix finds its parent; ties keep document order.
    tables.sort_by_key(|(_, t)| std::cmp::Reverse(t.len()));

    let mut out = format!("{HEADER}\n//! {doc}\n");
    let mut emitted: Vec<(String, Vec<String>)> = Vec::new();
    for (name, table) in tables {
        let parent = emitted
            .iter()
            .find(|(_, longer)| longer.starts_with(&table))
            .map(|(p, _)| p.clone());
        match parent {
            Some(parent) => writeln!(
                out,
                "\npub(super) const {name}: &[&str] = {parent}.split_at({}).0;",
                table.len()
            ),
            None => {
                let mut body = String::new();
                for (i, method) in table.iter().enumerate() {
                    writeln!(body, "    \"{method}\", // {i}").unwrap();
                }
                writeln!(out, "\npub(super) const {name}: &[&str] = &[\n{body}];")
            }
        }
        .unwrap();
        emitted.push((name, table));
    }
    out
}

/// `defs/mod.rs`: the class list and the per-section lookups.
fn render_mod(classes: &[(u8, String)]) -> String {
    let mut out = format!(
        "{HEADER}\n\
         //! The flattened method tables of every client-visible entity type,\n\
         //! keyed by clientIndex (the wire typeID; `<ServerOnly/>` entries take\n\
         //! none). Read through `crate::names`.\n\n\
         // One name per line with its index; rustfmt would re-align the index\n\
         // comments and fail the generated-file check, so it skips them.\n\
         #[rustfmt::skip]\nmod base;\n#[rustfmt::skip]\nmod cell;\n#[rustfmt::skip]\nmod client;\n\n\
         /// Every client-visible entity type: its clientIndex and its name.\n\
         pub(super) const CLASSES: [(u8, &str); {}] = [\n",
        classes.len()
    );
    for (index, name) in classes {
        writeln!(out, "    ({index:#04x}, \"{name}\"),").unwrap();
    }
    out.push_str("];\n");
    for (section, module, what) in [
        (
            Section::Client,
            "client",
            "ClientMethods (server to client)",
        ),
        (
            Section::Cell,
            "cell",
            "exposed CellMethods (client to cell)",
        ),
        (
            Section::Base,
            "base",
            "exposed BaseMethods (client to base)",
        ),
    ] {
        writeln!(
            out,
            "\n/// The flattened {what} of entity type `class_id`, by method index.\n\
             pub(super) fn {module}_methods(class_id: u8) -> &'static [&'static str] {{\n    \
             match class_id {{"
        )
        .unwrap();
        for (index, name) in classes {
            if !flatten(name, section).is_empty() {
                writeln!(
                    out,
                    "        {index:#04x} => {module}::{},",
                    const_name(name)
                )
                .unwrap();
            }
        }
        out.push_str("        _ => &[],\n    }\n}\n");
    }
    out
}

/// Every generated file, as `(path from crates/, contents)`.
fn render_all() -> Vec<(String, String)> {
    let classes = client_classes();
    vec![
        (format!("{OUT_DIR}/mod.rs"), render_mod(&classes)),
        (
            format!("{OUT_DIR}/client.rs"),
            render_section(
                Section::Client,
                "ClientMethods (server to client), flattened per entity type.",
                &classes,
            ),
        ),
        (
            format!("{OUT_DIR}/cell.rs"),
            render_section(
                Section::Cell,
                "Exposed CellMethods (client to cell), flattened per entity type.",
                &classes,
            ),
        ),
        (
            format!("{OUT_DIR}/base.rs"),
            render_section(
                Section::Base,
                "Exposed BaseMethods (client to base), flattened per entity type.",
                &classes,
            ),
        ),
    ]
}

/// Git may check the committed files out with CRLF line endings.
fn normalize_newlines(text: &str) -> String {
    text.replace("\r\n", "\n")
}

#[test]
fn names_codegen_tables_match_entities_defs() {
    let regen = std::env::var_os(REGEN_ENV).is_some();
    let mut stale = Vec::new();
    for (rel, want) in render_all() {
        let path = crate_file(&rel);
        if regen {
            std::fs::write(&path, &want)
                .unwrap_or_else(|e| panic!("writing {}: {e}", path.display()));
            continue;
        }
        let have = std::fs::read_to_string(&path).unwrap_or_default();
        if normalize_newlines(&have) != want {
            stale.push(rel);
        }
    }
    assert!(
        stale.is_empty(),
        "generated method-name tables are stale against entities/defs: {stale:?}\n\
         regenerate: {REGEN_ENV}=1 bash tools/build-lane/lane.sh cargo test -p cimmeria-wire names_codegen"
    );
}

#[test]
fn const_names_split_camel_case_and_acronyms() {
    assert_eq!(const_name("SGWGmPlayer"), "SGW_GM_PLAYER");
    assert_eq!(const_name("SGWSpawnableEntity"), "SGW_SPAWNABLE_ENTITY");
    assert_eq!(const_name("Account"), "ACCOUNT");
}

/// The clientIndex list the tables are keyed by: Account is 0x07 because
/// ServerOnly SGWBlackMarket takes no index.
#[test]
fn client_classes_skip_server_only_entities() {
    let classes = client_classes();
    let names: Vec<&str> = classes.iter().map(|(_, n)| n.as_str()).collect();
    assert_eq!(
        names,
        [
            "SGWSpawnableEntity",
            "SGWBeing",
            "SGWPlayer",
            "SGWGmPlayer",
            "SGWMob",
            "SGWPet",
            "SGWDuelMarker",
            "Account"
        ]
    );
    assert_eq!(classes[7].0, 0x07);
}
