# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import EffectScript

class Reload(EffectScript):
	def onEffectInit(self):
		self.n20_trigger_In()

	n3_var_Player = None
	def n9_trigger_In(self):
		if self.n9_var_Entity:
			stat = self.n9_var_Entity.getStat((self.n9_var_Stat_Id or 49))
			self.n9_var_Max = stat.max
			self.n10_var_Current = self.n9_var_Max
			if self.n10_var_Entity:
				stat = self.n10_var_Entity.getStat((self.n10_var_Stat_Id or 49))
				stat.setCurrent(self.n10_var_Current)
				self.n10_var_Entity.sendDirtyStats()

	n9_var_Entity = None
	n9_var_Stat_Id = None
	n9_var_Max = None
	n10_var_Entity = None
	n10_var_Stat_Id = None
	n10_var_Current = None
	def n20_trigger_In(self):
		if self.n20_var_Entity is not None:
			self.n20_var_Ammo_Stat_Id = self.n20_var_Entity.getAmmoStat()
			self.n9_var_Stat_Id = self.n20_var_Ammo_Stat_Id
			self.n10_var_Stat_Id = self.n20_var_Ammo_Stat_Id
			self.n9_trigger_In()

	n20_var_Ammo_Stat_Id = None
	n20_var_Entity = None
	def __init__(self, owner, effect, nvps):
		EffectScript.__init__(self, owner, effect, nvps)
		self.n3_var_Player = self.owner
		self.n9_var_Entity = self.n3_var_Player
		self.n10_var_Entity = self.n3_var_Player
		self.n20_var_Entity = self.n3_var_Player

