# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class test(Script):
	n5_var_Stargate_Id = None
	n6_var_Integer = None
	n7_var_Integer = None
	n8_var_Integer = None
	n9_var_Integer = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def loaded(args):
			self.owner.debug('EVENT TEST - Player Loaded')
		self.n1_lvar_SubscriptionId = self.owner.subscribe("player.loaded", loaded)
		self.owner.debug('EVENT TEST - Script Loaded')
		def makeGateCb(args):
			self.n5_var_Stargate_Id = args['stargateId']
			self.n9_var_Integer = self.n5_var_Stargate_Id
			self.n8_var_Integer = self.n5_var_Stargate_Id
			self.n6_var_Integer = self.n5_var_Stargate_Id
			self.n7_var_Integer = self.n5_var_Stargate_Id
			self.owner.debug('EVENT TEST - Make Gate')
			self.owner.debug(str(self.n7_var_Integer))
		self.n5_lvar_MakeGateSubscriptionId = self.owner.subscribe("stargate::make", makeGateCb, once = False)
		def makeGateFailedCb(args):
			self.n5_var_Stargate_Id = args['stargateId']
			self.n9_var_Integer = self.n5_var_Stargate_Id
			self.n8_var_Integer = self.n5_var_Stargate_Id
			self.n6_var_Integer = self.n5_var_Stargate_Id
			self.n7_var_Integer = self.n5_var_Stargate_Id
			self.owner.debug('EVENT TEST - Make Gate Failed')
			self.owner.debug(str(self.n6_var_Integer))
		self.n5_lvar_MakeGateFailedSubscriptionId = self.owner.subscribe("stargate::makefailed", makeGateFailedCb, once = False)
		def destroyGateCb(args):
			self.n5_var_Stargate_Id = args['stargateId']
			self.n9_var_Integer = self.n5_var_Stargate_Id
			self.n8_var_Integer = self.n5_var_Stargate_Id
			self.n6_var_Integer = self.n5_var_Stargate_Id
			self.n7_var_Integer = self.n5_var_Stargate_Id
			self.owner.debug('EVENT TEST - Destroy Gate')
			self.owner.debug(str(self.n8_var_Integer))
		self.n5_lvar_DestroyGateSubscriptionId = self.owner.subscribe("stargate::destroy", destroyGateCb, once = False)
		def gatePassageCb(args):
			self.n5_var_Stargate_Id = args['stargateId']
			self.n9_var_Integer = self.n5_var_Stargate_Id
			self.n8_var_Integer = self.n5_var_Stargate_Id
			self.n6_var_Integer = self.n5_var_Stargate_Id
			self.n7_var_Integer = self.n5_var_Stargate_Id
			self.owner.debug('EVENT TEST - Gate Passage')
			self.owner.debug(str(self.n9_var_Integer))
		self.n5_lvar_GatePassageSubscriptionId = self.owner.subscribe("stargate::passage", gatePassageCb, once = False)
		def acceptedCb(args):
			self.owner.debug('EVENT TEST - Mission Started')
			return True
		self.n10_lvar_AcceptedId = self.owner.subscribe("mission.accepted::" + str(1627), acceptedCb, once = False)
		def completedCb(args):
			self.owner.debug('EVENT TEST - Mission Completed')
			return True
		self.n10_lvar_CompletedId = self.owner.subscribe("mission.completed::" + str(1627), completedCb, once = False)
		def failedCb(args):
			self.owner.debug('EVENT TEST - Mission Failed')
			return True
		self.n10_lvar_FailedId = self.owner.subscribe("mission.failed::" + str(1627), failedCb, once = False)
		def rewardsCb(args):
			self.owner.debug('EVENT TEST - Mission Rewards Chosen')
			return True
		self.n10_lvar_RewardsId = self.owner.subscribe("mission.rewards_chosen::" + str(1627), rewardsCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n5_lvar_MakeGateSubscriptionId)
		self.owner.unsubscribe(self.n5_lvar_MakeGateFailedSubscriptionId)
		self.owner.unsubscribe(self.n5_lvar_DestroyGateSubscriptionId)
		self.owner.unsubscribe(self.n5_lvar_GatePassageSubscriptionId)
		self.owner.unsubscribe(self.n10_lvar_AcceptedId)
		self.owner.unsubscribe(self.n10_lvar_CompletedId)
		self.owner.unsubscribe(self.n10_lvar_FailedId)
		self.owner.unsubscribe(self.n10_lvar_RewardsId)

