//! `012-gm-slash-commands`: the committed zip, the XML inside it, and the rule
//! that the XML carries no CME-authored text.
//!
//! The stock 2009 client reads `Common/xml/slash_commands/InternalSlashCommands.xml`
//! at startup (`LaunchMisc__InitContentSystems` 0x0041f9c0, path from
//! `SlashCommandXMLPath` in GameplayEngine.ini). A launcher install lacks it,
//! so the client's command map has no `/gm*` entries and every one answers
//! "Invalid command.". The file is generated by
//! `tools/client-patches/gm_slash_commands.py` from `commands.toml`.
//!
//! What the client's parser demands (SGW.exe, gSOAP-generated, Ghidra
//! 2026-10-05): root `CommandList`; `Command` elements with the required
//! attributes `CommandName`, `EventName`, `Description`, `Usage` and the
//! optional `Access`, all in the `slash_commands` namespace; then
//! `MandatoryParam` elements followed by `OptionalParam` elements, each with
//! `PType`, `ParamName`, `ParamDescription`.

use std::collections::{BTreeMap, HashSet};
use std::io::Read;
use std::path::{Path, PathBuf};

use quick_xml::events::Event;
use quick_xml::Reader;

use crate::sha256_hex;

const XML_PATH: &str = "Common/xml/slash_commands/InternalSlashCommands.xml";
const NAMESPACE: &str = "http://www.cheyenneme.com/common/slash_commands";
/// The role letters the client's Access parser tests, in bit order
/// (SGW.exe 0x00a4c530).
const ROLE_LETTERS: &str = "gcCqQadDpm";
/// Commands the table registers (the QA tree's 164 entries, minus the two
/// words it defines twice, which the client's map folds into one).
const COMMAND_COUNT: usize = 162;

fn patch_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../data/client-patches")
}

#[derive(Debug, Clone)]
struct Param {
    tag: String,
    ptype: String,
    name: String,
    description: String,
}

#[derive(Debug, Clone)]
struct Command {
    word: String,
    access: Option<String>,
    description: String,
    event: String,
    usage: String,
    params: Vec<Param>,
}

/// Everything in the file that is a string a reader could take for prose.
#[derive(Debug, Default)]
struct Parsed {
    commands: Vec<Command>,
    comments: Vec<String>,
    root_attrs: BTreeMap<String, String>,
    stray_text: Vec<String>,
}

fn attrs(e: &quick_xml::events::BytesStart<'_>) -> BTreeMap<String, String> {
    e.attributes()
        .map(|a| {
            let a = a.expect("well-formed attribute");
            (
                String::from_utf8(a.key.as_ref().to_vec()).unwrap(),
                a.normalized_value(quick_xml::XmlVersion::Explicit1_0)
                    .expect("valid escapes")
                    .into_owned(),
            )
        })
        .collect()
}

fn parse(xml: &str) -> Parsed {
    let mut reader = Reader::from_str(xml);
    let mut out = Parsed::default();
    let mut open: Option<Command> = None;
    let mut depth_root = false;
    loop {
        match reader.read_event().expect("the XML parses") {
            Event::Eof => break,
            Event::Decl(_) => {}
            Event::Comment(c) => out.comments.push(String::from_utf8_lossy(&c).into_owned()),
            Event::Text(t) => {
                let s = String::from_utf8_lossy(&t).into_owned();
                if !s.trim().is_empty() {
                    out.stray_text.push(s);
                }
            }
            Event::Start(e) => match e.name().as_ref() {
                b"CommandList" => {
                    depth_root = true;
                    out.root_attrs = attrs(&e);
                }
                b"scmd:Command" => {
                    assert!(depth_root && open.is_none(), "Command outside the list");
                    let a = attrs(&e);
                    let get = |k: &str| a.get(&format!("scmd:{k}")).cloned();
                    let known = ["CommandName", "Access", "Description", "EventName", "Usage"];
                    for k in a.keys() {
                        assert!(
                            known.iter().any(|n| k == &format!("scmd:{n}")),
                            "unexpected Command attribute {k}"
                        );
                    }
                    open = Some(Command {
                        word: get("CommandName").expect("CommandName is required"),
                        access: get("Access"),
                        description: get("Description").expect("Description is required"),
                        event: get("EventName").expect("EventName is required"),
                        usage: get("Usage").expect("Usage is required"),
                        params: Vec::new(),
                    });
                }
                other => panic!("unexpected element {}", String::from_utf8_lossy(other)),
            },
            Event::Empty(e) => {
                let name = String::from_utf8_lossy(e.name().as_ref()).into_owned();
                let tag = match name.as_str() {
                    "scmd:MandatoryParam" => "MandatoryParam",
                    "scmd:OptionalParam" => "OptionalParam",
                    "scmd:Command" => panic!("a Command with no body is not generated"),
                    other => panic!("unexpected element {other}"),
                };
                let a = attrs(&e);
                let keys: Vec<&str> = a.keys().map(String::as_str).collect();
                assert_eq!(
                    keys,
                    // BTreeMap order.
                    ["scmd:PType", "scmd:ParamDescription", "scmd:ParamName"]
                        .iter()
                        .copied()
                        .collect::<std::collections::BTreeSet<_>>()
                        .into_iter()
                        .collect::<Vec<_>>(),
                    "param attributes"
                );
                open.as_mut()
                    .expect("param outside a Command")
                    .params
                    .push(Param {
                        tag: tag.into(),
                        ptype: a["scmd:PType"].clone(),
                        name: a["scmd:ParamName"].clone(),
                        description: a["scmd:ParamDescription"].clone(),
                    });
            }
            Event::End(e) => match e.name().as_ref() {
                b"scmd:Command" => out.commands.push(open.take().expect("Command was open")),
                b"CommandList" => depth_root = false,
                other => panic!("unexpected end {}", String::from_utf8_lossy(other)),
            },
            other => panic!("unexpected XML event {other:?}"),
        }
    }
    out
}

fn committed_xml() -> String {
    String::from_utf8(
        std::fs::read(patch_dir().join("012-gm-slash-commands/InternalSlashCommands.xml")).unwrap(),
    )
    .unwrap()
}

fn parsed() -> Parsed {
    parse(&committed_xml())
}

/// The mask SGW.exe computes from an Access attribute: it asks the wstring for
/// each role letter's position and sets the bit when the answer is non-zero,
/// so the letter at position 0 is left out and every absent role is put in
/// (0x00a4c530 over `std::wstring::find`, 0x009e8b10 returning the index or
/// npos). A command is usable when its mask is 0 or shares a bit with the
/// player's access level (0x00c789e0 against the global at 0x01df2d44, which
/// `onEntityProperty(GENERICPROPERTY_AccessLevel = 7, level)` writes).
fn access_mask(access: &str) -> u32 {
    ROLE_LETTERS
        .chars()
        .enumerate()
        .filter(|(_, letter)| access.find(*letter) != Some(0))
        .fold(0, |mask, (bit, _)| mask | (1 << bit))
}

fn usable(mask: u32, access_level: u32) -> bool {
    mask == 0 || mask & access_level != 0
}

fn normalize(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_ascii_lowercase()
}

// ---- the zip --------------------------------------------------------------

/// The shipped zip is one whole file with exactly the bytes in the repo, no
/// recipe and no deltas (the stock client has nothing to diff against: the
/// file is new). A hand edit of the XML without a rebuilt zip fails here.
#[test]
fn committed_zip_carries_exactly_the_generated_xml() {
    let file = std::fs::File::open(patch_dir().join("012-gm-slash-commands.zip")).unwrap();
    let mut zip = zip::ZipArchive::new(file).unwrap();
    assert_eq!(zip.len(), 1, "the zip holds one file");
    let mut entry = zip.by_name(XML_PATH).unwrap();
    let mut bytes = Vec::new();
    entry.read_to_end(&mut bytes).unwrap();
    let source =
        std::fs::read(patch_dir().join("012-gm-slash-commands/InternalSlashCommands.xml")).unwrap();
    assert_eq!(
        sha256_hex(&bytes),
        sha256_hex(&source),
        "the zip must be rebuilt from the committed XML (cimmeria-patchset build)"
    );
}

/// The client's own XML is ASCII with CRLF; ours matches, so nothing about the
/// file depends on a checkout's line-ending conversion.
#[test]
fn xml_is_ascii_crlf() {
    let xml = committed_xml();
    assert!(xml.is_ascii());
    let lf = xml.matches('\n').count();
    assert_eq!(xml.matches("\r\n").count(), lf, "every newline is CRLF");
}

// ---- the schema -----------------------------------------------------------

#[test]
fn xml_follows_the_clients_schema() {
    let p = parsed();
    assert_eq!(
        p.root_attrs.get("xmlns").map(String::as_str),
        Some(NAMESPACE),
        "default namespace"
    );
    assert_eq!(
        p.root_attrs.get("xmlns:scmd").map(String::as_str),
        Some(NAMESPACE),
        "scmd namespace"
    );
    assert_eq!(p.commands.len(), COMMAND_COUNT);

    let mut words = HashSet::new();
    for c in &p.commands {
        // The client's map holds one entry per word; a duplicate would replace
        // the first without a sound.
        assert!(words.insert(c.word.as_str()), "{} is defined twice", c.word);
        assert!(
            c.word.starts_with("/gm") || c.word == "/debugminigamecomplete",
            "{} is not a GM command word",
            c.word
        );
        assert!(
            c.event.starts_with("Event_SlashCmd_"),
            "{}: {}",
            c.word,
            c.event
        );
        // The parser reads MandatoryParam elements first and OptionalParam
        // elements after, so a mandatory one behind an optional one would end
        // the Command early and fail the whole file.
        let first_optional = c.params.iter().position(|p| p.tag == "OptionalParam");
        if let Some(i) = first_optional {
            assert!(
                c.params[i..].iter().all(|p| p.tag == "OptionalParam"),
                "{}: a mandatory parameter follows an optional one",
                c.word
            );
        }
        for param in &c.params {
            assert!(
                ["Boolean", "Integer", "Float", "String"].contains(&param.ptype.as_str()),
                "{}: parameter type {}",
                c.word,
                param.ptype
            );
        }
    }
}

/// Spot checks of the commands the server implements, with the event class
/// the client fires and the parameter types it parses (the cell method's
/// argument types, `SGWGmPlayer.def`).
#[test]
fn registers_the_commands_the_server_handles() {
    let p = parsed();
    let by_word: BTreeMap<&str, &Command> =
        p.commands.iter().map(|c| (c.word.as_str(), c)).collect();
    let shape = |word: &str| {
        let c = by_word
            .get(word)
            .unwrap_or_else(|| panic!("{word} is not registered"));
        let params: Vec<String> = c
            .params
            .iter()
            .map(|p| format!("{} {}:{}", p.tag, p.ptype, p.name))
            .collect();
        (c.event.clone(), params)
    };
    assert_eq!(
        shape("/gmdhd"),
        (
            "Event_SlashCmd_DHD".to_string(),
            vec!["MandatoryParam Integer:DestinationId".to_string()]
        )
    );
    let (event, params) = shape("/gmgotoxyz");
    assert_eq!(event, "Event_SlashCmd_GotoXYZ");
    assert_eq!(params.len(), 3);
    assert!(params.iter().all(|p| p.contains(" Float:")), "{params:?}");
    let (event, params) = shape("/gmgivexp");
    assert_eq!(event, "Event_SlashCmd_GiveXp");
    assert_eq!(params.len(), 1);
    assert!(params[0].contains(" Integer:"), "{params:?}");
    assert_eq!(shape("/gmsendgmshout").0, "Event_SlashCmd_GMShout");
    // The two words the QA tree defines twice resolve to the later entry (the
    // class that exists in SGW.exe, no parameters); the earlier one names a
    // class the binary does not have.
    assert_eq!(
        shape("/gmaddbehavioreventset"),
        ("Event_SlashCmd_AddBehaviorEventSet".to_string(), vec![])
    );
    assert_eq!(
        shape("/gmremovebehavioreventset"),
        ("Event_SlashCmd_RemoveBehaviorEventSet".to_string(), vec![])
    );
    // The stock `SlashCommands.xml` owns the player commands; none moved here.
    for stock in [
        "/help", "/say", "/yell", "/tell", "/quit", "/logoff", "/pvp",
    ] {
        assert!(
            !by_word.contains_key(stock),
            "{stock} belongs to the stock file"
        );
    }
}

/// The client-side filter: every command is usable by a GM (access level 2)
/// and by every higher level, and unusable by a player (level 0). The server
/// still gates each GM method; this is only the client's own check.
#[test]
fn every_command_is_open_to_a_gm_and_closed_to_a_player() {
    let p = parsed();
    for c in &p.commands {
        let access = c.access.as_deref().unwrap_or("");
        assert!(
            !access.is_empty() && access.chars().all(|l| ROLE_LETTERS.contains(l)),
            "{}: Access {access:?}",
            c.word
        );
        let mask = access_mask(access);
        assert_eq!(mask, 0x2FF, "{}: mask for Access {access:?}", c.word);
        assert!(!usable(mask, 0), "{}: usable by a player", c.word);
        for level in 1..=4 {
            assert!(
                usable(mask, level),
                "{}: not usable at level {level}",
                c.word
            );
        }
    }
}

/// Pins the reading of the client's mask code that the Access choice rests on.
#[test]
fn access_mask_follows_the_clients_find_quirk() {
    assert_eq!(
        access_mask("p"),
        0x2FF,
        "the letter at position 0 is left out"
    );
    assert_eq!(access_mask("g"), 0x3FE);
    assert_eq!(access_mask(""), 0x3FF, "no letters: every role is 'absent'");
    assert!(!usable(0x2FF, 0));
    assert!(usable(0x2FF, 2), "access level 2 passes");
    assert!(usable(0, 0), "no Access attribute: everyone");
}

// ---- the docs agree -------------------------------------------------------

fn docs_command_rows() -> HashSet<String> {
    let docs = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/commands.md"),
    )
    .unwrap();
    docs.lines()
        .filter_map(|l| l.strip_prefix("| `/"))
        .filter_map(|l| l.split('`').next())
        .map(|w| format!("/{w}"))
        .collect()
}

/// `docs/commands.md` is the player-facing list: it names every command this
/// file registers, and every `/gm*` row it has is registered (a row for a word
/// the client does not know, like the old `/gmshout`, would promise a command
/// that answers "Invalid command.").
#[test]
fn docs_and_xml_name_the_same_gm_commands() {
    let docs = docs_command_rows();
    let words: HashSet<String> = parsed().commands.iter().map(|c| c.word.clone()).collect();
    let mut missing_in_docs: Vec<_> = words.difference(&docs).collect();
    missing_in_docs.sort();
    assert!(
        missing_in_docs.is_empty(),
        "registered but not in docs/commands.md: {missing_in_docs:?}"
    );
    let mut missing_in_xml: Vec<_> = docs
        .iter()
        .filter(|w| w.starts_with("/gm") && !words.contains(*w))
        .collect();
    missing_in_xml.sort();
    assert!(
        missing_in_xml.is_empty(),
        "in docs/commands.md but not registered: {missing_in_xml:?}"
    );
}

// ---- no CME-authored text -------------------------------------------------

/// Every string value in the file is a name or a mechanical build from names.
/// No description, no parameter description, no prose comment: a file with
/// none of those fields filled in cannot carry CME's sentences.
#[test]
fn xml_has_no_prose_fields() {
    let p = parsed();
    assert!(
        p.stray_text.is_empty(),
        "text between elements: {:?}",
        p.stray_text
    );
    assert_eq!(
        p.comments,
        [
            " Generated by tools/client-patches/gm_slash_commands.py from \
          data/client-patches/012-gm-slash-commands/commands.toml. Do not edit by hand. "
        ],
        "the one comment is the generated-file note"
    );
    let word = |s: &str, extra: &str| {
        !s.is_empty()
            && s.chars()
                .all(|c| c.is_ascii_alphanumeric() || extra.contains(c))
    };
    for c in &p.commands {
        assert!(
            c.description.is_empty(),
            "{}: Description {:?}",
            c.word,
            c.description
        );
        assert!(word(&c.word, "/"), "{}", c.word);
        assert!(word(&c.event, "_"), "{}", c.event);
        let mut usage = vec![c.word.clone()];
        for param in &c.params {
            assert!(param.description.is_empty(), "{}: ParamDescription", c.word);
            assert!(
                word(&param.name, "-/"),
                "{}: ParamName {:?}",
                c.word,
                param.name
            );
            usage.push(if param.tag == "MandatoryParam" {
                format!("<{}>", param.name)
            } else {
                format!("[{}]", param.name)
            });
        }
        assert_eq!(
            c.usage,
            usage.join(" "),
            "{}: Usage is built from the names",
            c.word
        );
    }
}

/// Hashes of every description, parameter description and comment line in the
/// QA client's three slash-command files (`cme-prose.sha256`, written by
/// `tools/client-patches/cme_prose_hashes.py`). No multi-word string in our
/// file may match one, so a CME sentence pasted into the XML, or into the
/// table that generates it, fails in CI without the repository holding the
/// sentence.
#[test]
fn xml_contains_none_of_cmes_prose() {
    let hashes: HashSet<String> =
        std::fs::read_to_string(patch_dir().join("012-gm-slash-commands/cme-prose.sha256"))
            .unwrap()
            .lines()
            .map(str::to_string)
            .collect();
    assert!(hashes.len() > 200, "the hash list is missing or truncated");

    let p = parsed();
    let mut strings: Vec<String> = p.comments.clone();
    for c in &p.commands {
        strings.extend([c.description.clone(), c.usage.clone()]);
        for param in &c.params {
            strings.push(param.description.clone());
        }
    }
    for s in strings {
        let n = normalize(&s);
        if n.contains(' ') {
            assert!(
                !hashes.contains(&sha256_hex(n.as_bytes())),
                "{s:?} is a string from CME's slash-command files"
            );
        }
        // Each comment line, as the hash list holds them.
        for line in s.lines() {
            let n = normalize(line);
            assert!(
                !hashes.contains(&sha256_hex(n.as_bytes())),
                "{line:?} is a string from CME's slash-command files"
            );
        }
    }
}

/// The same check against the real client files, where one is available, with
/// the sentences themselves: no description, parameter description or comment
/// line of 8+ characters from any of the three files appears anywhere in our
/// XML. `SGW_QA_CLIENT` is the client install root (the folder holding
/// `Common` and `Working`). Run with
/// `cargo test -p cimmeria-patchset qa_prose -- --ignored`.
#[test]
#[ignore = "needs a client install (SGW_QA_CLIENT)"]
fn qa_prose_is_absent_from_the_xml() {
    let Some(root) = std::env::var_os("SGW_QA_CLIENT") else {
        panic!("set SGW_QA_CLIENT to a client install root");
    };
    let dir = PathBuf::from(root).join("Common/xml/slash_commands");
    let ours = normalize(&committed_xml());
    let mut checked = 0;
    for name in [
        "SlashCommands.xml",
        "InternalSlashCommands.xml",
        "FinalSlashCommands.xml",
    ] {
        let raw = std::fs::read_to_string(dir.join(name)).unwrap();
        let mut prose: Vec<String> = Vec::new();
        for key in ["scmd:Description=\"", "scmd:ParamDescription=\""] {
            for part in raw.split(key).skip(1) {
                prose.push(part.split('"').next().unwrap().to_string());
            }
        }
        for part in raw.split("<!--").skip(1) {
            let comment = part.split("-->").next().unwrap();
            prose.push(comment.to_string());
            prose.extend(comment.lines().map(str::to_string));
        }
        for s in prose {
            let n = normalize(&s);
            // Markup in a comment (the commented-out command template) is
            // schema syntax every file of this format shares, not prose.
            if n.len() >= 8 && !n.contains('<') {
                assert!(!ours.contains(&n), "{name}: {s:?} appears in our XML");
                checked += 1;
            }
        }
    }
    assert!(checked > 50, "only {checked} strings checked");
}
