//! Wavefront OBJ writer for chunk geometry.
//!
//! Output format matches what the C++ NavBuilder's `Mesh::loadOBJ`
//! parses in `deprecated/cpp/src/nav_builder/mesh.cpp`:
//!
//! - Comment lines start with `#`.
//! - Group/object lines start with `o ` — NavBuilder uses the leading
//!   `o Terrain_*` to skip terrain groups via a hardcoded prefix
//!   check (`mesh.cpp:88-96`). The extractor honours that convention
//!   so a future "navmesh from non-terrain only" rebuild is one
//!   group-rename away.
//! - Vertex lines: `v <x> <y> <z>` — three space-separated floats.
//! - Face lines: `f <a> <b> <c>` — three 1-based vertex indices.
//!   NavBuilder strips any `/<vt>/<vn>` suffixes if present (it
//!   tokenises on `0123456789-./`), but the simplest emitter writes
//!   bare indices.
//!
//! # Axis convention — known unknown
//!
//! NavBuilder's `loadOBJ` does the swizzle on read:
//!
//! ```text
//! v.x = obj_z / 100.0;
//! v.y = obj_y / 100.0;
//! v.z = obj_x / 100.0;
//! ```
//!
//! Two pieces of intent are buried in that pattern:
//!
//! 1. The `/ 100.0` converts UE3 centimetres to BW post-divide units
//!    (`100 cm == 1 BW unit`).
//! 2. The `(x, y, z) → (z, y, x)` rearrangement flips between UE3's
//!    Z-up coordinate system and BW's Y-up.
//!
//! The right behaviour for the extractor is therefore to write OBJ
//! lines as `v <ue3_x_cm> <ue3_y_cm> <ue3_z_cm>` — i.e., emit raw UE3
//! cm coords and let NavBuilder do the swizzle. That keeps the OBJ
//! file readable by any UE3-aware tool and avoids double-swizzling.
//!
//! **However**, the original C++ map exporter that produced the now-
//! defunct OBJs is no longer in the tree, so the cube-round-trip
//! smoke described in Phase 0.3 of the deep dive (emit a known cube,
//! run NavBuilder, compare bmin/bmax) is the only way to confirm
//! "no double swizzle" empirically. **Phase 0.3 is deferred** to a
//! follow-up PR — flagged here so a future implementer doesn't miss
//! it.

use std::io::{BufWriter, Write};
use std::path::Path;

use crate::geometry::TriangleSoup;

/// Write a single triangle soup to `path` as a Wavefront OBJ.
///
/// Vertex coordinates are written as-is — see the module-level
/// "Axis convention" note. The chunk's group line (if any) is emitted
/// before any geometry.
pub fn write_obj(path: &Path, soup: &TriangleSoup) -> crate::Result<()> {
    let file = std::fs::File::create(path)?;
    let mut w = BufWriter::new(file);
    write_obj_into(&mut w, std::slice::from_ref(soup))?;
    w.flush()?;
    Ok(())
}

/// Write a sequence of triangle soups (typically one per actor) into
/// a single combined OBJ. Vertex indices are re-numbered to account
/// for the per-group offset.
pub fn write_combined_obj(path: &Path, soups: &[TriangleSoup]) -> crate::Result<()> {
    let file = std::fs::File::create(path)?;
    let mut w = BufWriter::new(file);
    write_obj_into(&mut w, soups)?;
    w.flush()?;
    Ok(())
}

/// Lower-level emitter — writes into any `Write`. Exposed so tests
/// can serialise into a `Vec<u8>` without touching the filesystem.
pub fn write_obj_into<W: Write>(w: &mut W, soups: &[TriangleSoup]) -> crate::Result<()> {
    writeln!(w, "# Generated by cimmeria-navmesh-extractor")?;
    writeln!(
        w,
        "# Vertex coordinates are UE3 cm; NavBuilder swizzles on read."
    )?;

    // Vertex indices in OBJ are 1-based AND continuous across groups,
    // so we need to bias each soup's local indices by the running
    // total of vertices written so far.
    let mut vert_offset: u32 = 0;
    for soup in soups {
        if let Some(group) = &soup.group {
            writeln!(w, "o {group}")?;
        }
        for v in &soup.vertices {
            // OBJ uses standard ASCII floats with `.` as the radix
            // point — same as Rust's `Display for f32`.
            writeln!(w, "v {} {} {}", v[0], v[1], v[2])?;
        }
        for f in &soup.faces {
            writeln!(
                w,
                "f {} {} {}",
                f[0] + vert_offset,
                f[1] + vert_offset,
                f[2] + vert_offset
            )?;
        }
        vert_offset += soup.vertices.len() as u32;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::TriangleSoup;

    #[test]
    fn emits_one_triangle_with_three_vertices() {
        let mut soup = TriangleSoup::new(None);
        soup.push([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]);

        let mut buf = Vec::new();
        write_obj_into(&mut buf, &[soup]).unwrap();
        let s = String::from_utf8(buf).unwrap();

        assert!(s.contains("v 1 2 3\n"));
        assert!(s.contains("v 4 5 6\n"));
        assert!(s.contains("v 7 8 9\n"));
        assert!(s.contains("f 1 2 3\n"));
    }

    #[test]
    fn emits_group_label_before_geometry() {
        let mut soup = TriangleSoup::new(Some("Terrain_00000000A".to_string()));
        soup.push([[0.0; 3], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]);

        let mut buf = Vec::new();
        write_obj_into(&mut buf, &[soup]).unwrap();
        let s = String::from_utf8(buf).unwrap();

        let group_pos = s.find("o Terrain_00000000A").expect("group line present");
        let first_v = s.find("\nv ").expect("vertex line present");
        assert!(
            group_pos < first_v,
            "group line must precede the first vertex"
        );
    }

    #[test]
    fn combined_obj_rebases_indices_across_soups() {
        // Two soups, each with a single triangle. The combined OBJ
        // must address the second soup's triangle via vertex indices
        // 4, 5, 6 — not the local 1, 2, 3.
        let mut a = TriangleSoup::new(None);
        a.push([[0.0; 3], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]);
        let mut b = TriangleSoup::new(None);
        b.push([[2.0, 2.0, 2.0], [3.0, 2.0, 2.0], [2.0, 3.0, 2.0]]);

        let mut buf = Vec::new();
        write_obj_into(&mut buf, &[a, b]).unwrap();
        let s = String::from_utf8(buf).unwrap();

        assert!(s.contains("f 1 2 3\n"));
        assert!(s.contains("f 4 5 6\n"));
    }
}
