# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants

class Aftermath(Script):
	n2_var_Player = None
	def n2_propagator_Player(self):
		self.n7_var_Entity = self.n2_var_Player
		self.n13_var_Player = self.n2_var_Player
		self.n14_var_Player = self.n2_var_Player
		self.n15_var_Player = self.n2_var_Player
		self.n16_var_Player = self.n2_var_Player
		self.n17_var_Player = self.n2_var_Player
		self.n18_var_Player = self.n2_var_Player
		self.n19_var_Player = self.n2_var_Player
		self.n20_var_Player = self.n2_var_Player
		self.n21_var_Player = self.n2_var_Player
		self.n22_var_Player = self.n2_var_Player
		self.n24_var_Player = self.n2_var_Player
		self.n25_var_Player = self.n2_var_Player

	def n7_trigger_In(self):
		entity = self.n7_var_Entity
		if entity is not None:
			self.n7_var_Archetype = entity.archetype
			self.n8_var_Set = self.n7_var_Archetype
			self.n8_var_Value = self.n8_var_Set
			self.n9_var_A = self.n8_var_Value
			self.n11_var_A = self.n8_var_Value
			if self.n11_var_A < self.n11_var_B:
				self.n14_var_Player.displayDialog(None, 3942)
				self.n14_propagator_Out()
			self.n9_trigger_In()

	n7_var_Entity = None
	n7_var_Archetype = None
	n8_var_Set = None
	n8_var_Value = None
	def n9_trigger_In(self):
		if self.n9_var_A == self.n9_var_B:
			self.n13_var_Player.displayDialog(None, 3943)
			self.n20_var_Player.missions.advance(687, 2355)
			self.n24_trigger_In()
			self.n25_trigger_In()

	n9_var_A = None
	n9_var_B = None
	n10_var_Set = None
	n10_var_Value = None
	n11_var_A = None
	n11_var_B = None
	n12_var_Set = None
	n12_var_Value = None
	n13_var_Player = None
	def n14_propagator_Out(self):
		self.n15_trigger_In()
		self.n16_trigger_In()
		self.n17_trigger_In()
		self.n18_trigger_In()
		self.n19_trigger_In()
		self.n20_var_Player.missions.advance(687, 2355)
		self.n22_trigger_In()

	n14_var_Player = None
	def n15_trigger_In(self):
		if self.n15_var_Player is None or not 3347:
			return
		if not 1:
			added = self.n15_var_Player.inventory.pickedUpItem(3347, 1 or 1)
		else:
			added = self.n15_var_Player.inventory.addItem(1, 3347, 1 or 1)
		self.n15_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n15_var_Player = None
	def n16_trigger_In(self):
		if self.n16_var_Player is None or not 3359:
			return
		if not 1:
			added = self.n16_var_Player.inventory.pickedUpItem(3359, 1 or 1)
		else:
			added = self.n16_var_Player.inventory.addItem(1, 3359, 1 or 1)
		self.n16_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n16_var_Player = None
	def n17_trigger_In(self):
		if self.n17_var_Player is None or not 3372:
			return
		if not 1:
			added = self.n17_var_Player.inventory.pickedUpItem(3372, 1 or 1)
		else:
			added = self.n17_var_Player.inventory.addItem(1, 3372, 1 or 1)
		self.n17_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n17_var_Player = None
	def n18_trigger_In(self):
		if self.n18_var_Player is None or not 3387:
			return
		if not 1:
			added = self.n18_var_Player.inventory.pickedUpItem(3387, 1 or 1)
		else:
			added = self.n18_var_Player.inventory.addItem(1, 3387, 1 or 1)
		self.n18_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n18_var_Player = None
	def n19_trigger_In(self):
		if self.n19_var_Player is None or not 3401:
			return
		if not 1:
			added = self.n19_var_Player.inventory.pickedUpItem(3401, 1 or 1)
		else:
			added = self.n19_var_Player.inventory.addItem(1, 3401, 1 or 1)
		self.n19_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n19_var_Player = None
	n20_var_Player = None
	n21_var_Player = None
	def n22_trigger_In(self):
		if self.n22_var_Player is None or not 3325:
			return
		if not 1:
			added = self.n22_var_Player.inventory.pickedUpItem(3325, 1 or 1)
		else:
			added = self.n22_var_Player.inventory.addItem(1, 3325, 1 or 1)
		self.n22_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n22_var_Player = None
	def n24_trigger_In(self):
		if self.n24_var_Player is None or not 3482:
			return
		if not 1:
			added = self.n24_var_Player.inventory.pickedUpItem(3482, 1 or 1)
		else:
			added = self.n24_var_Player.inventory.addItem(1, 3482, 1 or 1)
		self.n24_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n24_var_Player = None
	def n25_trigger_In(self):
		if self.n25_var_Player is None or not 2797:
			return
		if not 1:
			added = self.n25_var_Player.inventory.pickedUpItem(2797, 1 or 1)
		else:
			added = self.n25_var_Player.inventory.addItem(1, 2797, 1 or 1)
		self.n25_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n25_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n8_var_Value = 0
		self.n9_var_A = self.n8_var_Value
		self.n11_var_A = self.n8_var_Value
		self.n10_var_Value = 8
		self.n9_var_B = self.n10_var_Value
		self.n12_var_Value = 5
		self.n11_var_B = self.n12_var_Value
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n2_var_Player = self.owner
			self.n2_propagator_Player()
			status = self.n21_var_Player.missions.getStepStatus(687, 2354)
			if status == Constants.MISSION_Active:
				self.n7_trigger_In()
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Cellblock_WoodenCrate', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)

