# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants
from cell.Minigame import Minigame
from common.Config import Config

class HackTheRings(Script):
	n1_var_Player = None
	def n2_trigger_In(self):
		status = self.n2_var_Player.missions.getStepStatus(640, 2120)
		if status == Constants.MISSION_Active:
			self.n3_trigger_In()
		if status == Constants.MISSION_Completed:
			region = self.owner.space.transporters.get(1)
			if region is not None:
				region.interact(self.owner)

	n2_var_Player = None
	def n3_trigger_In(self):
		def mgHandler(self, result):
			if result == Constants.MINIGAME_RESULT_Victory:
				self.n4_var_Player.missions.advance(640, 2215)
			elif result == Constants.MINIGAME_RESULT_Defeat:
				pass
			else:
				pass
		gameIds = [k for k, v in Config.MINIGAME_NAMES.items() if v == 'Livewire']
		assert(len(gameIds) == 1)
		minigame = Minigame('Livewire', 1, gameIds[0], 1, 0xffff, lambda mg, rc: mgHandler(self, rc))
		if not self.n3_var_Player.requestStartMinigame(minigame):
			pass

	n3_var_Player = None
	n4_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n1_var_Player = self.owner
			self.n2_var_Player = self.n1_var_Player
			self.n3_var_Player = self.n1_var_Player
			self.n4_var_Player = self.n1_var_Player
			self.n2_trigger_In()
			return True
		self.n1_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'HackTheRings_Switch', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_TagSubscriptionId)

