// Runtime entity type registry.
//
// Provides O(1) lookup of entity type metadata by name or numeric ID. The
// registry is populated at construction time from the static data generated
// by build.rs.

use std::collections::HashMap;

/// Metadata about a single entity type, available at runtime.
#[derive(Debug, Clone)]
pub struct EntityTypeInfo {
    /// BigWorld entity type name (e.g. "SGWPlayer").
    pub name: String,
    /// Numeric type ID assigned at build time (index order from entities.xml).
    pub id: u16,
    /// Number of properties declared directly on this entity type (not
    /// including inherited properties).
    pub property_count: usize,
}

/// Runtime registry for looking up entity type metadata by name or ID.
///
/// Constructed from the static `ENTITY_TYPE_DATA` array generated by build.rs.
///
/// # Examples
///
/// ```ignore
/// let registry = EntityRegistry::new();
/// if let Some(info) = registry.lookup_by_name("SGWPlayer") {
///     println!("SGWPlayer has {} properties", info.property_count);
/// }
/// ```
pub struct EntityRegistry {
    by_name: HashMap<String, EntityTypeInfo>,
    by_id: HashMap<u16, EntityTypeInfo>,
}

impl EntityRegistry {
    /// Create a new registry populated from the compile-time entity data.
    pub fn new() -> Self {
        let mut by_name = HashMap::new();
        let mut by_id = HashMap::new();

        for &(name, id, property_count) in crate::ENTITY_TYPE_DATA {
            let info = EntityTypeInfo {
                name: name.to_string(),
                id,
                property_count,
            };
            by_name.insert(name.to_string(), info.clone());
            by_id.insert(id, info);
        }

        Self { by_name, by_id }
    }

    /// Look up an entity type by its name.
    pub fn lookup_by_name(&self, name: &str) -> Option<&EntityTypeInfo> {
        self.by_name.get(name)
    }

    /// Look up an entity type by its numeric ID.
    pub fn lookup_by_id(&self, id: u16) -> Option<&EntityTypeInfo> {
        self.by_id.get(&id)
    }

    /// Return the total number of registered entity types.
    pub fn len(&self) -> usize {
        self.by_name.len()
    }

    /// Return true if the registry contains no entity types.
    pub fn is_empty(&self) -> bool {
        self.by_name.is_empty()
    }

    /// Iterate over all registered entity types.
    pub fn iter(&self) -> impl Iterator<Item = &EntityTypeInfo> {
        self.by_name.values()
    }
}

impl Default for EntityRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Debug for EntityRegistry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EntityRegistry")
            .field("count", &self.by_name.len())
            .field("types", &self.by_name.keys().collect::<Vec<_>>())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_constructs_without_panic() {
        let registry = EntityRegistry::new();
        // The registry should have at least zero entries (it should not panic).
        assert!(registry.len() >= 0);
    }

    #[test]
    fn registry_default_is_same_as_new() {
        let a = EntityRegistry::new();
        let b = EntityRegistry::default();
        assert_eq!(a.len(), b.len());
    }

    #[test]
    fn lookup_by_name_and_id_are_consistent() {
        let registry = EntityRegistry::new();
        for info in registry.iter() {
            let by_name = registry.lookup_by_name(&info.name).unwrap();
            let by_id = registry.lookup_by_id(info.id).unwrap();
            assert_eq!(by_name.name, by_id.name);
            assert_eq!(by_name.id, by_id.id);
            assert_eq!(by_name.property_count, by_id.property_count);
        }
    }

    #[test]
    fn missing_name_returns_none() {
        let registry = EntityRegistry::new();
        assert!(registry.lookup_by_name("NonExistentEntity").is_none());
    }

    #[test]
    fn missing_id_returns_none() {
        let registry = EntityRegistry::new();
        assert!(registry.lookup_by_id(u16::MAX).is_none());
    }
}
