//! Seed rendering for `resources.cover_sets` / `resources.cover_nodes`.
//!
//! Output is deterministic for a given input (no timestamps), so a
//! re-extract against the same client build is a byte-identical diff.

use std::fmt::Write as _;

use super::CoverSetOut;

/// `primary_author` for every extracted set. The column predates this
/// extractor (it held the pak's level-designer name); the `.umap` carries
/// no author, so it names the tool instead.
pub const AUTHOR: &str = "cover-extract";

/// Everything the headers need to be reproducible.
#[derive(Debug, Clone)]
pub struct Provenance<'a> {
    /// The command line that regenerates the files.
    pub command: &'a str,
    /// Free-text client build label, e.g. `Stargate Worlds-QA/Working`.
    pub client_build: &'a str,
    /// One line per map: `Castle_CellBlock (world 12): 236 nodes in 40 sets`.
    pub map_lines: &'a [String],
}

fn header(out: &mut String, table: &str, p: &Provenance<'_>) {
    let _ = writeln!(
        out,
        "-- Auto-generated by the cover-extract tool (crates/navmesh-extractor) -- DO NOT EDIT BY HAND."
    );
    let _ = writeln!(out, "-- Table: resources.{table}");
    let _ = writeln!(out, "-- Regenerate: {}", p.command);
    let _ = writeln!(out, "-- Client build: {}", p.client_build);
    let _ = writeln!(
        out,
        "-- Source: SGWSpecCoverNode actors and StaticMeshActor.CoverNodeArray components"
    );
    let _ = writeln!(
        out,
        "-- baked into each map's cooked .umap chunks, already in absolute world space"
    );
    let _ = writeln!(
        out,
        "-- (docs/reverse-engineering/findings/cover-world-placement.md). Positions are"
    );
    let _ = writeln!(
        out,
        "-- BigWorld metres; orient is radians, facing (cos, sin) in BW (x, z)."
    );
    let _ = writeln!(
        out,
        "-- Set ids are world_id * 100000 + n; see crates/navmesh-extractor/src/cover/grouping.rs."
    );
    for line in p.map_lines {
        let _ = writeln!(out, "--   {line}");
    }
    let _ = writeln!(out);
}

fn sql_str(s: &str) -> String {
    s.replace('\'', "''")
}

/// Render the `cover_sets` seed.
pub fn render_cover_sets(sets: &[CoverSetOut], p: &Provenance<'_>) -> String {
    let mut out = String::new();
    header(&mut out, "cover_sets", p);
    if sets.is_empty() {
        return out;
    }
    let _ = writeln!(
        out,
        "INSERT INTO resources.cover_sets (chunk_id, world_id, chunk_name, primary_author, has_variant, src_pak) VALUES"
    );
    for (i, s) in sets.iter().enumerate() {
        let sep = if i + 1 == sets.len() { ";" } else { "," };
        let _ = writeln!(
            out,
            "  ({}, {}, '{}', '{AUTHOR}', false, '{}'){sep}",
            s.set_id,
            s.world_id,
            sql_str(&s.name),
            sql_str(&s.src)
        );
    }
    out
}

/// Render the `cover_nodes` seed. `tail` is written as four zero bytes:
/// the column carries the pak record's unexplained trailer, which a
/// `.umap` marker does not have.
pub fn render_cover_nodes(sets: &[CoverSetOut], p: &Provenance<'_>) -> String {
    let mut out = String::new();
    header(&mut out, "cover_nodes", p);
    let total: usize = sets.iter().map(|s| s.nodes.len()).sum();
    if total == 0 {
        return out;
    }
    let _ = writeln!(
        out,
        "INSERT INTO resources.cover_nodes (chunk_id, node_id, pos_x, pos_y, pos_z, orient, height, quality, width, tail) VALUES"
    );
    let mut written = 0usize;
    for s in sets {
        for (node_id, n) in s.nodes.iter().enumerate() {
            written += 1;
            let sep = if written == total { ";" } else { "," };
            let _ = writeln!(
                out,
                "  ({}, {node_id}, {:.4}, {:.4}, {:.4}, {:.6}, '{}', '{}', {:.4}, '\\x00000000'::bytea){sep}",
                s.set_id,
                n.pos[0],
                n.pos[1],
                n.pos[2],
                n.orient,
                n.height.sql_name(),
                n.quality.sql_name(),
                n.width,
            );
        }
    }
    out
}
