# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class Lucia(Script):
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(18)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRingCenterTop', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(19)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n21_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRingCenter1', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(20)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n23_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRingCenter2', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(21)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n25_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRingCenterLeft', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(22)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n27_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRingCenterRight', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(24)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n29_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRing_fffefff8', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(25)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n31_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRing_fff8fffe', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(26)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n33_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRing_fff90006', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(27)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n35_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRing_0002000b', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(28)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n37_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRing_00070001', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(29)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n39_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'LuciaRing_00080001', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n21_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n23_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n25_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n27_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n29_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n31_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n33_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n35_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n37_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n39_lvar_TagSubscriptionId)

