# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class Menfa_Dark(Script):
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(30)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Menfa_Dark_Ring_00040001', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(31)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n41_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Menfa_Dark_Ring_00040000', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(32)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n43_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Menfa_Dark_Ring_ffff0003', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n41_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n43_lvar_TagSubscriptionId)

