# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class Omega_Site(Script):
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(10)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'OmegaSiteBeamCenter', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(11)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n4_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'OmegaSiteBeamBottom', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(12)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n14_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'OmegaSiteBeamLeft', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(14)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n16_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'OmegaSiteBeamToCmdCenter', interactCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			region = self.owner.space.transporters.get(16)
			if region is not None:
				region.interact(self.owner)
			return True
		self.n18_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'OmegaSiteBeamRight', interactCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n4_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n14_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n16_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n18_lvar_TagSubscriptionId)

