# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script

class SandBox(Script):
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.owner.debug('Sandbox level script loaded')
		def loaded(args):
			self.owner.debug('(SandBox) Player loaded on map')
		self.n3_lvar_SubscriptionId = self.owner.subscribe("player.loaded", loaded)

	def teardown(self):
		self.owner.unsubscribe(self.n3_lvar_SubscriptionId)

