# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants
import Atrea

class SGC_W1(Script):
	n1_var_Player = None
	n2_var_Player = None
	n3_var_Player = None
	n5_var_Player = None
	n6_var_Player = None
	n23_var_Entity = None
	def n24_trigger_In(self):
		self.n24_var_Entity = None
		if None is not None:
			self.n24_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGCW1_GenHammond'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n24_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n24_var_Entity = entity
						break
			else:
				self.n24_var_Entity = None
		self.n23_var_Entity = self.n24_var_Entity
		if self.n24_var_Entity is not None:
			entity = self.n23_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 16777216)

	n24_var_Entity = None
	n25_var_Player = None
	def n26_trigger_In(self):
		if self.n26_var_Source is not None and 10005 is not None:
			target = self.n26_var_Target
			targetId = target.entityId if target else None
			self.n26_var_Source.playSequence(10005, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n26_var_Source = None
	n26_var_Target = None
	n29_var_Player = None
	def n30_trigger_In(self):
		self.n30_var_Entity = None
		if None is not None:
			self.n30_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGCW1_GenHammond'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n30_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n30_var_Entity = entity
						break
			else:
				self.n30_var_Entity = None
		self.n31_var_Entity = self.n30_var_Entity
		self.n100_var_Entity = self.n30_var_Entity
		if self.n30_var_Entity is not None:
			entity = self.n31_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType & ~16777216)

	n30_var_Entity = None
	n31_var_Entity = None
	def n32_trigger_In(self):
		self.n32_var_Entity = None
		if None is not None:
			self.n32_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGC_W1_Tealc'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n32_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n32_var_Entity = entity
						break
			else:
				self.n32_var_Entity = None
		self.n33_var_Entity = self.n32_var_Entity
		if self.n32_var_Entity is not None:
			entity = self.n33_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 16777216)

	n32_var_Entity = None
	n33_var_Entity = None
	n34_var_Player = None
	n35_var_Player = None
	n36_var_Player = None
	def n36_propagator_Player(self):
		self.n37_var_Player = self.n36_var_Player
		self.n38_var_Source = self.n36_var_Player
		self.n38_var_Target = self.n36_var_Player
		self.n39_var_Source = self.n36_var_Player
		self.n39_var_Target = self.n36_var_Player
		self.n99_var_Entity = self.n36_var_Player
		self.n101_var_Player = self.n36_var_Player

	n37_var_Player = None
	def n38_trigger_In(self):
		if self.n38_var_Source is not None and 2319 is not None:
			target = self.n38_var_Target
			targetId = target.entityId if target else None
			self.n38_var_Source.playSequence(2319, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n38_var_Source = None
	n38_var_Target = None
	def n39_trigger_In(self):
		if self.n39_var_Source is not None and 10002 is not None:
			target = self.n39_var_Target
			targetId = target.entityId if target else None
			self.n39_var_Source.playSequence(10002, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)
		self.n99_trigger_In()

	n39_var_Source = None
	n39_var_Target = None
	n43_var_Entity = None
	def n44_trigger_In(self):
		self.n44_var_Entity = None
		if None is not None:
			self.n44_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGC_W1_Tealc'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n44_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n44_var_Entity = entity
						break
			else:
				self.n44_var_Entity = None
		self.n43_var_Entity = self.n44_var_Entity
		if self.n44_var_Entity is not None:
			entity = self.n43_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType & ~16777216)

	n44_var_Entity = None
	def n45_trigger_In(self):
		self.n45_var_Entity = None
		if None is not None:
			self.n45_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGC_W1_ElevatorButton1'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n45_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n45_var_Entity = entity
						break
			else:
				self.n45_var_Entity = None
		self.n46_var_Entity = self.n45_var_Entity
		if self.n45_var_Entity is not None:
			entity = self.n46_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 256)

	n45_var_Entity = None
	n46_var_Entity = None
	n55_var_Player = None
	def n55_propagator_Player(self):
		self.n59_var_Target = self.n55_var_Player
		self.n57_var_Player = self.n55_var_Player
		self.n77_var_Player = self.n55_var_Player
		self.n79_var_Player = self.n55_var_Player
		self.n86_var_Source = self.n55_var_Player
		self.n86_var_Target = self.n55_var_Player
		self.n92_var_Player = self.n55_var_Player

	n57_var_Player = None
	def n59_trigger_In(self):
		pos = self.n59_var_Destination
		self.n59_var_Target.moveTo(pos.x, pos.y, pos.z, worldName = 'SGC_W1' or None)
		self.n79_var_Player.missions.completeObjective(1559, 5358)
		self.n81_trigger_In()
		self.n86_trigger_In()

	n59_var_Target = None
	n59_var_Destination = None
	n60_var_Set = None
	n60_var_Value = None
	def n61_trigger_In(self):
		self.n61_var_Entity = None
		if None is not None:
			self.n61_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGCW1_AirmanWalking'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n61_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n61_var_Entity = entity
						break
			else:
				self.n61_var_Entity = None
		self.n62_var_Entity = self.n61_var_Entity
		if self.n61_var_Entity is not None:
			if self.n62_var_Entity is not None:
				self.n62_var_Entity.addWaypoint(self.n62_var_Position, lambda: None)
			self.n45_trigger_In()

	n61_var_Entity = None
	n62_var_Entity = None
	n62_var_Position = None
	n63_var_Set = None
	n63_var_Value = None
	n71_var_Player = None
	n71_var_Target = None
	n72_var_Player = None
	def n73_trigger_In(self):
		if self.n73_var_Source is not None and 10012 is not None:
			target = self.n73_var_Target
			targetId = target.entityId if target else None
			self.n73_var_Source.playSequence(10012, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n73_var_Source = None
	n73_var_Target = None
	n75_var_Player = None
	n76_var_Player = None
	n77_var_Player = None
	def n78_trigger_In(self):
		if self.n78_var_Player is None or not 55:
			return
		if not 1:
			added = self.n78_var_Player.inventory.pickedUpItem(55, 1 or 1)
		else:
			added = self.n78_var_Player.inventory.addItem(1, 55, 1 or 1)
		self.n78_var_Player.inventory.flushUpdates()
		if added:
			self.n94_var_Player.displayDialog(None, 5358)
		else:
			pass

	n78_var_Player = None
	n79_var_Player = None
	n80_var_Entity = None
	def n81_trigger_In(self):
		self.n81_var_Entity = None
		if None is not None:
			self.n81_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'SGC_W1_FirearmBody'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n81_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n81_var_Entity = entity
						break
			else:
				self.n81_var_Entity = None
		self.n80_var_Entity = self.n81_var_Entity
		if self.n81_var_Entity is not None:
			entity = self.n80_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 0)

	n81_var_Entity = None
	def n82_trigger_Set(self):
		entity = self.n82_var_Entity
		if entity is None:
			return
		entity.setInteractionType(entity.interactionType | 0)
		status = self.n129_var_Player.missions.getMissionStatus(1559)
		if status == Constants.MISSION_Active:
			self.n72_var_Player.missions.complete(1559)
			self.n78_trigger_In()

	def n82_trigger_Unset(self):
		entity = self.n82_var_Entity
		if entity is None:
			return
		entity.setInteractionType(entity.interactionType & ~0)
		status = self.n129_var_Player.missions.getMissionStatus(1559)
		if status == Constants.MISSION_Active:
			self.n72_var_Player.missions.complete(1559)
			self.n78_trigger_In()

	n82_var_Entity = None
	def n86_trigger_In(self):
		if self.n86_var_Source is not None and 10013 is not None:
			target = self.n86_var_Target
			targetId = target.entityId if target else None
			self.n86_var_Source.playSequence(10013, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n86_var_Source = None
	n86_var_Target = None
	n92_var_Player = None
	n94_var_Player = None
	n96_var_Player = None
	def n99_trigger_In(self):
		entity = self.n99_var_Entity
		if entity is not None:
			self.n99_var_Position = entity.position
			self.n100_var_Position = self.n99_var_Position
		if self.n100_var_Entity is not None:
			def waypointCb():
				self.n101_var_Player.displayDialog(None, 5356)
			self.n100_var_Entity.addWaypoint(self.n100_var_Position, waypointCb)

	n99_var_Entity = None
	n99_var_Position = None
	n100_var_Entity = None
	n100_var_Position = None
	n101_var_Player = None
	n128_var_Player = None
	n129_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n60_var_Value = self.str2vec('-123.625,1.311,-246.858')
		self.n59_var_Destination = self.n60_var_Value
		self.n63_var_Value = self.str2vec('237.326,1.312,17.921')
		self.n62_var_Position = self.n63_var_Value
		def loaded(args):
			self.n1_var_Player = self.owner
			self.n2_var_Player = self.n1_var_Player
			self.n3_var_Player = self.n1_var_Player
			self.n26_var_Source = self.n1_var_Player
			self.n26_var_Target = self.n1_var_Player
			status = self.n2_var_Player.missions.getMissionStatus(1559)
			if status == Constants.MISSION_Not_Active:
				self.n3_var_Player.missions.accept(1559)
				self.n24_trigger_In()
		self.n1_lvar_SubscriptionId = self.owner.subscribe("player.loaded", loaded)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n5_var_Player = self.owner
			self.n6_var_Player = self.n5_var_Player
			self.n75_var_Player = self.n5_var_Player
			status = self.n75_var_Player.missions.getStepStatus(1559, 4612)
			if status == Constants.MISSION_Active:
				self.n6_var_Player.displayDialog(None, 5354)
			return True
		self.n5_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGCW1_GenHammond', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n29_var_Player = args['player']
			self.n25_var_Player = self.n29_var_Player
			self.n26_var_Source = self.n29_var_Player
			self.n26_var_Target = self.n29_var_Player
			self.n25_var_Player.missions.advance(1559, 4613)
			self.n26_trigger_In()
			self.n30_trigger_In()
			self.n32_trigger_In()
			return True
		self.n29_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5354), dialogChoiceCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n34_var_Player = self.owner
			self.n35_var_Player = self.n34_var_Player
			self.n76_var_Player = self.n34_var_Player
			status = self.n76_var_Player.missions.getStepStatus(1559, 4613)
			if status == Constants.MISSION_Active:
				self.n35_var_Player.displayDialog(None, 5355)
			return True
		self.n34_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGC_W1_Tealc', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n36_var_Player = args['player']
			self.n36_propagator_Player()
			self.n37_var_Player.missions.advance(1559, 4614)
			self.n38_trigger_In()
			self.n39_trigger_In()
			self.n44_trigger_In()
			return True
		self.n36_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5355), dialogChoiceCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n55_var_Player = self.owner
			self.n55_propagator_Player()
			status = self.n57_var_Player.missions.getStepStatus(1559, 4614)
			if status == Constants.MISSION_Active:
				self.n77_var_Player.missions.completeObjective(1559, 5353)
			self.n92_var_Player.displayDialog(None, 5357)
			return True
		self.n55_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGC_W1_ElevatorButton1', interactCb, once = False)
		def interactCb(args):
			self.n71_var_Target = args['target']
			self.n82_var_Entity = self.n71_var_Target
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n71_var_Player = self.owner
			self.n78_var_Player = self.n71_var_Player
			self.n72_var_Player = self.n71_var_Player
			self.n94_var_Player = self.n71_var_Player
			self.n129_var_Player = self.n71_var_Player
			self.n82_trigger_Unset()
			return True
		self.n71_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'SGC_W1_FirearmBody', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n96_var_Player = args['player']
			self.n59_var_Target = self.n96_var_Player
			self.n59_trigger_In()
			return True
		self.n96_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5357), dialogChoiceCb, once = False)
		def dialogChoiceCb(args):
			self.n61_trigger_In()
			return True
		self.n102_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5356), dialogChoiceCb, once = False)
		def dialogChoiceCb(args):
			self.n128_var_Player = args['player']
			self.n73_var_Source = self.n128_var_Player
			self.n73_var_Target = self.n128_var_Player
			self.n73_trigger_In()
			return True
		self.n128_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5358), dialogChoiceCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n5_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n29_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n34_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n36_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n55_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n71_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n96_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n102_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n128_lvar_SubscriptionId)

