"""Render a reconciliation as Markdown. The JSON output is the dict itself."""

from report.render import dist_table, num, pct, table, usd

KEYS = ("input", "output", "cache_read", "cache_write")


def _share(x):
    return x if isinstance(x, int) else f"{x * 100:.2f}%"


def _checks(checks):
    return table(["check", "value", "limit", "result"],
                 [[c["name"], _share(c["value"]), _share(c["limit"]), "ok" if c["ok"] else "FAIL"] for c in checks])


def cost_state_md(c):
    t, u = c["totals"], c["uncovered"]
    parts = [
        "## Against Claude Code's cost-state records\n",
        f"{c['sessions']} sessions with a cost-state record. Each is compared over the process that wrote it:"
        " the session's requests, subagents included, from the process start on.\n",
        table(["", "est. USD"], [["cost-state total", usd(t["cost_state_usd"])],
                                 ["profiler, same windows", usd(t["profiler_usd"])],
                                 ["profiler minus cost-state", pct(t["gap_share"])],
                                 ["cost-state tokens repriced with the profiler's table", usd(t["repriced_usd"])],
                                 ["cost-state spend on models with no price", usd(t["unpriced_cost_state_usd"])]]),
        f"\nNot covered by any cost-state: {num(u['requests'])} requests, {usd(u['usd'])}"
        f" ({u['sessions_without_cost_state']} sessions without a record, {u['resumed_sessions']} resumed sessions'"
        " requests from before the process that wrote the record).\n",
        "Tokens by model, profiler minus cost-state as a share of the cost-state:\n",
        table(["model", "requests", "cost-state USD", "profiler USD", "input", "output", "cache read", "cache write"],
              [[m["model"], num(m["requests"]), usd(m["cost_state_usd"]), usd(m["profiler_usd"])]
               + [pct(m["gap"][k]) for k in KEYS] for m in c["by_model"]]),
        f"\nPer-session gap (sessions with at least {c['min_session_requests']} requests):\n",
        dist_table([("profiler minus cost-state", c["per_session_gap_share"])], pct),
        "\nChecks:\n",
        _checks(c["checks"]),
    ]
    return "\n".join(parts)


def otel_md(o):
    m, p = o["matched"], o["profiler_only"]
    parts = [
        "## Against OTel `claude_code.api_request` events\n",
        f"{num(o['events'])} events over {o['sessions']} sessions ({num(o['events_without_request_id'])} without a"
        f" request id). OTel `cost_usd` total {usd(o['otel_cost_usd'])}.\n",
        table(["", "requests", "OTel USD", "profiler USD"],
              [["matched on request id", num(m["requests"]), usd(m["otel_cost_usd"]), usd(m["profiler_usd"])],
               ["in OTel only", num(sum(r["requests"] for r in o["otel_only"])), usd(o["otel_only_cost_usd"]), "-"],
               ["in the profiler only, inside OTel's span", num(p["requests"]), "-", usd(p["usd"])]]),
        f"\nMatched requests with different token counts: {num(m['token_mismatches'])}.\n",
        "OTel-only requests (not in any transcript):\n",
        table(["query_source", "model", "requests", "cost_usd", "input", "output", "cache read", "cache write"],
              [[r["query_source"], r["model"], num(r["requests"]), usd(r["cost_usd"]), num(r["input_tokens"]),
                num(r["output_tokens"]), num(r["cache_read_tokens"]), num(r["cache_creation_tokens"])]
               for r in o["otel_only"]]),
    ]
    v = o["vs_cost_state"]
    if v:
        parts.append(f"\nOTel against cost-state for the {v['sessions']} sessions both have: {usd(v['otel_usd'])}"
                     f" vs {usd(v['cost_state_usd'])} ({pct(v['gap_share'])}).\n")
    parts += ["\nChecks:\n", _checks(o["checks"])]
    return "\n".join(parts)


def markdown(r):
    w = r["window"]
    head = (f"# Token profile reconciliation\n\nGenerated by `tools/token-profile/reconcile`. Aggregates only."
            f" Estimated USD is list price, a plan-usage proxy on a Max subscription, not a bill.\n\n"
            f"Window (process starts): {w['since'] or 'start'} to {w['until'] or 'now'}. Price table:"
            f" {r['price_table']}. Result: **{'within tolerance' if r['ok'] else 'OUT OF TOLERANCE'}**.\n")
    body = [cost_state_md(r["cost_state"])]
    if "otel" in r:
        body.append(otel_md(r["otel"]))
    return head + "\n" + "\n\n".join(body) + "\n"
