// GENERATED by `mercury::def_conformance::names_codegen` from
// `entities/entities.xml` and `entities/defs/`. Do not edit by hand; after a
// `.def` change run
// `CIMMERIA_REGEN_NAMES=1 bash tools/build-lane/lane.sh cargo test -p cimmeria-wire names_codegen`.

//! Exposed BaseMethods (client to base), flattened per entity type.

pub(super) const SGW_PLAYER: &[&str] = &[
    "chatJoin", // 0
    "chatLeave", // 1
    "sendPlayerCommunication", // 2
    "chatSetAFKMessage", // 3
    "chatSetDNDMessage", // 4
    "chatIgnore", // 5
    "chatFriend", // 6
    "chatList", // 7
    "chatMute", // 8
    "chatKick", // 9
    "chatOp", // 10
    "chatBan", // 11
    "chatPassword", // 12
    "petition", // 13
    "announcePetition", // 14
    "organizationInvite", // 15
    "organizationInviteByType", // 16
    "organizationKick", // 17
    "organizationRankChange", // 18
    "minigameCallRequest", // 19
    "versionInfoRequest", // 20
    "elementDataRequest", // 21
    "logOff", // 22
    "cancelLogOff", // 23
    "onClientReady", // 24
    "sendDuelChallenge", // 25
    "onSpaceQueueStatus", // 26
    "onSpaceQueueReadyResponse", // 27
    "onSpaceQueuedResponse", // 28
    "perfStats", // 29
];

pub(super) const SGW_GM_PLAYER: &[&str] = SGW_PLAYER.split_at(30).0;

pub(super) const ACCOUNT: &[&str] = &[
    "versionInfoRequest", // 0
    "elementDataRequest", // 1
    "logOff", // 2
    "createCharacter", // 3
    "playCharacter", // 4
    "deleteCharacter", // 5
    "requestCharacterVisuals", // 6
    "onClientVersion", // 7
];
