// GENERATED by `mercury::def_conformance::names_codegen` from
// `entities/entities.xml` and `entities/defs/`. Do not edit by hand; after a
// `.def` change run
// `CIMMERIA_REGEN_NAMES=1 bash tools/build-lane/lane.sh cargo test -p cimmeria-wire names_codegen`.

//! ClientMethods (server to client), flattened per entity type.

pub(super) const SGW_GM_PLAYER: &[&str] = &[
    "onStaticMeshNameUpdate", // 0
    "onSequence", // 1
    "onEntityMove", // 2
    "InteractionType", // 3
    "onEntityFlags", // 4
    "getInteractions", // 5
    "toggleInteractionDebugging", // 6
    "onEntityProperty", // 7
    "onVisible", // 8
    "onKismetEventSetUpdate", // 9
    "onEntityTint", // 10
    "onBeingNameIDUpdate", // 11
    "onTimerUpdate", // 12
    "onEffectUserData", // 13
    "onEffectResults", // 14
    "onLevelUpdate", // 15
    "onTargetUpdate", // 16
    "onBeingNameUpdate", // 17
    "onTopSpeedUpdate", // 18
    "onStateFieldUpdate", // 19
    "onStatUpdate", // 20
    "onStatBaseUpdate", // 21
    "onMeleeRangeUpdate", // 22
    "onArchetypeUpdate", // 23
    "onAlignmentUpdate", // 24
    "onFactionUpdate", // 25
    "BeingAppearance", // 26
    "onSystemCommunication", // 27
    "onPlayerCommunication", // 28
    "onLocalizedCommunication", // 29
    "onTellSent", // 30
    "onChatJoined", // 31
    "onChatLeft", // 32
    "onNickChanged", // 33
    "onOrganizationInvite", // 34
    "onOrganizationJoined", // 35
    "onOrganizationLeft", // 36
    "onMemberJoinedOrganization", // 37
    "onOrganizationRosterInfo", // 38
    "onMemberLeftOrganization", // 39
    "onMemberRankChangedOrganization", // 40
    "onStrikeTeamUpdate", // 41
    "onPvPOrganizationLeaveRequest", // 42
    "onOrganizationNameUpdate", // 43
    "onOrganizationExperienceUpdate", // 44
    "onOrganizationMOTDUpdate", // 45
    "onOrganizationNoteUpdate", // 46
    "onOrganizationOfficerNoteUpdate", // 47
    "onOrganizationCashUpdate", // 48
    "onOrganizationRankUpdate", // 49
    "onOrganizationRankNameUpdate", // 50
    "onSquadLootType", // 51
    "onStartMinigame", // 52
    "onStartMinigameDialog", // 53
    "onStartMinigameDialogClose", // 54
    "onEndMinigame", // 55
    "onSpectateList", // 56
    "onMinigameRegistrationPrompt", // 57
    "minigameRegistrationInfo", // 58
    "addOrUpdateMinigameHelper", // 59
    "removeMinigameHelper", // 60
    "minigameCallDisplay", // 61
    "minigameCallResult", // 62
    "minigameCallAbort", // 63
    "showMinigameContact", // 64
    "setupStargateInfo", // 65
    "updateStargateAddress", // 66
    "stargateRotationOverride", // 67
    "onStargatePassage", // 68
    "onBagInfo", // 69
    "onActiveSlotUpdate", // 70
    "onRemoveItem", // 71
    "onUpdateItem", // 72
    "onRefreshItem", // 73
    "onClearOrgVaultInventory", // 74
    "onCashChanged", // 75
    "onMailHeaderInfo", // 76
    "onMailHeaderRemove", // 77
    "onMailRead", // 78
    "sendMailResult", // 79
    "onMissionUpdate", // 80
    "onStepUpdate", // 81
    "onObjectiveUpdate", // 82
    "onTaskUpdate", // 83
    "offerSharedMission", // 84
    "onContactListUpdate", // 85
    "onContactListDelete", // 86
    "onContactListAddMembers", // 87
    "onContactListRemoveMembers", // 88
    "onContactListEvent", // 89
    "onBMOpen", // 90
    "onBMError", // 91
    "onBMAuctions", // 92
    "onBMAuctionRemove", // 93
    "onBMAuctionUpdate", // 94
    "onBMWatchedItemsUpdate", // 95
    "onVersionInfo", // 96
    "onCookedDataError", // 97
    "onBeginAidWait", // 98
    "onEndAidWait", // 99
    "onDHDReply", // 100
    "onKnownAbilitiesUpdate", // 101
    "onTimeofDay", // 102
    "onOverridePerfStatsRate", // 103
    "onInitialInteraction", // 104
    "onDialogDisplay", // 105
    "onVaultOpen", // 106
    "onTeamVaultOpen", // 107
    "onCommandVaultOpen", // 108
    "onStoreOpen", // 109
    "onStoreUpdate", // 110
    "onStoreClose", // 111
    "onCraftingRespecPrompt", // 112
    "onTrainerOpen", // 113
    "onLootDisplay", // 114
    "onPlayerDataLoaded", // 115
    "onPlayerTeleport", // 116
    "onClientMapLoad", // 117
    "giveAbility", // 118
    "giveXPForLevel", // 119
    "onDisplayDHD", // 120
    "onErrorCode", // 121
    "setupWorldParameters", // 122
    "onMapInfo", // 123
    "clearClientHintedGenericRegions", // 124
    "addClientHintedGenericRegion", // 125
    "onResetMapInfo", // 126
    "onMissionRewardsDisplay", // 127
    "onMissionOfferDisplay", // 128
    "stargateTriggerFailed", // 129
    "onExtraNameUpdate", // 130
    "onExpUpdate", // 131
    "onMaxExpUpdate", // 132
    "onRingTransporterList", // 133
    "onOrganizationCreationResult", // 134
    "launchOrganizationCreation", // 135
    "onUpdateDiscipline", // 136
    "onDisciplineRespec", // 137
    "onUpdateRacialParadigmLevel", // 138
    "onUpdateKnownCrafts", // 139
    "onUpdateCraftingOptions", // 140
    "onAbilityTreeInfo", // 141
    "onClientChallenge", // 142
    "onDuelChallenge", // 143
    "onTradeState", // 144
    "onTradeResults", // 145
    "onSpaceQueued", // 146
    "onSpaceQueueReady", // 147
    "onRemoteEntityCreate", // 148
    "onRemoteEntityMove", // 149
    "onRemoteEntityRemove", // 150
    "onDuelEntitiesSet", // 151
    "onDuelEntitiesRemove", // 152
    "onDuelEntitiesClear", // 153
    "onThreatenedMobsUpdate", // 154
    "onPlayMovie", // 155
    "onCancelMovie", // 156
    "onLOSResult", // 157
    "onShowWaypoints", // 158
    "onShowPath", // 159
    "onDisableShowPath", // 160
    "onSetTarget", // 161
    "onShowNavigation", // 162
];

pub(super) const SGW_PLAYER: &[&str] = SGW_GM_PLAYER.split_at(157).0;

pub(super) const SGW_PET: &[&str] = &[
    "onStaticMeshNameUpdate", // 0
    "onSequence", // 1
    "onEntityMove", // 2
    "InteractionType", // 3
    "onEntityFlags", // 4
    "getInteractions", // 5
    "toggleInteractionDebugging", // 6
    "onEntityProperty", // 7
    "onVisible", // 8
    "onKismetEventSetUpdate", // 9
    "onEntityTint", // 10
    "onBeingNameIDUpdate", // 11
    "onTimerUpdate", // 12
    "onEffectUserData", // 13
    "onEffectResults", // 14
    "onLevelUpdate", // 15
    "onTargetUpdate", // 16
    "onBeingNameUpdate", // 17
    "onTopSpeedUpdate", // 18
    "onStateFieldUpdate", // 19
    "onStatUpdate", // 20
    "onStatBaseUpdate", // 21
    "onMeleeRangeUpdate", // 22
    "onArchetypeUpdate", // 23
    "onAlignmentUpdate", // 24
    "onFactionUpdate", // 25
    "BeingAppearance", // 26
    "onAggressionOverrideUpdate", // 27
    "onAggressionOverrideCleared", // 28
    "onPetAbilityList", // 29
    "onPetStanceList", // 30
    "onPetStanceUpdate", // 31
];

pub(super) const SGW_MOB: &[&str] = SGW_PET.split_at(29).0;

pub(super) const SGW_BEING: &[&str] = SGW_GM_PLAYER.split_at(27).0;

pub(super) const SGW_SPAWNABLE_ENTITY: &[&str] = SGW_GM_PLAYER.split_at(12).0;

pub(super) const SGW_DUEL_MARKER: &[&str] = SGW_GM_PLAYER.split_at(12).0;

pub(super) const ACCOUNT: &[&str] = &[
    "onVersionInfo", // 0
    "onCookedDataError", // 1
    "onCharacterList", // 2
    "onCharacterCreateFailed", // 3
    "onCharacterVisuals", // 4
    "onCharacterLoadFailed", // 5
];
