// GENERATED by `mercury::def_conformance::names_codegen` from
// `entities/entities.xml` and `entities/defs/`. Do not edit by hand; after a
// `.def` change run
// `CIMMERIA_REGEN_NAMES=1 bash tools/build-lane/lane.sh cargo test -p cimmeria-wire names_codegen`.

//! The flattened method tables of every client-visible entity type,
//! keyed by clientIndex (the wire typeID; `<ServerOnly/>` entries take
//! none). Read through `crate::names`.

// One name per line with its index; rustfmt would re-align the index
// comments and fail the generated-file check, so it skips them.
#[rustfmt::skip]
mod base;
#[rustfmt::skip]
mod cell;
#[rustfmt::skip]
mod client;

/// Every client-visible entity type: its clientIndex and its name.
pub(super) const CLASSES: [(u8, &str); 8] = [
    (0x00, "SGWSpawnableEntity"),
    (0x01, "SGWBeing"),
    (0x02, "SGWPlayer"),
    (0x03, "SGWGmPlayer"),
    (0x04, "SGWMob"),
    (0x05, "SGWPet"),
    (0x06, "SGWDuelMarker"),
    (0x07, "Account"),
];

/// The flattened ClientMethods (server to client) of entity type `class_id`, by method index.
pub(super) fn client_methods(class_id: u8) -> &'static [&'static str] {
    match class_id {
        0x00 => client::SGW_SPAWNABLE_ENTITY,
        0x01 => client::SGW_BEING,
        0x02 => client::SGW_PLAYER,
        0x03 => client::SGW_GM_PLAYER,
        0x04 => client::SGW_MOB,
        0x05 => client::SGW_PET,
        0x06 => client::SGW_DUEL_MARKER,
        0x07 => client::ACCOUNT,
        _ => &[],
    }
}

/// The flattened exposed CellMethods (client to cell) of entity type `class_id`, by method index.
pub(super) fn cell_methods(class_id: u8) -> &'static [&'static str] {
    match class_id {
        0x01 => cell::SGW_BEING,
        0x02 => cell::SGW_PLAYER,
        0x03 => cell::SGW_GM_PLAYER,
        0x04 => cell::SGW_MOB,
        0x05 => cell::SGW_PET,
        _ => &[],
    }
}

/// The flattened exposed BaseMethods (client to base) of entity type `class_id`, by method index.
pub(super) fn base_methods(class_id: u8) -> &'static [&'static str] {
    match class_id {
        0x02 => base::SGW_PLAYER,
        0x03 => base::SGW_GM_PLAYER,
        0x07 => base::ACCOUNT,
        _ => &[],
    }
}
