# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from cell.ContentEngine import engine as _content_engine
import Atrea

class ArmYourself(Script):
	n3_var_Player = None
	def n4_trigger_In(self):
		if self.n4_var_Source is not None and 10000 is not None:
			target = self.n4_var_Target
			targetId = target.entityId if target else None
			self.n4_var_Source.playSequence(10000, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n4_var_Source = None
	n4_var_Target = None
	def n5_trigger_In(self):
		self.n5_var_Entity = None
		if None is not None:
			self.n5_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'ArmYourself_FrostBody'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n5_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n5_var_Entity = entity
						break
			else:
				self.n5_var_Entity = None
		self.n6_var_Entity = self.n5_var_Entity
		if self.n5_var_Entity is not None:
			self.n5_propagator_Found()

	def n5_propagator_Found(self):
		entity = self.n6_var_Entity
		if entity is None:
			return
		entity.setInteractionType(entity.interactionType & ~4194304)
		self.n4_trigger_In()

	n5_var_Entity = None
	n6_var_Entity = None
	n17_var_Player = None
	def n17_propagator_Player(self):
		self.n4_var_Source = self.n17_var_Player
		self.n4_var_Target = self.n17_var_Player
		self.n3_var_Player = self.n17_var_Player
		self.n18_var_Player = self.n17_var_Player
		self.n19_var_Player = self.n17_var_Player
		self.n20_var_Player = self.n17_var_Player

	def n18_trigger_In(self):
		if self.n18_var_Player is None or not 55:
			return
		if not 3:
			added = self.n18_var_Player.inventory.pickedUpItem(55, 1 or 1)
		else:
			added = self.n18_var_Player.inventory.addItem(3, 55, 1 or 1)
		self.n18_var_Player.inventory.flushUpdates()
		if added:
			self.n19_trigger_In()
			if self.n20_var_Player and self.n20_var_Player.inventory.updateActiveSlot(3, 1):
				self.n20_var_Player.inventory.flushUpdates()
				pass
		else:
			pass

	n18_var_Player = None
	def n19_trigger_In(self):
		if self.n19_var_Player is None or not 3730:
			return
		if not 0:
			added = self.n19_var_Player.inventory.pickedUpItem(3730, 1 or 1)
		else:
			added = self.n19_var_Player.inventory.addItem(0, 3730, 1 or 1)
		self.n19_var_Player.inventory.flushUpdates()
		if added:
			pass
		else:
			pass

	n19_var_Player = None
	n20_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		if _content_engine.is_handled('mission', 622):
			return
		def dialogCb(args):
			self.n17_var_Player = args['player']
			self.n17_propagator_Player()
			self.n5_trigger_In()
			self.n18_trigger_In()
			self.n3_var_Player.missions.complete(622)
			return True
		self.n17_lvar_SubscriptionId = self.owner.subscribe("dialog.open::" + str(3995), dialogCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n17_lvar_SubscriptionId)

