# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants

class EscapeTheCellblock(Script):
	n1_var_Player = None
	def n3_trigger_In(self):
		status = self.n3_var_Player.missions.getStepStatus(680, 2344)
		if status == Constants.MISSION_Active:
			region = self.owner.space.transporters.get(2)
			if region is not None:
				region.interact(self.owner)

	n3_var_Player = None
	n5_var_Player = None
	n7_var_Player = None
	n11_var_Player = None
	n12_var_Player = None
	n14_var_Invoker = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n1_var_Player = self.owner
			self.n3_var_Player = self.n1_var_Player
			self.n3_trigger_In()
			return True
		self.n1_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Preparation_RingSwitch', interactCb, once = False)
		def teleportCb(args):
			if args['regionId'] != 3:
				return False
			self.n5_var_Player = self.owner
			self.n7_var_Player = self.n5_var_Player
			self.n7_var_Player.missions.advance(680, 2345)
			return True
		self.n5_lvar_HandlerId = self.owner.subscribe('teleport::in', teleportCb, once = True)
		def regionCb(args):
			self.n14_var_Invoker = args['entity']
			self.n11_var_Player = self.n14_var_Invoker
			self.n12_var_Player = self.n14_var_Invoker
			if args['entering']:
				status = self.n11_var_Player.missions.getMissionStatus(681)
				if status == Constants.MISSION_Not_Active:
					self.n12_var_Player.missions.accept(681)
			else:
				pass
		self.n14_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region9', regionCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n5_lvar_HandlerId)
		if self.n14_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n14_lvar_SubscriptionId)

