# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from cell.ContentEngine import engine as _content_engine
from common import Constants
import Atrea

class FindAmbernol(Script):
	n1_var_Player = None
	def n1_propagator_Player(self):
		self.n3_var_Player = self.n1_var_Player
		self.n4_var_Player = self.n1_var_Player
		self.n5_var_Player = self.n1_var_Player
		self.n11_var_Player = self.n1_var_Player
		self.n19_var_Source = self.n1_var_Player
		self.n19_var_Target = self.n1_var_Player
		self.n30_var_Player = self.n1_var_Player
		self.n39_var_Instigator = self.n1_var_Player

	def n3_trigger_In(self):
		if self.n3_var_Player is None or not 19:
			return
		if not 0:
			added = self.n3_var_Player.inventory.pickedUpItem(19, 1 or 1)
		else:
			added = self.n3_var_Player.inventory.addItem(0, 19, 1 or 1)
		self.n3_var_Player.inventory.flushUpdates()
		if added:
			self.n6_trigger_In()
			self.n8_trigger_In()
			self.n11_var_Player.displayDialog(None, 2297)
			self.n19_trigger_In()
		else:
			pass

	n3_var_Player = None
	n4_var_Player = None
	n5_var_Player = None
	def n6_trigger_In(self):
		self.n6_var_Entity = None
		if None is not None:
			self.n6_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'ArmYourself_AmbernolVial'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n6_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n6_var_Entity = entity
						break
			else:
				self.n6_var_Entity = None
		self.n7_var_Entity = self.n6_var_Entity
		if self.n6_var_Entity is not None:
			if self.n7_var_Entity is not None:
				if Atrea.destroyCellEntity(self.n7_var_Entity.entityId):
					pass

	n6_var_Entity = None
	n7_var_Entity = None
	def n8_trigger_In(self):
		self.n8_var_Entity = None
		if None is not None:
			self.n8_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = 'ArmYourself_PrisonerRetrievalUnit'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n8_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n8_var_Entity = entity
						break
			else:
				self.n8_var_Entity = None
		self.n9_var_Entity = self.n8_var_Entity
		self.n39_var_Target = self.n8_var_Entity
		if self.n8_var_Entity is not None:
			self.n9_trigger_In()

	n8_var_Entity = None
	def n9_trigger_In(self):
		ent = self.n9_var_Entity
		if ent is None:
			return
		if self.n9_var_Aggression is not None:
			ent.setAggression(self.n9_var_Aggression)
		target = self.n39_var_Target
		instigator = self.n39_var_Instigator
		if target is not None and instigator is not None and hasattr(target, 'threatGenerated'):
			target.threatGenerated(instigator.entityId, 1000)

	n9_var_Entity = None
	n9_var_Aggression = None
	n10_var_Set = None
	n10_var_Value = None
	n11_var_Player = None
	n12_var_Player = None
	def n14_trigger_In(self):
		if self.n14_var_Player and (19 or None):
			removed = False
			if not removed and 19:
				removed = self.n14_var_Player.inventory.removeItemByDesign(19, 1, False)
			self.n14_var_Player.inventory.flushUpdates()
			if removed:
				pass

	n14_var_Player = None
	def n19_trigger_In(self):
		if self.n19_var_Source is not None and 10001 is not None:
			target = self.n19_var_Target
			targetId = target.entityId if target else None
			self.n19_var_Source.playSequence(10001, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n19_var_Source = None
	n19_var_Target = None
	n25_var_Invoker = None
	n26_var_Player = None
	n27_var_Player = None
	n30_var_Player = None
	def n32_trigger_In(self):
		status = self.n32_var_Player.missions.getStepStatus(639, 2343)
		if status == Constants.MISSION_Active:
			self.n14_trigger_In()
			self.n33_var_Player.missions.complete(639)
			self.n34_var_Player.missions.accept(640)

	n32_var_Player = None
	n33_var_Player = None
	n34_var_Player = None
	n39_var_Target = None
	n39_var_Instigator = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		if _content_engine.is_handled('mission', 639):
			return
		self.n10_var_Value = 1
		self.n9_var_Aggression = self.n10_var_Value
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n1_var_Player = self.owner
			self.n1_propagator_Player()
			status = self.n5_var_Player.missions.getStepStatus(639, 2145)
			if status == Constants.MISSION_Active:
				self.n3_trigger_In()
				self.n4_var_Player.missions.advance(639, 2144)
			return True
		self.n1_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'ArmYourself_AmbernolVial', interactCb, once = False)
		def itemCb(params):
			self.n12_var_Player = params['player']
			self.n14_var_Player = self.n12_var_Player
			self.n32_var_Player = self.n12_var_Player
			self.n34_var_Player = self.n12_var_Player
			self.n33_var_Player = self.n12_var_Player
			self.n32_trigger_In()
			return True
		self.n12_lvar_HandlerId = self.owner.subscribe('item.use::' + str(19), itemCb, once = False)
		def deadCb(args):
			self.n30_var_Player.missions.advance(639, 2343)
			return True
		self.n17_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'ArmYourself_PrisonerRetrievalUnit', deadCb, once = False)
		def regionCb(args):
			self.n25_var_Invoker = args['entity']
			self.n27_var_Player = self.n25_var_Invoker
			self.n26_var_Player = self.n25_var_Invoker
			if args['entering']:
				status = self.n27_var_Player.missions.getStepStatus(639, 2117)
				if status == Constants.MISSION_Active:
					self.n26_var_Player.missions.advance(639, 2145)
			else:
				pass
		self.n25_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region11', regionCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n1_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n12_lvar_HandlerId)
		self.owner.space.unsubscribe(self.n17_lvar_TagSubscriptionId)
		if self.n25_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n25_lvar_SubscriptionId)

