# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants

class Hallway05Controller(Script):
	def n3_trigger_Set(self):
		self.n3_lvar_Value = None
		a = (self.n3_var_A or 0)
		if self.n3_lvar_Value == a:
			status = self.n5_var_Player.missions.getMissionStatus(686)
			if status == Constants.MISSION_Active:
				self.n8_var_Player.missions.complete(686)
		if self.n3_lvar_Value > a:
			status = self.n5_var_Player.missions.getMissionStatus(686)
			if status == Constants.MISSION_Active:
				self.n8_var_Player.missions.complete(686)

	def n3_trigger_In(self):
		self.n3_lvar_Value += 1
		a = (self.n3_var_A or 0)
		if self.n3_lvar_Value == a:
			status = self.n5_var_Player.missions.getMissionStatus(686)
			if status == Constants.MISSION_Active:
				self.n8_var_Player.missions.complete(686)
		if self.n3_lvar_Value > a:
			status = self.n5_var_Player.missions.getMissionStatus(686)
			if status == Constants.MISSION_Active:
				self.n8_var_Player.missions.complete(686)

	n3_var_A = None
	n4_var_Set = None
	n4_var_Value = None
	n5_var_Player = None
	n6_var_Player = None
	n8_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		if _content_engine.is_handled('mission', 686):
			return
		self.n3_lvar_Value = 0
		self.n4_var_Value = 2
		self.n3_var_A = self.n4_var_Value
		self.n6_var_Player = self.owner
		self.n5_var_Player = self.n6_var_Player
		self.n8_var_Player = self.n6_var_Player
		def deadCb(args):
			self.n3_trigger_In()
			return True
		self.n1_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'Hallway05_Guard1', deadCb, once = False)
		def deadCb(args):
			self.n3_trigger_In()
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'Hallway05_Guard2', deadCb, once = False)

	def teardown(self):
		self.owner.space.unsubscribe(self.n1_lvar_TagSubscriptionId)
		self.owner.space.unsubscribe(self.n2_lvar_TagSubscriptionId)

