# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants

class Hallway04Controller(Script):
	n2_var_Player = None
	n3_var_Player = None
	n4_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		if _content_engine.is_handled('mission', 685):
			return
		self.n4_var_Player = self.owner
		self.n2_var_Player = self.n4_var_Player
		self.n3_var_Player = self.n4_var_Player
		def deadCb(args):
			status = self.n2_var_Player.missions.getMissionStatus(685)
			if status == Constants.MISSION_Active:
				self.n3_var_Player.missions.complete(685)
			return True
		self.n1_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'Hallway04_Guard', deadCb, once = False)

	def teardown(self):
		self.owner.space.unsubscribe(self.n1_lvar_TagSubscriptionId)

