# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from cell.ContentEngine import engine as _content_engine
from common import Constants

class MessHall(Script):
	n3_var_Invoker = None
	n4_var_Player = None
	n5_var_Player = None
	n22_var_Player = None
	def n33_trigger_Set(self):
		self.n33_lvar_Value = None
		a = (self.n33_var_A or 0)
		if self.n33_lvar_Value == a:
			status = self.n22_var_Player.missions.getMissionStatus(681)
			if status == Constants.MISSION_Active:
				self.n39_var_Player.missions.complete(681)

	def n33_trigger_In(self):
		self.n33_lvar_Value += 1
		a = (self.n33_var_A or 0)
		if self.n33_lvar_Value == a:
			status = self.n22_var_Player.missions.getMissionStatus(681)
			if status == Constants.MISSION_Active:
				self.n39_var_Player.missions.complete(681)

	n33_var_A = None
	n34_var_Set = None
	n34_var_Value = None
	n39_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		if _content_engine.is_handled('mission', 681):
			return
		self.n33_lvar_Value = 0
		self.n34_var_Value = 2
		self.n33_var_A = self.n34_var_Value
		def regionCb(args):
			self.n3_var_Invoker = args['entity']
			self.n4_var_Player = self.n3_var_Invoker
			self.n5_var_Player = self.n3_var_Invoker
			self.n22_var_Player = self.n3_var_Invoker
			self.n39_var_Player = self.n3_var_Invoker
			if args['entering']:
				pass
			else:
				status = self.n4_var_Player.missions.getMissionStatus(680)
				if status == Constants.MISSION_Active:
					self.n5_var_Player.missions.complete(680)
		self.n3_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + 'Castle_Cellblock.Region9', regionCb, once = False)
		def deadCb(args):
			self.n33_trigger_In()
			return True
		self.n31_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'MessHall_Guard1', deadCb, once = False)
		def deadCb(args):
			self.n33_trigger_In()
			return True
		self.n32_lvar_TagSubscriptionId = self.owner.space.subscribe("entity.dead.tag::" + 'MessHall_Guard2', deadCb, once = False)

	def teardown(self):
		if self.n3_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n3_lvar_SubscriptionId)
		self.owner.space.unsubscribe(self.n31_lvar_TagSubscriptionId)
		self.owner.space.unsubscribe(self.n32_lvar_TagSubscriptionId)

