# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from common import Constants
from cell.Minigame import Minigame
from common.Config import Config

class Preparation(Script):
	n2_var_Player = None
	def n3_trigger_In(self):
		if self.n3_var_Player is None or not 21:
			return
		if not 3:
			added = self.n3_var_Player.inventory.pickedUpItem(21, 1 or 1)
		else:
			added = self.n3_var_Player.inventory.addItem(3, 21, 1 or 1)
		self.n3_var_Player.inventory.flushUpdates()
		if added:
			self.n8_var_Player.missions.advance(641, 3563)
		else:
			pass

	n3_var_Player = None
	def n6_trigger_In(self):
		item = self.n6_var_Player.inventory.findItem(21, 0 or None, not False)
		if item is not None:
			pass
		else:
			self.n3_trigger_In()

	n6_var_Player = None
	n8_var_Player = None
	n23_var_Player = None
	n24_var_Player = None
	n24_var_Target = None
	n25_var_Player = None
	n26_var_Player = None
	n26_var_NPC = None
	n27_var_Player = None
	def n28_trigger_Step(self):
		self.n28_var_Player.missions.advance(641, 3564)
		entity = self.n29_var_Entity
		if entity is None:
			return
		entity.setInteractionType(entity.interactionType & ~8388608)

	n28_var_Player = None
	n29_var_Entity = None
	n30_var_Player = None
	def n30_propagator_Player(self):
		self.n34_var_Player = self.n30_var_Player
		self.n31_var_Player = self.n30_var_Player
		self.n32_var_Player = self.n30_var_Player
		self.n33_var_Player = self.n30_var_Player
		self.n35_var_Player = self.n30_var_Player

	def n31_trigger_In(self):
		def mgHandler(self, result):
			if result == Constants.MINIGAME_RESULT_Victory:
				self.n32_var_Player.displayDialog(None, 3998)
				self.n33_var_Player.missions.complete(641)
				self.n35_var_Player.missions.accept(680)
			elif result == Constants.MINIGAME_RESULT_Defeat:
				pass
			else:
				pass
		gameIds = [k for k, v in Config.MINIGAME_NAMES.items() if v == 'Livewire']
		assert(len(gameIds) == 1)
		minigame = Minigame('', 1, gameIds[0], 1, 0xffff, lambda mg, rc: mgHandler(self, rc))
		if not self.n31_var_Player.requestStartMinigame(minigame):
			pass

	n31_var_Player = None
	n32_var_Player = None
	n33_var_Player = None
	n34_var_Player = None
	n35_var_Player = None
	def n36_trigger_In(self):
		entity = self.n36_var_Entity
		if entity is not None:
			self.n36_var_Archetype = entity.archetype
			self.n40_var_A = self.n36_var_Archetype
			if self.n40_var_A == self.n40_var_B:
				self.n42_var_Player.displayDialog(self.n42_var_NPC, 5023)
			if self.n40_var_A != self.n40_var_B:
				self.n26_var_Player.displayDialog(self.n26_var_NPC, 3999)

	n36_var_Entity = None
	n36_var_Archetype = None
	n38_var_Set = None
	n38_var_Value = None
	n40_var_A = None
	n40_var_B = None
	n42_var_Player = None
	n42_var_NPC = None
	n43_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		self.n38_var_Value = 8
		self.n40_var_B = self.n38_var_Value
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n2_var_Player = self.owner
			self.n8_var_Player = self.n2_var_Player
			self.n23_var_Player = self.n2_var_Player
			self.n6_var_Player = self.n2_var_Player
			self.n3_var_Player = self.n2_var_Player
			status = self.n23_var_Player.missions.getStepStatus(641, 2121)
			if status == Constants.MISSION_Active:
				self.n6_trigger_In()
			return True
		self.n2_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Preparation_SMG1A', interactCb, once = False)
		def interactCb(args):
			self.n24_var_Target = args['target']
			self.n26_var_NPC = self.n24_var_Target
			self.n29_var_Entity = self.n24_var_Target
			self.n42_var_NPC = self.n24_var_Target
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n24_var_Player = self.owner
			self.n25_var_Player = self.n24_var_Player
			self.n26_var_Player = self.n24_var_Player
			self.n36_var_Entity = self.n24_var_Player
			self.n42_var_Player = self.n24_var_Player
			status = self.n25_var_Player.missions.getStepStatus(641, 3563)
			if status == Constants.MISSION_Active:
				self.n36_trigger_In()
			return False
		self.n24_lvar_TplSubscriptionId = self.owner.subscribe("entity.interact.template::" + 'Col Marsh (pet)', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n27_var_Player = args['player']
			self.n28_var_Player = self.n27_var_Player
			self.n28_trigger_Step()
			return True
		self.n27_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5023), dialogChoiceCb, once = False)
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n30_var_Player = self.owner
			self.n30_propagator_Player()
			status = self.n34_var_Player.missions.getStepStatus(641, 3564)
			if status == Constants.MISSION_Active:
				self.n31_trigger_In()
			return True
		self.n30_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + 'Preparation_Terminal', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n43_var_Player = args['player']
			self.n28_var_Player = self.n43_var_Player
			self.n28_trigger_Step()
			return True
		self.n43_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(3999), dialogChoiceCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n2_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n24_lvar_TplSubscriptionId)
		self.owner.unsubscribe(self.n27_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n30_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n43_lvar_SubscriptionId)

