# Automatically generated by Atrea Script Editor
# Script Version: 1.4
# Dataset Version: 1.2

from cell.Script import Script
from cell.ContentEngine import engine as _content_engine
import Atrea
from common import Constants
from cell.Minigame import Minigame
from common.Config import Config
from common.defs.Def import DefMgr

class Prisoner_329(Script):
	n113_var_Player = None
	n114_var_Entity = None
	def n115_trigger_In(self):
		self.n115_var_Entity = None
		if None is not None:
			self.n115_var_Entity = Atrea.findEntityOnSpace(None, self.owner.space.spaceId)
		else:
			tpl = ''
			tag = '329_CellDoorButton'
			entities = Atrea.findEntities(self.owner.space.spaceId)
			if tag:
				for entity in entities:
					if entity.tag == tag:
						self.n115_var_Entity = entity
						break
			elif tpl:
				for entity in entities:
					if entity.template is not None and entity.template.name == tpl:
						self.n115_var_Entity = entity
						break
			else:
				self.n115_var_Entity = None
		self.n114_var_Entity = self.n115_var_Entity
		self.n120_var_Entity = self.n115_var_Entity
		if self.n115_var_Entity is not None:
			entity = self.n114_var_Entity
			if entity is None:
				return
			entity.setInteractionType(entity.interactionType | 256)

	n115_var_Entity = None
	n116_var_Player = None
	def n116_propagator_Player(self):
		self.n117_var_Player = self.n116_var_Player
		self.n118_var_Player = self.n116_var_Player
		self.n119_var_Player = self.n116_var_Player
		self.n131_var_Source = self.n116_var_Player
		self.n131_var_Target = self.n116_var_Player
		self.n144_var_Entity = self.n116_var_Player
		self.n150_var_Player = self.n116_var_Player
		self.n151_var_Player = self.n116_var_Player

	n117_var_Player = None
	def n118_trigger_In(self):
		def mgHandler(self, result):
			if result == Constants.MINIGAME_RESULT_Victory:
				self.n119_var_Player.missions.advance(638, 2116)
				self.n131_trigger_In()
			elif result == Constants.MINIGAME_RESULT_Defeat:
				pass
			else:
				pass
		gameIds = [k for k, v in Config.MINIGAME_NAMES.items() if v == 'Livewire']
		assert(len(gameIds) == 1)
		minigame = Minigame('Cell Door Minigame', 1, gameIds[0], 1, 0xffff, lambda mg, rc: mgHandler(self, rc))
		if not self.n118_var_Player.requestStartMinigame(minigame):
			pass

	n118_var_Player = None
	n119_var_Player = None
	def n120_trigger_Set(self):
		entity = self.n120_var_Entity
		if entity is None:
			return
		entity.setInteractionType(entity.interactionType | 256)
		self.n144_trigger_In()

	def n120_trigger_Unset(self):
		entity = self.n120_var_Entity
		if entity is None:
			return
		entity.setInteractionType(entity.interactionType & ~256)
		self.n144_trigger_In()

	n120_var_Entity = None
	def n131_trigger_In(self):
		if self.n131_var_Source is not None and 1749 is not None:
			target = self.n131_var_Target
			targetId = target.entityId if target else None
			self.n131_var_Source.playSequence(1749, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)
		self.n120_trigger_Unset()

	n131_var_Source = None
	n131_var_Target = None
	n132_var_Player = None
	n133_var_Player = None
	n138_var_Player = None
	n140_var_Player = None
	n141_var_Player = None
	def n142_trigger_In(self):
		dialogSet = DefMgr.get('interaction_set_map', 5866)
		if self.n142_var_Player is not None and dialogSet is not None and self.n142_var_Player.removeDialog(17, dialogSet):
			status = self.n138_var_Player.missions.getStepStatus(638, 2114)
			if status == Constants.MISSION_Active:
				self.n113_var_Player.missions.advance(638, 2115)
				self.n115_trigger_In()

	n142_var_Player = None
	def n143_trigger_In(self):
		dialogSet = DefMgr.get('interaction_set_map', 2794)
		if self.n143_var_Player is not None and dialogSet is not None and self.n143_var_Player.removeDialog(17, dialogSet):
			status = self.n138_var_Player.missions.getStepStatus(638, 2114)
			if status == Constants.MISSION_Active:
				self.n113_var_Player.missions.advance(638, 2115)
				self.n115_trigger_In()

	n143_var_Player = None
	def n144_trigger_In(self):
		entity = self.n144_var_Entity
		if entity is not None:
			self.n144_var_Archetype = entity.archetype
			self.n145_var_Set = self.n144_var_Archetype
			self.n145_var_Value = self.n145_var_Set
			self.n146_var_A = self.n145_var_Value
			self.n148_var_A = self.n145_var_Value
			self.n144_propagator_Successful()

	def n144_propagator_Successful(self):
		if self.n146_var_A == self.n146_var_B:
			dialogSet = DefMgr.get('interaction_set_map', 5865)
			if self.n150_var_Player is not None and dialogSet is not None and self.n150_var_Player.addDialog(17, dialogSet, 0 or None):
				pass
		if self.n148_var_A < self.n148_var_B:
			dialogSet = DefMgr.get('interaction_set_map', 2793)
			if self.n151_var_Player is not None and dialogSet is not None and self.n151_var_Player.addDialog(17, dialogSet, 0 or None):
				pass

	n144_var_Entity = None
	n144_var_Archetype = None
	n145_var_Set = None
	n145_var_Value = None
	n146_var_A = None
	n146_var_B = None
	n147_var_Set = None
	n147_var_Value = None
	n148_var_A = None
	n148_var_B = None
	n149_var_Set = None
	n149_var_Value = None
	n150_var_Player = None
	n151_var_Player = None
	n153_var_Player = None
	n154_var_Player = None
	n155_var_Player = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		if _content_engine.is_handled('mission', 638):
			return
		self.n145_var_Value = 0
		self.n146_var_A = self.n145_var_Value
		self.n148_var_A = self.n145_var_Value
		self.n147_var_Value = 8
		self.n146_var_B = self.n147_var_Value
		self.n149_var_Value = 5
		self.n148_var_B = self.n149_var_Value
		def interactCb(args):
			# TODO: Move this to a "Player Variable" node (Entity type)
			self.n116_var_Player = self.owner
			self.n116_propagator_Player()
			status = self.n117_var_Player.missions.getStepStatus(638, 2115)
			if status == Constants.MISSION_Active:
				self.n118_trigger_In()
			return True
		self.n116_lvar_TagSubscriptionId = self.owner.subscribe("entity.interact.tag::" + '329_CellDoorButton', interactCb, once = False)
		def dialogChoiceCb(args):
			self.n140_var_Player = args['player']
			self.n142_var_Player = self.n140_var_Player
			self.n138_var_Player = self.n140_var_Player
			self.n113_var_Player = self.n140_var_Player
			self.n142_trigger_In()
			return True
		self.n140_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5021), dialogChoiceCb, once = False)
		def dialogChoiceCb(args):
			self.n141_var_Player = args['player']
			self.n143_var_Player = self.n141_var_Player
			self.n138_var_Player = self.n141_var_Player
			self.n113_var_Player = self.n141_var_Player
			self.n143_trigger_In()
			return True
		self.n141_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2300), dialogChoiceCb, once = False)
		def dialogChoiceCb(args):
			self.n153_var_Player = args['player']
			self.n155_var_Player = self.n153_var_Player
			self.n133_var_Player = self.n153_var_Player
			self.n132_var_Player = self.n153_var_Player
			self.n155_var_Player.displayDialog(None, 2298)
			self.n133_var_Player.missions.accept(639)
			self.n132_var_Player.missions.complete(638)
			return True
		self.n153_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(5020), dialogChoiceCb, once = False)
		def dialogChoiceCb(args):
			self.n154_var_Player = args['player']
			self.n155_var_Player = self.n154_var_Player
			self.n133_var_Player = self.n154_var_Player
			self.n132_var_Player = self.n154_var_Player
			self.n155_var_Player.displayDialog(None, 2298)
			self.n133_var_Player.missions.accept(639)
			self.n132_var_Player.missions.complete(638)
			return True
		self.n154_lvar_SubscriptionId = self.owner.subscribe("dialog.choice::" + str(2299), dialogChoiceCb, once = False)

	def teardown(self):
		self.owner.unsubscribe(self.n116_lvar_TagSubscriptionId)
		self.owner.unsubscribe(self.n140_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n141_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n153_lvar_SubscriptionId)
		self.owner.unsubscribe(self.n154_lvar_SubscriptionId)

