# Automatically generated by Atrea Script Editor
# Script Version: 1.3
# Dataset Version: 1.1.1

from cell.Script import Script

class TestMission(Script):
	n6_var_Invoker = None
	def n15_trigger_In(self):
		if self.n15_var_Source is not None:
			target = self.n15_var_Target
			if target:
				targetId = target.entityId
			else:
				targetId = None
			self.n15_var_Source.playSequence(0, targetId, True,
				0, viewType = 0, instanceId = 0,
				playOnSelf = True, playOnWitnesses = True)

	n15_var_Source = None
	n15_var_Target = None
	def __init__(self, owner, storedVars):
		Script.__init__(self, owner, storedVars)
		def regionCb(args):
			self.n6_var_Invoker = args['entity']
			self.n15_var_Source = self.n6_var_Invoker
			self.n15_var_Target = self.n6_var_Invoker
			if args['entered']:
				self.n15_trigger_In()
			else:
				pass
		self.n6_lvar_SubscriptionId = self.owner.subscribe("client_hinted_region::" + '', regionCb, once = False)

	def teardown(self):
		if self.n6_lvar_SubscriptionId:
			self.owner.unsubscribe(self.n6_lvar_SubscriptionId)

	def persist(self):
		pass

	def restore(self):
		pass

